### ISSUE TITLE
Material eintragen, darüber Autoren eintragen? 

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#1]
Material eintragen, darüber Autoren eintragen?  Kann man in Pods aktiviern, dann werden bei dem Ziep CPT aber kein Titel und nichts eingetragen sondern nur ein leerer Datensazt angelegt. Benötigt also noch eigene Programmierung.

**Comment by empeiria** [comment]
Ist zwar mühselig - ringt uns aber die Entscheidung ab, ob die Autoren wichtig sind oder ob es ausreicht, dass die Insitution angegeben wird.
Ich entscheide bislang danach ob ein Landeskirchlicher Bezug da ist / Autoren in Instituten arbeiten.
