### ISSUE TITLE
Organisation kommt nach Umbenennung zweimal in den Facetten vor

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-materialpool#100]
![image](https://cloud.githubusercontent.com/assets/307023/21359438/96687d66-c6dc-11e6-99e6-f7cdbddc670e.png)
Ich hatte hinter den Organisationsnamen Planetschule in Klammern WDR gesetzt.
später habe ich das Rückgängig gemacht,
Trotzdem bleibt der Eintrag in der Facettierten suche
Auch das Neuindexieren hat nicht gebracht

**Comment by johappel** [comment]
Anscheinend wir der facetwp index nicht erneuert:
![grafik](https://cloud.githubusercontent.com/assets/307023/21361580/e6e17344-c6e4-11e6-8a8c-332160a80b7a.png)

**Comment by johappel** [comment]
Nein, das ist es nicht, der Wert der Organisation wird aus irgendeinem Grund hart in der wp_postmeta gespeichert:
![grafik](https://cloud.githubusercontent.com/assets/307023/21362362/56f16d9e-c6e8-11e6-8eae-2e6753a17d8f.png)

**Comment by johappel** [comment]
Wenn ich das Maetrial mit der ID 666 neu speichere, wird auch der postmeta erneuert:
![grafik](https://cloud.githubusercontent.com/assets/307023/21362525/00c0dc2e-c6e9-11e6-9c21-33d1260c021d.png)
und auch der facet_wp_index korrekt geschrieben:
![grafik](https://cloud.githubusercontent.com/assets/307023/21362557/2d9f901e-c6e9-11e6-9884-694a33cf22f9.png)

*Fazit* 
Nach ändern des Ornanisationsnamens (Wahrscheinlich auch Autornamens) müssen alle verbundenen Materialien neu gespeichert werden :-(

**Comment by staude** [comment]
Pods speichert nur die ID, die ich nicht als Facette verwenden kann. Daher ist mit https://github.com/rpi-virtuell/rw-materialpool/commit/7dfc57fee4a2ccff4da180b14dd5d6952a87eea4 eingebaut das bei speichern die als Klartext in die Meta gepackt werden, worauf die Facette dann greift.
Brauchen also das Gegenteil, beim Speichern von Orga / Autor muss das beim Material ggf auch erneuert werden.
