### ISSUE TITLE
Verweise lassen sich nicht löschen

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-materialpool#102]
*Beispiel*: http://material.rpi-virtuell.de/wp-admin/post.php?post=800&action=edit
![video_02](https://cloud.githubusercontent.com/assets/307023/21564909/c0ca86a0-ce91-11e6-9c72-c92dd9f7e149.gif)

**Comment by staude** [comment]
Kann ich bei dem genannten Material nicht nachavollziehen. Verweise wurden gelöscht. Bitte noch mal selbst versuchen und die Browser Konsole im Blick behalten.

**Comment by staude** [comment]
Da noch nicht wieder Aufgetreten sei dem, lösche ich das Ticket mal.
