### ISSUE TITLE
Bilder auf der Detailseite

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#105]
Ich arbeite gerade im Reformationsblog. Dort werden die Bilder, die ich eingebe, in einem sehr unglücklichen Ausschnitt wiedergegeben und ich kann nichts beeinflussen.
Zum Beispiel hier:
http://blogs.rpi-virtuell.de/reformation/2017/01/04/luther-360/?preview_id=486&preview_nonce=5104c6c89c&post_format=standard&_thumbnail_id=540&preview=true

oder hier:
http://blogs.rpi-virtuell.de/reformation/2016/10/04/reformation-kompetenzorientiert-thesen-inhalte-kompetenzen-und-unterrichtliche-zugaenge/?preview_id=254&preview_nonce=12701f6f2e&post_format=standard&_thumbnail_id=580&preview=true

das ist eigentlich das Logo der "Evangelischen Kirche Pfalz Religionsunterricht". Eine Werbung für ein Institut ist dieses Logo fürwahr nicht. Entweder müssten die Blogbilder so sein, wie bei den News oder ich müsste den Ausschnitt beeinflussen können.

**Comment by johappel** [comment]
Gehört nicht zum Materialpool.
Links, die ein "preview=true" enthalten, sind Vorschauseiten und können nur vom Autor gesehen werden.
![grafik](https://cloud.githubusercontent.com/assets/307023/22057650/f0b31e4e-dd65-11e6-9350-b21d1970ad80.png)

**Comment by staude** [comment]
bei bedarf auf https://github.com/rpi-virtuell/reliwerk/issues weiterführen
