### ISSUE TITLE
Bildquellen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#106]
Noch etwas zu den Bildern: Im Lutherblog taucht unten die Bildquelle auf. Dabei wird der Titel des Bildes angegeben, so wie ich ihn eingegeben habe und danach die Bildquelle, wie sie beim Bild direkt eingetragen wurde. Bei den News ist es genau so. Das hat folgende Konsequenzen: Ich muss mir bei der Namensgebung des Bildes immer im Klaren sein, dass das nachher so Eins:Eins im Frontend auftaucht. Oft ist der Name, den ich einem Bild gebe, ganz ähnlich, wie der eigentliche Name, dann liest es sich komisch:
http://news.rpi-virtuell.de/?p=19226&preview_id=19226&preview_nonce=18243d3862&post_format=standard&_thumbnail_id=19228&preview=true
Das kommt ganz oft vor und sieht manchmal noch seltsamer aus wie in diesem Beipspiel.
Meiner Meinung nach würde der Name, der in der Bildquelle auftaucht, ausreichen.
Vielleicht kommt das von dem Gedanken, dass bei flickr der Titel verlangt wird. Aber der Titel ist ja etwas anderes als das, was ich über das Bild schreibe. Und die wenigsten Bilder haben Titel und flickr verwenden wir so gut wie nicht mehr. Also, hier wünschte ich mir eine andere Lösung.

**Comment by johappel** [comment]
Ghört auch nicht in die Materialpool Issues
http://news.rpi-virtuell.de/?p=19226&preview_id=19226&preview_nonce=18243d3862&post_format=standard&_thumbnail_id=19228&preview=true
ist ein Vorschaulink (preview=true) andere Nutzer können den nicht öffenen.
Wir sollten hierzu noch mal eien WOrkshop machen.
