### ISSUE TITLE
Blogs Bild

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#107]
Und wenn ich schon mal dabei bin: das Bild bei den Blogs, sozusagen das Titelbild, mit dem schlecht ausgeleuchteten Schlagzeug, ist soooo finster, ich kann kaum etwas erkennen. Wenn es nur DER Bezug zur rpi-virtuell wäre, von mir aus. Aber auf den komme ich auch bei längerem Nachdenken nicht. Hier spielt jemand auf? Oder so? Also bitte, wenn ich dieses Bild reingemacht hätte, dann würde ich euch gerne hören.

**Comment by johappel** [comment]
Dieses Problem gehört nicht zum Materialpool
