### ISSUE TITLE
Frontend Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#108]
RPI Loccum hat für das Reformationsjahr eine Zusammenstellung gemacht. Die Materialien haben im Backend Abstände dazwischen zu besseren Lesbarkeit. Im Frontend erscheint alles aneinendergeschrieben. Ich habe jetzt mit Fettschrift versucht, Unterschiede hervorzuheben, denn ich konnte im Backend keine Abstände machen. Es ging einfach nicht.
Das größere Bild finde ich sehr schön. Bei einer halbierten Seite schieben sich Text und Bild ineinander.

**Comment by staude** [comment]
Im Backend
![2017-04-11_1428](https://cloud.githubusercontent.com/assets/870951/24909204/41a461ca-1ec3-11e7-9d69-c3794abd5aca.png)

Frontend
![2017-04-11_1429](https://cloud.githubusercontent.com/assets/870951/24909232/5bf6ee6c-1ec3-11e7-9f39-b6d361377a68.png)
