### ISSUE TITLE
Nur männliche Form bei den Autoren

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#109]
Bei den Autoren finde ich es kein Problem "der Autor / die Autorin" zu schreiben. Es ist genug Platz da und es ist auch wie eine Überschrift.
Hier finde ich zum Beispiel die männliche Form einfach unpassend:
http://material.rpi-virtuell.de/?post_type=autor&p=951&preview=true

**Comment by johappel** [comment]
+1
