### ISSUE TITLE
Bildquelle verändert - alte Adresse bleibt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#110]
http://blogs.rpi-virtuell.de/reformation/2017/01/04/luther-360/
Bei diesem Beitrag hatte ich eine Bildquelle von evangelisch.de; einen Playmobil Luther von Peter roggenthin. In der Zwischenzeit habe ich eigene Playmo-Luther-Bilder gemacht und das Bild ersetzt mit meinem eigenen. Es tauchen aber im Frontend nach wie vor beide Bildquellen auf: die alte, zu der es das Bild gar nicht mehr gibt und die neue mit Bild.

**Comment by johappel** [comment]
Das ist kein Materialpooleintrag: http://blogs.rpi-virtuell.de/reformation/2017/01/04/luther-360/

**Comment by lehr-ruetsche** [comment]
Dann gib mir einfach die Adresse, wo ichs eintragen soll.

**Comment by staude** [comment]
@lehr-ruetsche 
Alles was Materialpool ist https://github.com/rpi-virtuell/rw-materialpool/issues
Alles andere https://github.com/rpi-virtuell/reliwerk/issues
