### ISSUE TITLE
Verweis auf weiteres Material

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#111]
Ich habe eben Materialien des MDR in den Materialpool eingetragen:
*http://material.rpi-virtuell.de/material/spezial-zum-jubilaeumsjahr-2017/

Nun gibt es noch weitere Materialien des MDR, die auf der Organisationsseite auch angezeigt werden. 
Das wusste ich nun zufällig, aber das weiß ich ja nicht immer, ob es von einer Organisation auch noch andere Einträge gibt. Ist daran gedacht, dass auf einer Materialpoolseite des EINEN Materials auch auf weitere Materialien dieser Organisationen hingewiesen wird? Oder erfährt man das nur, wenn man auf Organisationen geht?

**Comment by johappel** [comment]
Das wäre eine nettes Feature

**Comment by lehr-ruetsche** [comment]
stimmt, bei manchen Organisationen schon :-)

**Comment by staude** [comment]
Einen Link "Weiteres Material dieser Orga/Autor" unter jede Orga und jeden Autor setzen?

Einfach die n neusten Materialien beim Material auflisten find ich auch  schwierig, das ist ja wahrscheinlich thematisch nichts passendes zum aktuell angeschauten Material und der Kontext ist nur, das es  vom gleichen Auoren/Orga ist.

**Comment by lehr-ruetsche** [comment]
Eure Argumentation ist mir einsichtig. Könnte sich echt auswachsen.

 

Von: Frank Staude [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. Januar 2017 10:43
An: rpi-virtuell/rw-materialpool
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/rw-materialpool] Verweis auf weiteres Material (#111)

 

Einen Link "Weiteres Material dieser Orga/Autor" unter jede Orga und jeden Autor setzen?

Einfach die n neusten Materialien beim Material auflisten find ich auch schwierig, das ist ja wahrscheinlich thematisch nichts passendes zum aktuell angeschauten Material und der Kontext ist nur, das es vom gleichen Auoren/Orga ist.
