### ISSUE TITLE
Übertrag von Texten

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#112]
Ich habe eben den Film von Mirko Drotschmann des MDR eingetragen. Und zwar übernommen aus den News:
http://blogs.rpi-virtuell.de/reformation/2016/09/24/promis-der-geschichte-erklaert-von-mirko-drotschmonn/
Da ich dabei auf einen YouTube-Eintrag zurückgegriffen habe, haben sich Textfelder automatisch gefüllt.
Allerdings tauchte der etwas längere Text insgesamt in der Kurzbeschreibung auf. Das ging mir schon mehrmals so. Ich schneide ihn dan aus und füge ihn unten ein. Könnte man das so einrichten, dass Inhaltsbeschreibungen im größeren Beschreibungsfeld landen und nicht in der Kurzbeschreibung? Die sollte ja wirklich kurz sein.

**Comment by johappel** [comment]
+1

**Comment by staude** [comment]
Der Punkt ist, das wenn man über das Bookmarklet Text markiert, dieser in die Beschreibung übernommern wird. Darum wird eine beim url crawlen gefundene beschreibung in die kurzbeschreibung aufgenommen. 

Wie soll das verhalten  da dann sein?
@lehr-ruetsche @johappel

**Comment by johappel** [comment]
Ok, wir setzen die geparsten Inhalte in die Beschreibung
