### ISSUE TITLE
Autor im Frontend des Materials

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#113]
Ich habe den Film von Mirko Drotschmann eingetragen. Bei Autor habe ich nichts eingetragen, weil ich Drotschmann erst noch anlegen musste. Ich habe Mirko Drotschmann auch als Autor angelegt, weil ich weiß, dass es von ihm noch mehr im Materialpool gibt. Bei seinem Autoreintrag habe ich sein Material angegeben, auch den MDR als Organisation. Aber das Material hat sich nicht automatisch zugeordnet. Ich dachte, das würde es tun.
Ich musste also nochmals in das Material und dort Mirko Drostschmann suchen, er war dann auch da, aber eben nicht automatisch. Im Frontend sieht man vom Autor gar nichts.

**Comment by staude** [comment]
Link?

**Comment by lehr-ruetsche** [comment]
http://material.rpi-virtuell.de/material/martin-luther-promis-der-geschichte-erklaert-von-mirko-drotschmann-2/?preview_id=964&preview_nonce=cf634342b0&preview=true

 

Von: Frank Staude [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. Januar 2017 10:37
An: rpi-virtuell/rw-materialpool
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/rw-materialpool] Autor im Frontend des Materials (#113)

 

Link?
