### ISSUE TITLE
Interimsorganisation im Frontend

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#114]
http://material.rpi-virtuell.de/?post_type=material&p=980&preview=true

Wenn es eine bekannte Organisation ist, taucht sie im Frontend beim Material auf. Wenn es eine Interimsorganisation ist, nicht. Ist das so geplant?

**Comment by johappel** [comment]
Interims-Autor und -Organisation sollen unter der Beschreibung ausgegeben werden.
