### ISSUE TITLE
Nochmals: Organisation verbindet sich nicht mit dem Material

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#116]
http://material.rpi-virtuell.de/material/martin-luther-im-kloster/

Hier habe ich zuerst das Material eingegeben. Dann die Organisation. Bei der Organisation das Material. Als ich wieder auf die Materialseite ging, hatte sich nichts verknüpft. Auch nach mehrmaligen neuen Speichern und Hochladen nicht.
Beide Materialien sind veröffentlicht. Eine automatische Zuordnung der Organisation zum Materialpooleintrag über das Material erfolgt meines Erachtens nicht.

**Comment by staude** [comment]
und bei welcher Organisation hast du das Material zugeordnet?

**Comment by lehr-ruetsche** [comment]
Die zuletzt eingetragene Organisation: Dekanatämter Schorndorf und Waiblingen

**Comment by staude** [comment]
Da ist auch kein Material zugeordnet, so gesehen alles richtg. Hattest du nach dem Material zuordnen noch mal gespeichert?

**Comment by johappel** [comment]
Das geleiche Problem! Dopperlter Eintrag:
![grafik](https://cloud.githubusercontent.com/assets/307023/22063151/953f58a8-dd7d-11e6-9eb2-8df9e2b2a828.png)
