### ISSUE TITLE
Werk und Bände

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#117]
Ich habe die Zeitschrift rpi-impulse 2/2016 insgesamt eingegeben:

http://material.rpi-virtuell.de/material/reformation-heute-glauben-neu-entdecken/

Dann habe ich zwei einzelne Artikel aus der Zeitschrift eingegeben und auf rpi-impulse als Werk verwiesen.

Auf keiner der beiden Frontendseiten ist das erschienen:

http://material.rpi-virtuell.de/material/reformation-2-0-mit-dem-smartphone-auf-den-spuren-luthers/

http://material.rpi-virtuell.de/material/lutherbilder-hinterfragen/?preview_id=999&preview_nonce=775c7cb560&preview=true

Die Bände haben sich auch gegenseitig nicht erkannt, aber gut, das ist vielleicht etwas viel verlangt. Ich habe sie ja nicht eingegeben. Aber wenn ich die Bände in großem zeitlichen Abstand eingebe, dann weiß ich ja auch nicht, dass es da vielleicht schon mal einen Band gegeben hat.

Was habe ich diesmal falsch gemacht?

**Comment by lehr-ruetsche** [comment]
Ich habe jetzt einen dritten Artikel eingegeben. Die Zeitschrift habe ich wieder als Werk angegeben. Die beiden letzten Artikel habe ich unter Werk angegeben. Im Frontend ist nichts zu sehen.
http://material.rpi-virtuell.de/material/luthers-95-thesen-erlebbar-gemacht/

**Comment by staude** [comment]
wird auch aktuell im template noch nicht ausgegeben

**Comment by lehr-ruetsche** [comment]
Allerdings haben sie sich im Backend auch nicht gegenseitig ergänzt.

**Comment by staude** [comment]
Wieso? bei http://material.rpi-virtuell.de/material/luthers-95-thesen-erlebbar-gemacht/ ist als Werk http://material.rpi-virtuell.de/material/weisst-du-denn-gar-nicht-wie-schoen-du-bist/ angegeben und das wiederum hat 4 Bände laut Backend.

**Comment by lehr-ruetsche** [comment]
Ja, nachdem nichts ging, habe ich alle schön von Hand eingegeben.

**Comment by lehr-ruetsche** [comment]
Das geht aber nur, wenn alles am STück ist, so wie eben, und ich mich  noch erinnere.
