### ISSUE TITLE
Embed für Autoren/Orga/Material stylen und Inhalt festlegen

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#122]
Embed für Autoren/Orga/Material stylen und Inhalt festlegen

**Comment by johappel** [comment]
Material:
Thumbnail?, Titel, Kurzbeschreibung, Medientyp, Bildungsstufe, Link zur Materialdetail
Autoren: 
Titel, Bild, Link zur Autorenseite (Liste erste 5 neuesten Treffer von Materialien?)
Organisation:  
Titel, Logo, Liste erste 5 neuesten Treffer von Materialien)
Allgemein:
Link zum Materialpool + rpi-logo

**Comment by staude** [comment]
Material commited
