### ISSUE TITLE
Autor erscheint nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#128]
Ich habe jetzt zweimal neue Materialien angelegt. Dann für das eine eine Organisation und  das andere einen Autor angelegt und das Material eingetragen. Alles veröffentlicht. Alles neu hochgeladen. Dennoch erschienen beim Material weder der Autor noch die Organisation automatisch. Ich musste sie Händisch nachtragen.

**Comment by staude** [comment]
Wenn es nochmal passiert. nicht Nachpflegen sondern ein Ticket erstellen mit URL wo das zu sehen ist. Danke.
