### ISSUE TITLE
Logos bei den Organisationen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#130]
Das mit den Logos ist etwas schwierig. Ich habe oft astreine Logos zur Verfügung, aber wenn ich sie einbaue, kommen sie völlig verpixelt im Frontend der Organisation an. Otto Ziegelmeier von theology.de hat mir 5 zugesandt, davon konnte ich genau eines verwenden, das kleinste.

**Comment by johappel** [comment]
könnte man evtl eine plugin nutzen, dass die Dateien in Kategorien ordnet?

**Comment by johappel** [comment]
ich brauc
