### ISSUE TITLE
wo gehts zum Link?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#131]
Ich habe den "Zehn-Meter-Turm" von Webcomeptent eingegeben. Früher konnte man auf den Titel klicken und war dann auf der Seite. Oder bilde ich mir das ein? Jetzt muss man den Link ganz schön suchen. Oben links, das ganz kleine, das ist der Link zum Material!

**Comment by johappel** [comment]
Kannst du den Link zum Material angeben. Erspart mir echt arbeit.
Ich finde keine Eintarg mit zehn meter turm im Materialpool.

**Comment by staude** [comment]
@johappel http://material.rpi-virtuell.de/material/der-zehn-meter-turm/
@lehrruetsche "das ganz kleine"? so klein finde ich das nicht

![2017-01-31_0929](https://cloud.githubusercontent.com/assets/870951/22557292/6beace1c-e96a-11e6-9bbc-50f8b90eb5ae.png)
