### ISSUE TITLE
Mediatheken

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#132]
Was wirklich ungünstig ist: dass wir keinen gemeinsamen Medienpool haben. Es kann gut sein, dass es ein Logo bereits gibt, aber es steckt in einer anderen Datei. Dort wären auch die Rechte vermerkt. Dann findet man das Logo nicht und fragt nochmal an. Oder ich bin mir ziemlich sicher, dass wir das Schöpfungsbild von da Vinci schon irgendwo hatten. Jetzt haben wirs halt nochmal. Das Problem ist weniger das ständige neue Suchen, sondern die Rechtegeschichte, die man vielleicht ja schon mal geklärt hatte. Nur das Bild befindet sich beim Reformationsblog oder im Materialpool oder bei den News oder...

**Comment by johappel** [comment]
Selbstorganisation ist das halbe Leben:-)
Aber eine technische Lösung die einem die Ordnung abnimmt, ist mir nicht bekannt

**Comment by johappel** [comment]
Man kann ja einmal erfasste bilder einbetten, statt sie neu Hochzuladen. Dann braucht man die Rechte  nur einmal klären.
