### ISSUE TITLE
Begrüßungsmail

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#148]
Bei Neuanlage von Orga / Autor eine Begrüßungsmail versenden(auf Knopfdruck, nicht automatisch)

- 2 Textvorlagen im Backend pflegbar.
- Benötigte Macros?

**Comment by staude** [comment]
@lehrruetsche Welche Makros werden benötigt für die Texterstellung?

**Comment by johappel** [comment]
Vorschlag
%materialpool_home%
%material_autor_url%
%material_orga_url%
%material_autor_name%
%material_last_material%

%redakteur_name%
%redakteur_reply_email%

**Comment by lehrruetsche** [comment]
Liebe Frank, da ich etwas unsicher bin, wie das Ganze programmiertechnisch vor sich geht, hier ein erster Vorschlag mit der Bitte um Rückmeldung:
Lieber Herr…
Liebe Frau….
wir freuen uns, dass wir im ‚neuen rpi-virtuell‘ auf WordPress die Möglichkeit haben, Sie als Autor/in ausführlicher vorzustellen. Neu bei rpi-virtuell eingetragene Materialien werden automatisch zugeordnet und sind so auch über Ihren Namen auffindbar.
Sie können Ihren Eintrag auf dieser Seite finden:
Wenn Sie Änderungswünsche haben, lassen Sie uns dies bitte wissen.
Mit freundlichen Grüßen
Andrea Lehr-Rütsche
Redaktion rpi-virtuell/Comenius-Institut Münster

**Comment by staude** [comment]
@lehrruetsche Wie @johappel ja schon begonnen hat, ist die Frage welche Platzhalter du benötigst die beim versenden dann entsprechend gefüllt werden. 
Herr/Frau unterscheiden wir bei den Autoren ja nicht.

**Comment by johappel** [comment]
Guten Tag %material_autor_name%

Bei unserer Recherche nach geeigneten Inhalten und Medien für die religionspädagogische Arbeit  haben wir Material (%material_last_material%) gefunden bei dem sie maßgeblich mitgewirkt haben.  

Wir freuen uns, dass wir im neuen rpi-virtuell Materialpool (%materialpool_home%) nun auch die Möglichkeit haben, neben Materialien auch  die verbundenen Autorinn/en und Bildungseinrichtungen vorstellen zu können. 

Für Sie wurde heute eine eigene Seite eingerichtet, über die unserer Besucher künftig in Ihren Materialien recherchieren können. Werfen Sie doch einen Blick darauf:
%material_autor_url%
Sind die Angaben korrekt? Möchten Sie ein neues Foto von sich einstellen?
Wenn Sie Änderungswünsche haben, lassen Sie uns dies bitte wissen.

Mit freundlichen Grüßen
%redakteur_name% (%redakteur_reply_email%)
Redaktion rpi-virtuell/Comenius-Institut Münster

**Comment by lehrruetsche** [comment]
Mir wäre es recht, wenn Joachim diese Mail schreibt, da ich festgestellt habe, dass ich keine Ahnung von den technischen Hintergründen habe, die da berücksichtigt werden müssen. Ist die Frage, ob wir das vor dem Kirchentag noch in Angriff nehmen.

**Comment by staude** [comment]
>Ist die Frage, ob wir das vor dem Kirchentag noch in Angriff nehmen.

Alles was mit Mails zu tun hat hängt an dem Konzept Öffentlichkeitsarbeit/PR/SocialMedia das noch weitestgehenst unklar ist.

**Comment by staude** [comment]
Einfache Mail, Klick in DB speichern.

**Comment by staude** [comment]
So sieht das in den Einstellungen aus:

![einstellungen](https://user-images.githubusercontent.com/870951/33240360-2e222c76-d2b5-11e7-9ebf-35e7089d957e.png)

Bei den Autoren:

![2017-11-26_1423](https://user-images.githubusercontent.com/870951/33240379-5d8ccf02-d2b5-11e7-8061-0eff48a67e40.png)

Zu %redakteur_name% (%redakteur_reply_email%) in der Vorlage

Wie stellen wir sicher das jeder Redaktuer da Vorname Nachname als Nicename gewählt hat.
Und ist es nicht Sinnvoller da eine redaktion@rpi oder ähnliches als Email zu verwenden?
Wir möchsten die Mails ja auch sehen und reagieren wenn der Mitarbeitende im Urlaub ist, nicht mehr für uns tätig usw.

Bei https://material.rpi-virtuell.de/material/storm-und-der-verbotene-brief würde in der Mail als Redaktuer und Email auftauchen
helenmarian mit der Email:  lehr-ruetsche@web.de

das ist ja mal ein dreifaches Nogo. Kein "ordentlicher" Name, eine Email die erkennbar nicht zu dem Benutzer genamen gehört und eine Email bei einem Webmail statt rpi-virtuell oder comenius.de


Und dann bräuchte ich noch einen Vorlagentext für die Email an Organisationen mit den dort benötigten Macros.

**Comment by staude** [comment]
Hier der Text eine erzeugten Email:

Guten Tag, Michael Wermke!

Bei unserer Recherche nach geeigneten Inhalten und Medien für die religionspädagogische Arbeit haben wir Material (Lutherisch - was ist das?) gefunden bei dem Sie maßgeblich mitgewirkt haben.

Wir freuen uns, dass wir im neuen rpi-virtuell Materialpool (http://material.dev) nun auch die Möglichkeit haben, neben Materialien auch die verbundenen Autorinn/en und Bildungseinrichtungen vorstellen zu können.

Für Sie wurde heute eine eigene Seite eingerichtet, über die unserer Besucher künftig in Ihren Materialien recherchieren können. Werfen Sie doch einen Blick darauf: http://material.dev/check_autor/56bb65a3f476c4ac21f749a4ccb32f3c

Sind die Angaben korrekt? Möchten Sie ein neues Foto von sich einstellen?
Wenn Sie Änderungswünsche haben, lassen Sie uns dies bitte wissen.

Mit freundlichen Grüßen
lehr-ruetsche (lehr-ruetsche@kabelbw.de)
Redaktion rpi-virtuell/Comenius-Institut Münster

**Comment by staude** [comment]
@lehrruetsche bekomme ich dann von dir noch den Text für die Einrichtungen. Danke.

**Comment by staude** [comment]
Organisations Emailtext (Entwurf von Andrea)

RPI-virtuell ist das Internetportal der Ev. Kirche in Deutschland für Religionspädagogik und Religionsunterricht. In unserem Materialpool wurde Ihre Einrichtung erfasst. Dabei haben wir Ihr Logo verlinkt. Sind Sie mit dieser Darstellung einverstanden oder haben Sie Verbesserungsvorschläge? 
Link
Wenn Sie uns ein geeigneteres Logo zusenden wollen, würden wir uns freuen. Die Größe sollte 200 x 200 Pixel nicht unterschreiten. Sollten Sie dies zur Hand haben, wären wir sehr dankbar, wenn Sie es uns zusenden würden.
Mit freundlichen Grüßen
Andrea Lehr-Rütsche

Redaktion RPI-virtuell
Comenius-Institut Münser
