### ISSUE TITLE
Gruppensuche

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#150]
Wenn ich auf Gruppen gehe und dann meine Gruppe finden will, geht das ja nur über "Suche". Die "Suche" suche ich immer mal wieder. Dann finde ich sie ganz rechts in der Ecke. Könnten wir sie nicht so wie im Materialpool etwas zentraler und größer platzieren?

**Comment by johappel** [comment]
![image](https://cloud.githubusercontent.com/assets/307023/23022711/90a1b688-f452-11e6-8be2-130da02b3e0d.png)
 
Ich find das eigentlich ziemlich groß

**Comment by staude** [comment]
Seit 16.2. nicht passiert, ausserdem kein Materialpool Problem.
Wenn noch Handlungsbedarf besteht, bitte in https://github.com/rpi-virtuell/reliwerk/issues/ ein Ticket erstellen
