### ISSUE TITLE
Medientyp is empty

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#152]
Gerade habe ich einen Eintrag zu einer Unterrichtseinheit gemacht. Als ich zu Organisationen kam, konnte ich einfach in das feld nichts eintragen. Es ging einfach nicht. Feld darüber, Feld darunter - alles gut. Nur Organisationen ging nicht. Da dachte ich, ich speichere alles ab und lade die Seite neu. Als ich sie gespeichert hatte, kam ein großes leeres Feld: Medientyp ist empty (oder so ähnlich) und als ich zurückwollte auf meine bearbeitete Seite, war alles weg. Ich weiß, man soll das nicht mit früher vergleichen, aber früher war das nicht so ;-)

**Comment by johappel** [comment]
Ich habe inzwischen den weg gefunden , das nachzuvollziehen:

ich hbae diese Material eingebgeben und als Medientyp Lernort>Lokale EInrichting  angewählt.
Gespeichert. Ok.

Danach wollte ich es ändern, nach dem Ändern hinzufügen eines Werkes war der Medientyp offenbar nicht mehr gespeichert. dann kamm die Fehlermeldung:


![grafik](https://cloud.githubusercontent.com/assets/307023/23172737/0d99daf0-f857-11e6-921f-054e778243d5.png)

**Comment by johappel** [comment]
Beim nächsten ändern das  Datensatzes trat dann der Fehler nicht mehr auf

**Comment by staude** [comment]
Die Änderung vom WE ist, das ich wie besprochen in Pods den Medientypen zu einem Pflichtfeld geändert habe. 
Das erklärt nur nicht warum er verschwindet. 
Schau ich mir morgen an

**Comment by staude** [comment]
Habe das Required von Medientype erst mal wieder entfernt. 
Entgegen den Textfelder wird in Pods bei den Multiplen Checkboxen das nicht auf der Seite geprüft sondern erst nach Absenden. Zwar kommt man mit dem BackButton des Browsers zurück auf die Seite, aber man kann nicht mehr speichern weil die Nonces nicht mehr gültig ist. Ein Neuladen der Seite verwirft die Inhalte die ja noch nicht gespeichert sind.

**Comment by staude** [comment]
Werfe mal bei Pods.io ein Ticket ein.
