### ISSUE TITLE
Bildquelle bei Materialeintrag im Materialpool

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#153]
Bisher habe ich hauptsächlich mit Logos und vor allem mit Screenshots gearbeitet.
Nun habe ich versucht, ein Bild aus Wikimedia einzugeben. Wenn man es hochlädt vom eigenen PC, kann man nicht wie gewohnt den Urheber des Bildes und die Url des Bildes eingeben. Die Url des Bildes kann man allerdings in der Materialpoolmaske eintragen. Man kann aber nicht den Urheber als Bildquelle eintragen. Es erscheint auch nichts davon im Frontend:
http://material.rpi-virtuell.de/material/berliner-dom-zweitgroesste-gruft-europas/?preview=true

Es geht in diesem Fall um den Beitrag zum Berliner Dom in den Beiträgen des Materialpools.

**Comment by johappel** [comment]
Bildquelle Plugin installieren
