### ISSUE TITLE
Autor

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#154]
Ich habe eben einen Begleittext zum Lerngang Berliner Dom geschrieben.
Unter meinem Begleittext steht etwas unvermittelt die Autorin:
http://material.rpi-virtuell.de/material/die-toten-und-wir-lebenden-besuch-in-der-gruft-des-berliner-doms/?preview=true
Auf mich wirkt das so, als hätte sie den Artikel geschrieben. Irgendwie ist das nicht klar, dass sich die Autorenschaft auf den Artikel bezieht und nicht auf den Begleittext. 

Mir ist aufgefallen, dass das bei anderen Artikeln nicht so ist, zum Beispiel bei einer Erzählung von Frieder Harz. Kann es sein, dass es daran liegt, dass ich sie als Interimsautorin eingetragen habe?

**Comment by johappel** [comment]
Ich verstehe den Artikel so dass die Autorin den Begleittext schreibt und die Führungen auch organisiert.

Du hast deine Frage unter Issues eingetragen.
Welche Hilfe brauchst du konkret? Wir können wir das Issue lösen`?

**Comment by lehrruetsche** [comment]
Den Begleittext habe ich geschrieben. Den vorherigen Begleittext, den ich gelöscht habe, hattest du geschrieben. Auf jeden Fall hat ihn nicht Frau von Franzecky geschrieben. So wirkt es aber. Sie hat den Artikel geschrieben, auf den ich hinweise, aber nicht das kleine Textchen.
Manchmal übernehme ich aus dem Artikel einen kleinen Text, aber bei ihr ging das nicht. Die Zusammenfassung ist von mir. Nur das man eben denkt, so wie es jetzt aussieht, er wäre von ihr.
Das Issue könntet ihr so lösen, dass hier kein Autor auftaucht, sonder nur rechts, wo sie üblicherweise sind. Auch wenn es nur ein Interims-Autor ist.

**Comment by lehrruetsche** [comment]
Also, ich habs jetzt eins zu eins ausprobiert:
bei angelegten Autoren tauchen diese nur rechts auf mit Bild und allem pipapo.
Bei Interims-Autoren tauchen diese direkt unter dem Begleittext auf. Das ist nicht so glücklich, weil es einen falschen Eindruck erweckt. Kann man sie nicht auch nach rechts ziehen?

**Comment by staude** [comment]
@johappel Materialpool_Material.php#704   get_description gibt description und addon (interimsautor und -orga) aus. Reicht es das noch mal in ein span mit klasse zu kapseln damit zu es ausrichten/stylen kannst wie du magst?

**Comment by staude** [comment]
Braucht keine Span, da gibt es schon eine Klasse ohne Klassenbezeichnung. 
Hab mal class="materialpool-material-description-interim" eingebaut.
