### ISSUE TITLE
Bildquelle

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#155]
Habe eben einen neuen Beitrag eingegeben zu "Das Schicksal ist ein mieser Verräter". Das Bild ist aus dem offiziellen Filmtrailer aus YouTube. Habe ich eingetragen, ist aber nirgends zu sehen.
Was ihr für mich tun könnt?
Dafür sorgen, dass die Bildquelle erscheint.

**Comment by staude** [comment]
Eingebaut das die Bildquelle unter dem Bild ausgegeben wird.
Aber: bei dem genannten Material http://material.rpi-virtuell.de/material/das-schicksal-ist-ein-mieser-verraeter-theologische-gespraeche-zu-den-grossen-fragen-mit-jugendlichen-fuehren/
ist unten keine Quelle eingetragen

![2017-04-11_1507](https://cloud.githubusercontent.com/assets/870951/24910707/e91dd0ee-1ec8-11e7-9aa2-198eb747087f.png)
