### ISSUE TITLE
Interims-Organisation

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#156]
Bei dem Beitrag zu den Vorstellungen von Jugendlichen vom Leben nach den Tod habe ich den Autor angelegt, weil der noch mehr verfasst hat, aber nicht die Organisation. Die EH Darmstadt habe ich als Interimsorganisation eingetragen.
Nun passiert das gleiche wie bei den Interims-Autoren. Die Organisation steht genau unter dem Beitragstext. Das wirkt etwas sinnfrei. Müsste auch eher nach rechts.

**Comment by staude** [comment]
ist ein und die selbe funktion die beides ausgibt 
daher technisch doppelt mit #154
