### ISSUE TITLE
Beschreibung erkennt nur youtube-oembed - kein vimeo

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#160]
Beispiel:
http://material.rpi-virtuell.de/material/gesichter-der-flucht-diyar/
vimeo-Link wird nicht erkannt.
youtube-Link wird zu Film-Einbettung

**Comment by staude** [comment]
Das liegt an dem Video, da ist das embedden eingeschränkt. MIt anderen geht das Problemlos z.b. https://vimeo.com/204611433

![2017-02-22_1857](https://cloud.githubusercontent.com/assets/870951/23225079/eba0131c-f930-11e6-9410-33ac97709991.png)
