### ISSUE TITLE
Titel im Materialpool fehlt

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#162]
Trotz mehrmaligen neuen Ladens fehlt immer noch der Titel.
![wasser schenkt leben](https://cloud.githubusercontent.com/assets/15977289/23615396/8eb4d94e-0286-11e7-95ec-dcb8188247c5.png)

Vielleicht liegt es an den Apostrophen?

**Comment by staude** [comment]
alles richtig 
<img width="1590" alt="2017-03-06_1618" src="https://cloud.githubusercontent.com/assets/870951/23616042/b3bfdf34-0288-11e7-8d35-2937cac1a465.png">
