### ISSUE TITLE
Überschneidung von Url und Untertitel

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#163]
![uberschneidung](https://cloud.githubusercontent.com/assets/15977289/23616144/0b7148f8-0289-11e7-8307-7a9ebae2ccd0.png)
Automatisch eingegebener Untertitel und Url überschneiden sich. Im Backend war die automatische Eingabe nicht zu sehen.

**Comment by staude** [comment]
Tritt auf bei fehlgeschlagenen Embedden. Sollte mit #216 erledigt sein
