### ISSUE TITLE
Doppelung

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#164]
![doppelung](https://cloud.githubusercontent.com/assets/15977289/23619059/b0155f8a-0292-11e7-8c51-1a0d593afc4c.png)

Ich weiß einfach nicht, wie diese Doppelung zustande kommt und wie ich sie rauskriegen kann.
Zuerst war sogar auf der Frontside etwas, aber der Bereich mit den Inhalten im Backend war leer.

Das gleiche ist hier passiert:
http://material.rpi-virtuell.de/material/du-siehst-mich-zeitsprung-12017/?preview_id=1554&preview_nonce=6ac5b6136e&preview=true

Im Backend fehlt die Beschreibung, aber im Frontend ist sie da. Wie immer das geht!?!

**Comment by johappel** [comment]
Es ist eigentlich ekien Doppelung:
du hast einmal alle Artikel im Beschreibungstext direkt verlinkt:
![grafik](https://cloud.githubusercontent.com/assets/307023/23623583/d8fd1ce8-02a2-11e7-8579-36af98f7f770.png)

Und anschließend noch einemal in der Hierarchie:
![grafik](https://cloud.githubusercontent.com/assets/307023/23623601/e54cd54c-02a2-11e7-8d22-cfa8e3efec6f.png)
