### ISSUE TITLE
Mailpoet prüfen

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#169]
Mailpoet Einsatz prüfen für automatische Erzeugung von Newslettern pro Autor/Orga

Einsatz prüfen zu automatischen Erzeugung für InfoMails von #168

**Comment by staude** [comment]
MailPoet hat keine API. Es müsste neue Listen, neue Anmeldeformulare und Newsletter direkt in die nicht dokumentierte Datenbank geschrieben werden. 

MalChip hat eine schöne REST API -> prüfen ob es von den Preisen her geht und ob es mit den für uns gültigen Datenschutzbestimmungen vereinbar ist das zu nutzen.

**Comment by staude** [comment]
Möglicherweise ist Newsletter2go als deutscher Anbieter eine Alternative. 
Api: https://docs.newsletter2go.com/#!/List/createList

**Comment by staude** [comment]
Weitere Anbieter mit API

https://rest.cleverreach.com/explorer/v2/

https://aws.amazon.com/de/ses/  fällte ja eher aus weil Amazon

Mache hier weiter wenn die Anforderungen klarer sind.

**Comment by retinasilk** [comment]
"MalChip hat eine schöne REST API -> " meintest du MailChimp?

**Comment by empeiria** [comment]
Der freie Plan bei Mailchimp hat 2000 Abonnenten und 12.000 mails pro Monat über das Mailchimp-System. https://mailchimp.com/pricing/entrepreneur/ Da war die datenschutzrechtliche Klärung noch ausstehend - Komfortabler wäre das natürlich und wir nutzen das bereits für openreli.
Der freie Plan bei Mailpoet hat ebenfalls 2000 Abonnenten, dafür kann aber über das eigene Mailsystem verschickt werden http://www.mailpoet.com/features/features-list/ - Das war datenschutzrechtlich der Grund, weshalb wir diese Variante bevorzugt haben. 
In Kombination mit elasticemail können wir nun pro eigener Mailadresse bis zu 150.000 Mails im Monat verschicken https://elasticemail.com/pricing/ Ist das datenschutzrechtlich unbedenklich?
