### ISSUE TITLE
Interims-Autorin erscheint nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#171]
Habe eben ein Material angelegt mit einer Interims-Autorin. Diese erscheint aber in der Frontansicht nicht.
Es ist immer noch so, dass die Überschrift da ist, wenn ich speichere und weg ist, wenn ich veröffentliche. Irgendwann ist sie dann da. Aber so ganz verstehen tu ichs nicht.

**Comment by staude** [comment]
Tatsächlich werden interims Autoren in der Liste nur zurückgegeben wenn min ein "echter" Autor vorhanden ist
