### ISSUE TITLE
Altersgruppen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#176]
Im mpool hat sich bei den Altersstufen 15 - 10 eingeschlichen. Bringt die Zuordnung durcheiandner. Grundschule wird älter angegeben.

**Comment by staude** [comment]
Altersstufen 15 - 10 gelöscht.

@lehrruetsche "Grundschule wird älter angegeben." Konkretes Beispiel ?

@johappel die Altersstufe kommt von dir so.

Franks-iMac:Materialipool frank$ fgrep 15-10 * | wc -l
    2831

**Comment by staude** [comment]
siehe #182  doppelt, close.
