### ISSUE TITLE
Man kommt nicht zum Material

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#179]
Habe die beiden ersten Materialien genommen im mpool, Das Merkblatt zu Amos und Die Propheten. Ich klicke drauf und komme auf die Detailseite. Klicke ich dort auf "Zum Material" komme ich aber nicht zum Material, sondern verbleibe auf derselben Seite.
Bei den bereits neu eingetragenen Materialien aus dem neuen Materialpool klappt es.
Okay, es kann auch sein, dass Joachim an diesen Seiten rumgemacht hat, denn ich habe jetzt "Lutherbonbon" im alten Materialpool aufgerufen und da wurde mir "Zum Material" gar nicht angeboten, sondern nur "bearbeiten". 
Oder bin ich jetzt völlig falsch unterwegs?

**Comment by staude** [comment]
https://github.com/rpi-virtuell/rw-materialpool/commit/7204132438104e38ba0d358b58197a29c5aa68da

behoben und mit nächsten update weg
