### ISSUE TITLE
Grundschule - Altersstufen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#182]
Obwohl ich bei dem Material von 4teachers zur Kreuzigung Grundschule und Sekundarstufe angegeben habe, kommt bei den Altersstufen die Anzeige 15 - 19 und 19 - 88

**Comment by staude** [comment]
Bitte mal vollständigen Titel oder URL, dann schau ich mal ob das im importierten XML falsch drin steht oder ob was anderes schief geht.

**Comment by staude** [comment]
@johappel 

Fehler im Exportscript


 <category domain="altersstufe" nicename="15-10"><![CDATA[15-10]]></category>
 <category domain="altersstufe" nicename="13-15"><![CDATA[13-15]]></category>
 <category domain="altersstufe" nicename="10-13"><![CDATA[10-13]]></category> 

<wp:postmeta>
    <wp:meta_key><![CDATA[_pods_material_altersstufe]]></wp:meta_key>
    <wp:meta_value><![CDATA[a:2:{i:0;i:40;i:1;i:41;}]]></wp:meta_value>
</wp:postmeta>


Alterstufe 15-10 gibt es nicht, auch nicht 10-15. Muss raus.

Die Altersstufen oben entsprechen nicht den IDs 40 und 41, das sind die Altersstufen 15-19 (ID 40) und 18-99 (ID 41)

**Comment by johappel** [comment]
10-15 ist sekundarstufe 1

**Comment by staude** [comment]
Wird aber als 10-13 + 13-15 eingetragen. Code korrigiert damit es sichtbar ist oben
