### ISSUE TITLE
Veranstaltungen - Layout

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#183]
Irgendwie gefällt mir das mit den **Veranstaltungen** nicht: das sollte klarer getrennt sein, wirkt verrutscht:
http://news.rpi-virtuell.de/

**Comment by staude** [comment]
Das ist kein Materialpool Problem
Bitte in https://github.com/rpi-virtuell/reliwerk/issues/ melden
Danke
