### ISSUE TITLE
Bindestrich verwandelt sich beim Kopieren in ein Fragezeichen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#186]
Ich habe diesen Phrase in den Materialpool einkopiert und aus dem Bindestrich zwischen 15 und 19 wurde ein Fragezeichen gemacht:
Passion I: Die Tempelaktion Jesu (Markus 11, 15–19) | 2.2.2
Im alten Materialpool ist der Bindestrich ein Bindestrich geblieben.

**Comment by staude** [comment]
Hast du das nachträglich bearbeitet @lehrruetsche ? 
bei mir ist es korrekt

![2017-03-24_1228](https://cloud.githubusercontent.com/assets/870951/24292413/84ef84d0-108d-11e7-8fcf-788f033fbbcc.png)

**Comment by lehrruetsche** [comment]
Es wird ja in anderen Zusammenhängen nochmals vorkommen. Wenn es bei dir korrekt lief, warten wir mal ab, ob ich das Problem nochmals habe.
