### ISSUE TITLE
Materialeingabe unnötige Metaboxen Default ausblenden

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#188]
@lehrruetsche wünscht  das Unnötige Metaboxen wie trackback und Diskussion per Default deaktiviert sind damit die Erklärung für neue Mitarbeitende nicht anfängt mit "die obersten Elemente sind unnötig und werden ignoriert".

**Comment by johappel** [comment]
Die kann jeder selbst einmalig deaktivieren. Dafür braucht es keinen programmatischen Eingriff.

**Comment by staude** [comment]
Usermetadaten mit den Einstellungen beim Erzeugen des Benutzers speichern.
