### ISSUE TITLE
Anführungszeichen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#189]
http://material.rpi-virtuell.de/material/christologie-von-oben-und-von-unten/

Die Anführungszeichen am Ende sehen lustig aus.

Die Überschrift kommt bei mir nach wie vor in der Vorschau. Beim ersten Veröffentlichen NICHT. Wenn ich dann aktualisiere, dann erscheint sie wieder.

**Comment by johappel** [comment]
ich fürchte, das liegt an der Schriftart

**Comment by lehrruetsche** [comment]
Ich habs nochmals neu geschrieben, es sieht immer noch genau so aus.

**Comment by lehrruetsche** [comment]
Vielleicht sollten wir eine andere Schriftart für die Überschrift wählen - oder geht das nicht?
Es sieht auch bei der nächsten Überschrift nicht besser aus.
