### ISSUE TITLE
Materialpool - Materialien - Datumseingabe

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#19]
Erstellungsdatum und Wiedervorlagedatum wurde zwar ein Fenster angezeigt, aus dem man das Datum auswählen konnte, aber die angewählten Daten wurden nicht übernommen.
In diesem Fall hatte ich das Datum einer Zeitschrift 1/2016, das ging gar nicht. Was macht man in so einem Fall?

**Comment by staude** [comment]
Januar 2016 ist kein Datum. In dem Datumsdialog muss schon der Tag angeklickt werden, damit das Datum in das Feld übernommen wird. 
Ein mögliche verabredung wäre, das in so einem Fall dann der 1. Januar. 2016 verwendet wird. oder der 15 des Monats.

**Comment by johappel** [comment]
1/2016 ist kein Datum sondern ein Bezeichner für die Ausgabe (kann aj sein dass es nur 2 Ausgaben gibt in 2016)
Braucht es ein zusätzliches Feld "Ausgabe" (gab es früher)?

**Comment by lehrruetsche** [comment]
Ich habe nicht bemerkt, dass wenn ich das Jahr ändere, der angeklickte Tag automatisch verschwindet, und dann fügt sich kein Datum ein. Ja, was die "Breitband-Angaben" angeht, müssen wir eine Verabredung treffen. Solche Angaben kommen oft vor.

**Comment by staude** [comment]
Wenn das konkrete Datum bei einem Großteil der Materialien ein Problem ist, dann muss überlegt werden ob wir das Jahr oder evt noch das Quartal erfassen um das Material über die Facetten auch zeitlich eingrenzbar zu machen

**Comment by staude** [comment]
Feld Jahr hinzufügen und als Facette aufnehmen.
