### ISSUE TITLE
Suchefunktion bei Materialien

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#190]
Ich habe im Backend unter Suche "Fußwaschung" eingegeben. Obwohl ich heute Materialien dazu eingegeben habe, die das Wort im Titel haben und es auch als Schlagwort eingetragen wurde, fand sich NICHTS!!!

**Comment by staude** [comment]
http://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=Fußwaschung liefert 3 Treffer.

war ggf noch nicht indiziert von der Suche. Oder wars du aus versehen auf mpool? Dort gibt es nur Treffer im alten Material.
