### ISSUE TITLE
Auf dieser Seite funktioniert der Screenshot nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#193]
http://material.rpi-virtuell.de/material/wie-ostern-zu-seinem-namen-kam/

Rahmen ist da, aber kein Bild, leider.

**Comment by staude** [comment]
Die Metadaten auf der Quellseite sind defekt
< meta property="og:image" content="http://www.brauchtum.defileadmin/brauchtum/media/img/header-brauchtum.jpg">

hab es korrigiert als cover URL im Material eingetragen. 

mal sehen ob ich eine Adresse finde das ich denen das mitteilen kann
