### ISSUE TITLE
Alter Materialpool - Es werden keine Seiten mehr angezeigt

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#194]
Wenn man zum Beispiel im alten Materialpool "Auferstehung" eingibt, kommt genau eine Seite an Vorschlägen. Man kommt nicht mehr weiter. Also zehn Vorschläge.

**Comment by staude** [comment]
@beo9999 magst du mal schauen? ich habe ja überhaupt keine Zugänge zum alten.

**Comment by staude** [comment]
Was ist hiermit? @beo9999

**Comment by beo9999** [comment]
War wohl ein Problem mit Andrea's Firefox. 
Bei mir ist mit Firefox und Chrome das Problem nicht aufgetreten.

**Comment by staude** [comment]
dann kann das Ticket geschlossen werden? @lehrruetsche

**Comment by staude** [comment]
dann kann das Ticket geschlossen werden? @lehrruetsche @beo9999
