### ISSUE TITLE
Schreibfehler auf der Login-Seite

### ISSUE THREAD

**Issue by beo9999** [rpi-virtuell/rw-materialpool#197]
Im Wort "Nutzungsbedingungen" fehlt ein "e". :) 
![2017-03-27 11_13_05-rpi-virtuell anmelden](https://cloud.githubusercontent.com/assets/12952801/24349292/d7ee6392-12de-11e7-8f45-3bd657bebe80.png)

**Comment by beo9999** [comment]
OK, gehört wohl eigentlich nicht hierhin, eher https://github.com/rpi-virtuell/reliwerk .
Verschieben geht ja wohl nicht.

**Comment by staude** [comment]
wurde gefixt
