### ISSUE TITLE
Vorschau?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#198]
Bei diesem schönen Heft funktioniert die Vorschau nicht:

http://material.rpi-virtuell.de/material/religion-sprache-medien/

**Comment by staude** [comment]
Das Material ist https://www.derlehrerclub.de/download.php?type=documentpdf&id=1439 und aktuell Parsen wir nur die URL ob die auf .pdf oder .odt endet, in dem fall müsste das Material heruntergeladen werden um den Dateityp zu ermitteln.

@lehrruetsche @johappel wie oft kommt das vor? Brauchen wir eine Lösung für den Sonderfall oder kann das ignoriert werden?

**Comment by johappel** [comment]
das liegt an dem abgelaufen Zertifikat vermute ich
https://www.derlehrerclub.de/download.php?type=documentpdf&id=1439

ich denke: das ist nicht unser Problem

**Comment by staude** [comment]
>das liegt an dem abgelaufen Zertifikat vermute ich

Nein, Parsen wir nur die URL ob die auf .pdf oder .odt endet

**Comment by johappel** [comment]
> in  dem fall müsste das Material heruntergeladen werden um den Dateityp zu ermitteln.
Naja die Url paresen reicht, allerdings müsste man so parsen, dass der QQuerystring nicht berücksichtigt wird, also nur die Url bis zum "?"

**Comment by staude** [comment]
dann ist es https://www.derlehrerclub.de/download.php. Hast du auch nichts gewonnen.

**Comment by johappel** [comment]
Dann würde ich sagen: Ausnahmefall (erst mal zurücksetzen)
Workarround: querystring erweitern:
https://www.derlehrerclub.de/download.php?type=documentpdf&id=1439&mime=pdf

**Comment by johappel** [comment]
Allerdings hilft uns das in diesem speziellen Fall auch nicht, weil das zertifikat nicht gültig ist

**Comment by staude** [comment]
ssl veryfiy über all deaktiviert
