### ISSUE TITLE
Bild?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#199]
Zu diesem Special zu Luther-Projekten habe ich ein Bild hochgeladen. Aber es erscheint nicht. Was mache ich falsch?
http://material.rpi-virtuell.de/material/ideensammlung-zu-projekttagen-oder-wochen/

**Comment by staude** [comment]
Ein Special hat keine URL und damit kein Cover. Ggf das Bild in  den Content aufnehmen.
