### ISSUE TITLE
Materialpool-Organisationen-Logo

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#20]
Bei Logo ist ein Feld freigelassen. Was soll man da eingeben? Es gibt kein durchsuchen-Feld für ein Bild.

**Comment by staude** [comment]
Die URL zum Logo, z.b. auf der Webseite der Organisation.

**Comment by johappel** [comment]
Das wurde eingefügt, weill es schneller geht, die Url eines Logos zu ermitteln, als dieses erst herunterzuladen und anschließend wieder in den Materialpool hochzuladen.

**Comment by lehrruetsche** [comment]
alles klar.
