### ISSUE TITLE
Titel-Suche

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#200]
Ich hatte gehofft, man könnte den Titel bei der Suche genau eingeben, vielleicht mit Anführungszeichen dann würde genau der Titel angezeigt. Ist das grundsätzlich nicht machbar? Wenn man einen Titel eingibt, der hauptsächlich die Worte "Reformation" und "Martin Luther" enthält, kann man sichjetzt schon 11 Seiten anschauen. Obwohl man vielleicht den genauen Titel eingegeben hat.

**Comment by staude** [comment]
Mit der aktuellen Suche: Nein

https://searchwp.com/docs/kb/indexer-work-tokenizing

**Comment by staude** [comment]
test mit Elastic durchführen
