### ISSUE TITLE
alles weg

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#201]
Es passiert mir gerade häufiger, dass ich im neuen Materialpool etwas eingebe, auf Screenshot gehe, dann auf speichern - und dann kommt irgendeine Meldung, dass irgendetwas invalid ist und alles ist weg, oder  in Teilen ist es weg. Ich verstehe nicht ganz, warum sich das jetzt so häuft. Naja, da werdet ihr mir vermutlich auch nicht helfen können, aber es ist ziemlich ärgerlich.

**Comment by staude** [comment]
bitte mal ein video davon machen

**Comment by lehrruetsche** [comment]
ich wollte es gerade löschen, aber das gelang mir nicht. Ich glaube, das Material ist schon drin.

**Comment by lehrruetsche** [comment]
Das steht groß und rot Cancel und wenn ich auf Cancel gehe, passiert nichts - was kann man da eigentlich falsch machen? Aber irgendwas mach ich falsch.

**Comment by staude** [comment]
Ich habe keine Ahnung was für ein Cancel du meinst - weil ich an keiner Stelle eins eingebaut habe in meinem Code. Darum: bitte mit Screenshot oder noch besser Video sowas dokumentieren oder per Bildschirmfreigabe mal zeigen, sonst kann ich nur raten

**Comment by staude** [comment]
Das Problem ist folgendes: 
Die BPB Webseite hat in den og:image nur einen relativen Pfad

< meta property="og:image" content="/cache/images/3/235063-dg-original.jpg?078D2" />

Beim eingeben der URL laden wir ja die Seite und übernehmen die Beschreibung, wenn vorhanden und unter anderem auch den og:image als Cover URL.

CoverURL ist in Pods aber als Feld vom Typ Webseite definiert. Nur eine Pfadangabe ist keine vollständige URL und darum weigert sich Pods das zu speichern.

wir müssen also abprüfen ob das eine vollständige URL ist, und sonst ggf nicht in das Feld eintragen. 

Betrifft check_url beim eintragen und den Screenshot Mechanismus.
