### ISSUE TITLE
Interimsorganisation

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#202]
mpool:
Es war jetzt bei zwei Materialien hintereinander so, dass ich eine Interimsorganisation hatte. Die hatte sich tatsächlich automatisch eingetragen: aber sowohl die Organisation als auch die www-Adresse, was dann jeweils zu Doppelungen führte.

**Comment by staude** [comment]
das haben wir so importiert, die Idee ist eigentlich das das die Zuordnung erleichtert. @johappel Aber du hast recht, die Interimsdaten geben wir da in der Detailansicht so aus. Wäre also eine Verabredung das die angepasst werden müssen oder wir sie doch nicht importieren.

**Comment by lehrruetsche** [comment]
Eben habe ich Material von Planet Schule Konvertiert. Da steht jetzt bei Interimsorganisation:
Planet Schule www.planets-schule.de
Planet Schule ist aber eine bereits bei uns angelegte Organisation.
