### ISSUE TITLE
Verfügbarkeit

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#206]
Im Frontend erscheint immer "Verfügbarkeit", obwohl hier selten etwas erscheint. Ist das aus technischen Gründen für die Suche nach OER-Material wichtig?

**Comment by staude** [comment]
Ggf im Template abfragen

**Comment by staude** [comment]
kostenfrei, frei zugänglich ist jetzt per default ausgewählt.

Wird im Template nun abgefragt, ob es einen wert gibt
