### ISSUE TITLE
Organisationen -.Materialien von

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#209]
Auf der Seite der Organisation steht oben "Materialien von" es müsste aber auch manchmal heißen "Materialien vom" (z.B. Bayerischen Rundfunk, PTZ Stuttgart usw.) Lässt sich dies irgendwie anders formulieren? Oder muss es überhaupt da stehen?

**Comment by staude** [comment]
Nehme "Materialen von " raus.
Ansonsten neues Ticket machen mit Textvorschlag.
