### ISSUE TITLE
Materialpool - Altersstufe

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#21]
Bei der Materialeingabe gibt man bereits die Altersstufe an. Für Altersstufe gibt es aber ein eigenes Eingabefeld. Es ist schön, dass die Altersstufen extra beschrieben werden, aber wozu das Eingabefeld da ist, verstehe ich nicht wirklich.

**Comment by staude** [comment]
Ih versteh die Frage nicht so richtig. Die Altersstufen haben wir für im/export  mit quellen wo das zwingend ist. Mit ankreuzen der Bildungsstufen werden die passenden Altersstufen gleich mitselektiert.

**Comment by johappel** [comment]
Das Feld Altersstufen ist der Kompatibilität mit anderen Datenabnken wichtig, da es dort unsere Bildunsgstufen so nicht geben wird.
Das Feld Altersstufen wird bei der Auswahl der Bildungsstufen zwar vorselektiert, könnte aber bei bedarf auch händisch feinjustiert werden.
