### ISSUE TITLE
Viewer leer

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#210]
http://material.rpi-virtuell.de/material/das-reformations-jubilaeum-leicht-erklaert/

http://material.rpi-virtuell.de/material/religion-sprache-medien/

(letzteres ist sehr aufwändig, vielleicht brauchts einfach lange. Der erste Screenshot sind nur zwei Seiten)

**Comment by staude** [comment]
Das ist schon schräg. Wenn ich unsere Wrapper URL direkt aufrufe
http://material.rpi-virtuell.de/?vsviewer_url=https%3A%2F%2Fwww.bundestag.de%2Fblob%2F487266%2F0935684630002825ece5945a7a5691cd%2Fbeilage_reformationsjahr_09_01_17-data.pdf
bekomme ich das PDF,  aber mir dem Viewer geht es nicht.
