### ISSUE TITLE
Seltsamer Screenshot

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#211]
http://material.rpi-virtuell.de/material/reformation-und-glaubensspaltung/

Kommt etwas seltsam rüber, lässt sich vermutlich nicht ändern...

**Comment by staude** [comment]
Du meinst das Organisations Logo? das ist ja nicht das Logo alleine sondern der ganze Banner Blog da oben. Kannst du Orga ja mal anschreiben ob sie irgendwo das Logo alleine liegen haben.

**Comment by staude** [comment]
ping @lehrruetsche

**Comment by staude** [comment]
Material URL nicht mehr vorhanden
