### ISSUE TITLE
doppeltes Speichern im Materialpool mag das System nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#212]
Kann sein, dass wir das schon hatten:

Eben habe ich ein neues Material erstellt, gespeichert und betrachtet. Dann habe ich einen Fehler im Téxt entdeckt, verbessert und nochmals gespeichert. Und dann wurde mir gesagt: diese Url hat er schon, ein schönes weißes Feld. 
Als ich auf Materialien bin, war der Entwurf da. Trotzdem ist schwer verständlich, warum man nach einer Verbesserung nicht abspeichern kann. Wenn ich vielleicht gleich auf Veröffentlichen gegangen wäre, wäre nichts passiert, aber vielleicht hätte es ja noch einen Fehler gegeben?

**Comment by staude** [comment]
kann ich nicht nachvollziehen.
https://screencast.com/t/7MSUh3PzY
Bitte mal zeigen

**Comment by lehrruetsche** [comment]
Mein Problem ist, dass das Feld "dies Url hat er schon" immer mal wieder auftaucht und ich denke: was um Himmels Willen habe ich jetzt wieder angeklickt. Ich versuchte das gedanklich zu rekonstruieren, aber oft weiß ich nicht, an was genau es lag. Das mit dem Verbessern ist seither nicht mehr vorgekommen, ich verbessere oft was und alles klappt.
