### ISSUE TITLE
Materialeintrag Screenshot wird nicht übertragen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#213]
Webcompetentbeitrag April 2017: Screenshot sieht in der Vorschau und veröffentlicht so aus:
http://material.rpi-virtuell.de/material/hier-ist-entwuerdigung-programm/

Geht man aber auf die STartseite, ist alles perfekt:
http://material.rpi-virtuell.de/facettierte-suche/

Irgendwas stimmt mit dem Screenshot zurzeit nicht so richtig.

**Comment by staude** [comment]
Das ist ein Bug in WordPress. Wenn man in einem neuen Beitrag im visuellen Editor die URL http://webcompetent.org/?p=6343 eingibt und Return drückt wird nicht den Beitrag von Webcompetent embedded sondern der Materialpool Eintrag mit der ID 6343 -> Gesprächsführung im Unterricht – Die Lehrerfrage wird eingebettet.

**Comment by staude** [comment]
Hab ein Core Bug Ticket eingereicht
https://core.trac.wordpress.org/ticket/40372

**Comment by staude** [comment]
Kann ich momentan nicht fixen. 
Workaround wäre, im Theme nicht auf Embed abzufragen und die "special" Ansicht wirklich nur bei Viewer und spezial zu verwenden, aber nicht bei embedbaren Inhalten.
@johappel

**Comment by staude** [comment]
Hab ein Workaround gebaut.
