### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#214]
Es wäre schön, wenn die Suchfunktion bei der Organisation sowohl der kurzen Titel als auch den langen Titel durchsuchen könnte. Aber ich glaube, das hatten wir schon mal...

**Comment by staude** [comment]
Im Backend in der Liste unter http://material.rpi-virtuell.de/wp-admin/edit.php?post_type=organisation können wir machen. Im Zuordnungsdialog wird das schwer, wenn überhaupt möglich. 
wahlweise könnte man das umstellen das in den "langen" Namen gesucht wird, statt den "kurzen", beides wird vermutlich nicht mit vertretbaren Aufwand gehen.

**Comment by staude** [comment]
Pods ansehen ob das "einfach" via Hook zu lösen ist, das beide Felder durchsucht werden.

**Comment by staude** [comment]
Ist nicht mit vertretbaren Aufwand realisierbar
