### ISSUE TITLE
Kein Screenshot

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#215]
Bei diesem Artikel wurde kein  Screenshot erstellt:

http://material.rpi-virtuell.de/material/facebook-in-der-bildung/

**Comment by staude** [comment]
https://s.wordpress.com/mshots/v1/https%3A%2F%2Fwww.bpb.de%2Flernen%2Fdigitale-bildung%2Fwerkstatt%2F240296%2Ffacebook-in-der-bildung?w=400&h=300  also die Screenshot url liefert das 404 icon, das heisst, das Wordpress.com , wenn es versucht auf die Seite zugreifen einen 404 Fehler bekommt. 

Da kann man nix machen, ausser mal bei der bpb anzufragen was der Grund ist.
