### ISSUE TITLE
Materialpool - Lizenzen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#22]
Das normale Copyrights sollte auch dazu. Und vielleicht die üblichen Abkürzungen BY-SA-NC dahinter? Ich glaube, BY fehlt ganz.

**Comment by johappel** [comment]
Das hatten wir beschlossen weg zulassen, da sonst jeweils die exakte Lizenz CC2, CC3, CC4  DE oder EN... ermittelt werden muss, was sehr viel Aufwand bedeuten kann.
Es wird lediglich nach cc ... (sa|nc) unterschieden
