### ISSUE TITLE
Verlinkung im alten Materialpool

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#223]
Die Materialien des alten Materialpools haben in WordPress keinen Link zum Orgininalmaterial. Das heißt, ich muss es auf jeden Fall erst konvertieren, damit ich anschauen kann, um was es geht. Irgendwo müsste dieser Link doch sein, oder?

**Comment by staude** [comment]
Nein, es gibt das Template noch nicht im Theme.

**Comment by staude** [comment]
behoben
