### ISSUE TITLE
Doppelungen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#224]
Doppelungen werden angezeigt mit einem Feld, dass das Material schon das sei mit dem Hinweis, wo es zu finden ist. Aber dann landet man auf einer Art "Error-Seite", also auf einer Seite, auf der man das Material nicht findet.

**Comment by staude** [comment]
Was ist eine "Art Error Seite"? Screenshot?

**Comment by lehrruetsche** [comment]
Hier der Screenshot
![auf dieser seite konnte nichts gefunden werden](https://cloud.githubusercontent.com/assets/15977289/25191282/6e0e97d6-252f-11e7-9fce-95be6fa7397f.png)

**Comment by lehrruetsche** [comment]
Und das kommt kurz vorher:
![link wurde schon verwendet](https://cloud.githubusercontent.com/assets/15977289/25191373/a40e3936-252f-11e7-8420-f10f48c35687.png)

**Comment by staude** [comment]
wie an dem _trashed in der URL beim ersten Screenshot zu sehen ist, ist das Material in dem die URL schon verwendet wurde im Papierkorb.  
Regelmäßig den Papierkorb leeren
