### ISSUE TITLE
Nichtbearbeitetes wird sofort übernommen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#226]
Wenn man Materialien konvertiert, dann aber nicht bearbeitet sondern wieder zurückgeht zum Materialpool, wird er automatisch in die neuen Materialien übernommen. Wahrscheinlich lässt sich daran n ichts ändern, ist aber nicht so ganz günstig.

**Comment by staude** [comment]
Ja, das ist das Verhalten wie es seit der Implementierung dieser Funktion drin, wie es gezeigt wurde und wie es schon verwendet wurde.

Was ist jetzt der Änderungswunsch?

**Comment by lehrruetsche** [comment]
Wenn ich das Material im Moment nicht so wichtig finde, aber auch noch nicht löschen will, habe ich keine Möglichkeit, es einfach im alten Materialpool zu belassen. Es ist bereits konvertiert: es gibt nur Hopp oder Top. Zum Beispiel hatte ich Compassion, da kam das Wort Passion drin vor, hat aber mit der Passion gar nichts zu tun, sondern mit einem Sozialprojekt, in dem es um Lernen von Mitgefühl geht. Ich wollte es eigentlich nicht bearbeiten, aber ich musste es. Oder ein Material zu Schulgottesdiensten des RPI Loccum, es war offensichtlich schon älter, aber auf die Schnelle konnte ich das Alter nicht finden und eigentlich wollte ich es jetzt auch gar nicht bearbeiten, aber wie gesagt: hopp oder top.

**Comment by staude** [comment]
>Wenn ich das Material im Moment nicht so wichtig finde, aber auch noch nicht löschen will, habe ich keine Möglichkeit, es einfach im alten Materialpool zu belassen.

Es nicht konvertieren

> Es ist bereits konvertiert: 

Das ist nicht korrekt, das alte Material ist als Beitrag importiert und nicht als Material. 
Das alten Material ist im Frontend unter http://material.rpi-virtuell.de/archiv/ erreichbar und die Suche im Material gibt die einen Link, wenn es zu dem Suchbegriff auch Treffer im alten Material gibt.
Im Backend ist das alte Material im Bereich Beiträge zu finden http://material.rpi-virtuell.de/wp-admin/edit.php

Wenn du dann auf Konvertieren klickst wird der Beitrag gelöscht und ein Material erzeugt und veröffentlicht.

>es gibt nur Hopp oder Top.

Das ist nicht korrekt, auch bei Material kann man den Status ändern. in den beschriebenen Fall könntest du den Status wieder auf Entwurf setzten.

![2017-04-19_1012](https://cloud.githubusercontent.com/assets/870951/25169819/bb5bb650-24e8-11e7-94e7-46e5b7e96e01.png)

Es muss nur klar sein das in die Listen Entwurf genau wie in Vorschlag auch mal reingeschaut werden muss. 

![2017-04-19_1014](https://cloud.githubusercontent.com/assets/870951/25169936/0ce4ef46-24e9-11e7-89ad-d6b239bda060.png)

Die Vorschläge wurden ja seit Monaten nicht angefasst.

![2017-04-19_1015](https://cloud.githubusercontent.com/assets/870951/25169968/2db38282-24e9-11e7-97b1-f6628639e988.png)

Und genau darum hab ich eingebaut das die Konvertierten veröffentlich sind.
Sonst wird es dazu führen das ein ganzer Rutsch zu einem Thema konvertiert wird (und damit im Archiv des alten Materials verschwunden) und hoffentlich irgendwann dann bearbeitet wird (und dann nicht vergessen wird es zu veröffentlichen).

Das wurde von mir min zwei mal genau so Demonstriert und kommuniziert.
Aber gut, die Probleme sind benannt und nun können wir in der Runde noch mal den Workflow diskutieren.
