### ISSUE TITLE
Autoren von Interims zum "festen Autor"

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#229]
Ich habe das Problem, dass ich die Autoren manchmal falsch einschätze und erst mal bei Interimsautor eintrage. Dann kommt er noch zweimal und ich mache ihn zum "richtigen" Autoren. Leider ändert sich der Status dann bei den "alten Einträgen" nicht. Er wird dort nicht automatisch zum "richtigen Autor". Wenn man den Autor aufruft, wird nur der Beitrag aufgeführt, den man nach seiner Autorenerstellung eingetragen hat, die vorherigen nicht. Lässt sich das technisch irgendwie lösen? Aktuell ist Sascha Flüchter so ein Fall.

**Comment by staude** [comment]
Keine Automatisierung. 
Aber genau darum werden die Interims Felder in der backend suche mit durchsucht, damit du ihn darüber suche kannst
