### ISSUE TITLE
Organisationen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#231]
Manchmal erscheinen nicht einzelne Organisationen, sondern alle:
![organisationen alle auf einmals](https://cloud.githubusercontent.com/assets/15977289/25316298/dc884d3c-2864-11e7-9e4f-7124d51f488b.png)

Das Blöde ist, dass das nicht immer ist, sondern manchmal - und dann kann ich sie auch nicht umgehend abrufen wie sonst.

**Comment by lehrruetsche** [comment]
Kann es sein, das es passiert, wenn ich nur in das zweite Titelfeld etwas eintrage?

**Comment by staude** [comment]
ja, dann hat die Orga keinen Namen und damit ist der post-name leer, darum die url /organisationen was wiederum die Archiv Seite aufruft die alle Organisationen auflistet

**Comment by lehrruetsche** [comment]
okay
