### ISSUE TITLE
Titel fehlt nach wie vor.

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#232]
Ich arbeite ja nun seit einiger Zeit mit dem Konvertieren. Und ich habe nach wie vor das Problem, dass ich NIEMALS den Titel sofort aufs erste, zweite oder dritte Mal lesen kann. Er ist einfach nicht da, nicht mal wenn ich extra den Cache leere. Irgendwann, wenn ich später draufgehe, ist er dann da.

**Comment by staude** [comment]
Wie schon öfters geschrieben zu dem Thema. Ich kann es nicht nachvollziehen, mach ein Video oder  noch besser, zeig es mir Online - damit ich mal sehe was du da machst bzw es evtl auch mal nachvollziehen kann.
