### ISSUE TITLE
Viewer Kindernothilfe

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#234]
Bei der Kindernothilfe funktioniert der Viewer nicht:

http://material.rpi-virtuell.de/material/kinder-auf-der-flucht-2/

**Comment by staude** [comment]
Ja, gibt es immer mal wieder das es Dokumente gibt die wir aktuell da nicht angezeigt bekommen.
Dafür gibt es den Haken den Viewer zu deaktivieren
<img width="660" alt="2017-04-25_0829" src="https://cloud.githubusercontent.com/assets/870951/25371782/ae819fe0-2992-11e7-82b1-11e394a8336f.png">

Hab ich bei dem Material schon gesetzt
