### ISSUE TITLE
Material erscheint mehrfach auf der Startseite des Materialpools.

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#235]
Bin eben auf den neuen Materialpool gegangen, sozusagen auf unsere "Startseite" des Materialpools. Dort waren die neuen Materialien zum Beispiel von der Kindernothilfe doppelt eingetragen, auch der Tag der Straßenkinder taucht zweimal auf!

**Comment by staude** [comment]
@johappel wie auch schon im Chat am 22.4. im #materialpool channel geschrieben zum Thema "Mord als Gottesdienst" so sind auch die neuen "Tag der Strassenkinder", "Kinder auf der Flucht" und "KirchenApp" jeweils doppelt eingetragen. 

<img width="2165" alt="2017-04-25_0820" src="https://cloud.githubusercontent.com/assets/870951/25371273/2c3f2518-2990-11e7-9d37-ce97ede1a206.png">

was mich wundert ist das der jeweils nicht vollständig ausgefüllte Eintrag der mit der neueren ID ist. als wenn das irgendwie zweimal gespeichert wird. Allerdings gelingt es mir nicht dieses Verhalten zu reproduzieren. Können wir das mal so machen das ich da per Bildschirmfreigabe zuschaue wie du die bearbeitest?

**Comment by staude** [comment]
Ich lösche die jetzigen doppelten mal
