### ISSUE TITLE
Abstand viewer,Quelle , Titel

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#239]
(Andrea) Aber wenn im Frontend ein Viewer erscheint und darunter der Link, klebt gleich daran der Titel. Dann größerer Absatz und danach der Text. Den größeren Absatz wünschte ich mir zwischen dem Link unter dem Viewer und dem Titel.

http://material.rpi-virtuell.de/material/verantwortung-fuer-mich-dich-und-die-welt/

**Comment by lehrruetsche** [comment]
Das Problem taucht nur auf, wenn man ein PDF hochlädt, weil dann das Layout anders ist, als bei direkten Links. Durch den Viewer verschiebt sich das ganze, es ist immer noch so, dass der Link kommt, dann gleich der Titel, dann ein Abstand und dann der Text.
