### ISSUE TITLE
Falsche Verknüpfung eines Materials

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#240]
Es gibt diesen Eintrag, alles funktioniert wunderbar: 
http://material.rpi-virtuell.de/material/schulgottesdienste-7/

Und es gibt diesen Eintrag (ganz nach unten scrollen) und dieses verknüpft sich immer mit einer ganz anderen Seite. Zuerst war es "Schulgottesdienst" von Bibelwissenschaft.de Den Eintrag habe ich dann gelöscht, jetzt verknüpft es sich mit einem Special:
http://material.rpi-virtuell.de/facettierte-suche/?thema=13838&gruppe=43&fwp_suche=multireligi%C3%B6s

Ich mache bestimmt schon eine halbe Stunde rum, weil ich diesen Link oft verknüpft habe - aber ich finde des Rätsels Lösung nicht.

**Comment by staude** [comment]
????

Welches Material (URL?) verknüpft sich immer mit was anderem?

**Comment by lehrruetsche** [comment]
Das letzte Material auf der Seite: Schulgottesdienste Erding - da geht mein Schulgottesdienstspecial auf. Das sieht mir wirklich nach einem Bug aus.
