### ISSUE TITLE
Autor erscheint nicht bei pdf-Eintrag

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#241]
Ich habe eben zwei Artikel von Prof. Dr. Markl eingetragen, die er mir zugeschickt hat. Ich habe ihn als Autor angelegt, aber er erscheint nicht im Artikel.

http://material.rpi-virtuell.de/material/exodus/
http://material.rpi-virtuell.de/material/exil/

Der Autor wurde von mir mit Bild angelegt.

**Comment by staude** [comment]
Weil es zwei Dominik Markl hab. einen leeren der nur den slug hatte und dem die Materialien zuordnet waren und einen  mit dem slug Dominik-markl-2 der Namen und Bild hatte, aber keine Materialien.
hab ich berichtigt
