### ISSUE TITLE
Bildeingabe mit Url bei den News

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#243]
Bei der Bildeingabe bei den News rechts unten steht als Angebot "Enter the Url for external Image". Was bedeutet dieses Feld? Wenn ich eine Url eines Bildes eingebe, passiert nichts.

**Comment by staude** [comment]
Kein Materialpool Bezug, bitte hier https://github.com/rpi-virtuell/reliwerk/issues eintragen

**Comment by staude** [comment]
Das verwendet eine externe URL als Beitragsbild. wenn ich mich recht erinnere hatten wir da aber schon mal ein Problem mit. @empeiria

**Comment by lehrruetsche** [comment]
Ja, sehr schade, dass das nicht funktioniert. Wäre toll, wenn das ginge.
