### ISSUE TITLE
News: Medien angehakt, erscheint aber nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#244]
Bei dem Material "Simple show" habe ich News und Medien angehakt, es taucht aber nur bei den News auf. Habe auch einen zweiten Browser getestet, mit demselben Ergebnis.

**Comment by staude** [comment]
Welches Material, finde kein passendes? Was meinst du mit taucht nur bei News auf?
URLs?

**Comment by lehrruetsche** [comment]
http://news.rpi-virtuell.de/2017/04/29/simple-show-zur-religioesen-entwicklung-bei-u3/
