### ISSUE TITLE
Gruppe: Informationen zu den Gruppen auf englisch

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#245]
Habe eben eine neue Gruppe angelegt, die Infos waren alle auf englisch.
http://gruppen.rpi-virtuell.de/groups/create/step/group-settings/

Oh, oh, ich weiß nicht, was ihr da geändert habt, aber irgendwie ist alles anders. Also, ich habe alles gemacht, was mir gesagt wurde nach dem Anklicken von "Create a group" und als ich dann auf "Next Step" geklickt habe, kam ich wieder auf diesselbe Seite! Ich kam also nicht weiter. Konnte nichts anlegen.
http://gruppen.rpi-virtuell.de/groups/create/step/group-settings/

**Comment by staude** [comment]
Kein Materialpool Problem -> https://github.com/rpi-virtuell/reliwerk/issues
