### ISSUE TITLE
Gruppenanmeldung

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#246]
Heute Morgen habe ich versucht, eine Gruppe Siebtklässler für eine Gruppenarbeit bei rpi-virtuell anzumelden. Die Gruppe hatte ich schon eingerichtet. Es tauchten folgende Probleme auf: Natürlich gaben die Schüler und Schülerinnen bei Benutzernamen Großbuchstaben ein und Satzzeichen. Das ist heute eigentlich normal und wird sogar erwartet. Aber hier darf man es nicht! Es steht aber auch nirgends. Dann dachte ich auch, der Benutzername sei der, der nachher auftaucht. Aber das ist der andere Name, der später erfragt wird. Dann kam das Capcha. Das bei den Schülerinnen und Schülern oft lange dauerte. Und DANACH wurde ihnen mitgeteilt, dass sie Großbuchstaben verwendet hätten. Daraufhin das Ganze von vorne bis hin zum dreimaligen Capcha. Manche brauchten eine halbe Stunde, um sich anzumelden. Es wäre gut, wenn man hinschreiben würde, dass nur Kleinbuchstaben und Zahlen verwendet werden dürfen. Und das Capcha, ich habe noch nie so ein umständliches erlebt.

**Comment by staude** [comment]
Kein Materialpool Problem -> https://github.com/rpi-virtuell/reliwerk/issues
