### ISSUE TITLE
Gruppe verlassen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#247]
Nach wie vor steht rechts neben der Gruppe immer noch riesig "Gruppe verlassen". Das war doch schon mal geändert, oder? Wir haben mehrfahr darüber gesprochen, dass das so ankommt: ich gehe jetzt mal raus und nicht, ich melde mich komplett ab. Es wird zwar jetzt nochmals nachgefragt, aber ich halte das trotzdem nicht für gut.

**Comment by staude** [comment]
Kein Materialpool Problem -> https://github.com/rpi-virtuell/reliwerk/issues

**Comment by staude** [comment]
ping @lehrruetsche test
