### ISSUE TITLE
Viewer klappt bei diesem Material nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#248]
http://material.rpi-virtuell.de/material/himmelfahrt-auffahrt/

**Comment by staude** [comment]
Ja, wird immer wieder mal vorkommen - aktuell haben wir da noch keine Lösung. 
Dafür kannst du beim Material ja den Viewer deaktivieren

<img width="1430" alt="2017-05-03_1441" src="https://cloud.githubusercontent.com/assets/870951/25660919/a4db9784-300e-11e7-8141-46bd16c67ac7.png">
