### ISSUE TITLE
Trenner?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#251]
Mir kommt es so vor, als ob es völlig egal ist, ob ich den "Trenner" einsetze oder nicht. Auf der Startseite bei dem Text zu Himmelfahrt, bewirkt er einfach gar nichts. Der Fließtext geht automatisch über ein einen gegliederten Text, obwohl da ein Trenner dazwischen ist. Kommt nicht gut rüber.

http://news.rpi-virtuell.de/

**Comment by staude** [comment]
Kein Materialpool Problem :-) Bitte in https://github.com/rpi-virtuell/reliwerk/issues/ erstellen danke
