### ISSUE TITLE
Änderungen in der Schulart - Änderungen im Alter

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#253]
Wenn man bei den Schulstufen ein Häkchen setzt, werden automatisch die enstprechenden Altersangaben angehakt.
Nimmt man aber ein Häkchen wieder raus (zum Beispiel Grundschule), bleiben die Altersangaben bestehen (also das Häkchen sitzt immer noch bei 5 - 10).
Das ist nicht weiter tragisch, solange ich das mache, aber wenn sich irgendwann eine Lösung finden ließe, wäre das nicht schlecht.

**Comment by staude** [comment]
Evt hilft es ja auch schon wenn wir die Altersstufen Auswahl direkt unter die Bildungsstufe setzen?

**Comment by staude** [comment]
In Absprache mit @lehrruetsche wir die Altersstufe direkt unter die Bildungsstufen im Dialog gesetzt.
