### ISSUE TITLE
Special zerschossen?

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#254]
Ich habe neu http://material.rpi-virtuell.de/material/die-frauen-am-grab/ angelegt.
Allerdings gibt es hier gegenüber anderen Specials keine Sidebar-Widgets mehr sondern Autor und Institution untereinander:
![image](https://cloud.githubusercontent.com/assets/1091954/25900370/9c157e14-3593-11e7-8837-5765e55fd6c1.png)

**Comment by staude** [comment]
Auf die schnelle hab ich keine Idee.
an den MP3 liegt es nicht, hatte welche zu nem Test bei nem anderen Special eingefügt, da war dennoch alles gut.
Akkordions hatte das andere auch.

**Comment by staude** [comment]
ich vermute mal, das das von dir eingefügte html nicht sauber ist und darum irgendwelche divs noch nicht geschlossen sind. @empeiria

**Comment by empeiria** [comment]
na gut - ich werde die divs checken...

**Comment by staude** [comment]
hast du ja hinbekommen
