### ISSUE TITLE
Fehler 404 bei Screenshot

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#255]
Bei der Bundeszentrale für politische Bildung taucht im Bild des Screenshots "404" auf, das ist bisher auch noch nicht vorgekommen:
http://material.rpi-virtuell.de/material/flucht-und-asyl-4/
http://material.rpi-virtuell.de/material/themenseite-flucht/

**Comment by staude** [comment]
Siehe #257 
Kann ich nicht fixen. Bei der Bundeszentrale muss du die Url des Bildes raussuchen und als Cover eintragen oder es gibt halt kein Screenshot.
