### ISSUE TITLE
Probleme mit Youtube-Film einfügen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#256]
Ich habe einen Beitrag, der sich auf einen youtube film bezieht.
Ich wollte den Film einfügen, habe ganz einfach die Url kopiert wie immer, eingefügt wie immer und raus kommt das:
![jeder konnte ein fluchting sein](https://cloud.githubusercontent.com/assets/15977289/25941442/c655bfda-3639-11e7-9c92-f1042585cc5e.png)
Nach dem ich die Prozedur viermal wiederholt habe, rufe ich jetzt um Hilfe. Was mache ich falsch?
Ich habe es jetzt noch mit einem ganz anderen Video probiert und es passiert genau dasselbe.

**Comment by empeiria** [comment]
Die URL wurde ja schon oben eingetragen. Ich stimme @lehrruetsche zu: Man sollte das Video direkt abspielen können und nicht nur das Vorschaubild gezeigt bekommen oder es nochmal in der Beschreibung eintragen müssen.
![image](https://cloud.githubusercontent.com/assets/1091954/25942891/532369e0-363e-11e7-81cf-16e47d26619a.png)

**Comment by staude** [comment]
Du machst nichts falsch. 

dieses Video kann ich in meiner Installation problemlos embedden.
Im original Datenbestand hingegen nicht.

Kann nicht versprechen das ich das aktuell fixen kann, es gibt da mehrere Bugs im Embed Handlng in WP
