### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#257]
REMID material.rpi-virtuell.de/material/kirchenasylbewegung-deutschland-jeder-einzelfall-zaehlt/

Planet Wissen funktioniert nicht (ich glaube, das war schon früher ein Problem)
http://material.rpi-virtuell.de/material/planet-wissen-fluechtlinge/

bpb auch nicht, habe ich aber glaube schon geschrieben.

E-wie-Evangelisch gibt kein Screenshot her, man kann das Video aber auch nicht direkt einbinden.

![e-wie-evangelisch](https://cloud.githubusercontent.com/assets/15977289/26054601/7a35f5f2-396d-11e7-8028-db17e9d5be5f.png)

Leider funktioniert der Screenshot bei der Bayerischen Kirche auch nicht:

http://material.rpi-virtuell.de/material/eine-bewegung-nimmt-ihren-anfang/

**Comment by johappel** [comment]
ich habe mal den Link benutzt der auf der Seite unter teilen vorgeschlagen wird. Damit geht es:
http://material.rpi-virtuell.de/material/planet-wissen-fluechtlinge/

Allerdings sieht die Anzeige im Editmod so aus, als würde der Sreenshot nicht funktionieren:
![grafik](https://cloud.githubusercontent.com/assets/307023/26056102/26af27e4-3974-11e7-9025-fd25c0cb6672.png)

**Comment by staude** [comment]
Screenshot Erzeugung geändert.
- Planet Wissen geht nun
- Bayerischen Kirche geht nun
- E-wie-Evangelisch  geht nun

**Comment by staude** [comment]
http://www.bpb.de/shop/lernen/falter/236190/zuflucht-deutschland hat im html eine leere og:image und der screenshotservice von WordPress.com liefert eine 404 Seite zurück, weil der offenbar bei denen geblockt wird. Da kann ich nix machen - da musst du leider eine Grafik von der Seite raussuchen und als Cover eintragen oder es gibt keinen.

**Comment by staude** [comment]
Schliesse das Ticket, da alle vorhanden Fälle geklärt sind. Ggf wieder eröffnen oder ein neues machen, danke.
