### ISSUE TITLE
Titel, Cover, Video und zusammenklappen.

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#26]
Kein Titel: http://material.rpi-virtuell.de/material/mein-gott-ich-lobe-dich/?preview_id=241&preview_nonce=4f83f612d5&preview=true (War auch zuerst bei dem Gewalt-Titel so, jetzt geht er)

Das Video erscheint nicht als Video, nur als Url. Ist das so gedacht?

Leere Angabenfelder erscheinen auch weiterhin, obwohl ich den Pfeil zugeklappt habe.

Und in die vielen Cover-Urls müsst ihr mich noch einführen. Wie dem auch sei: sieht nicht gut aus. Kurt Mikula-Eintrag.

**Comment by staude** [comment]
@lehrruetsche , bitte in zukunft ein Issue pro Problem, sonst wird das zu unübersichtlich.

Was meint "Kein Titel"?  auf  http://material.rpi-virtuell.de/material/mein-gott-ich-lobe-dich/ ist der Titel ausgegeben.

>Das Video erscheint nicht als Video, nur als Url. Ist das so gedacht?
Haben wir jemals was anderes besprochen? Dann müssten wir zusätzlich den embedcode mit speichern.

>Wie dem auch sei: sieht nicht gut aus. Kurt Mikula-Eintrag.
Das sind ungestylte Dummytemplates damit ich schon mal Code schreiben konnte um auf den Inhalt zuzugreifen und wir überhaupt schon mal was sehen.

**Comment by staude** [comment]
Andrea versucht mal die Schritte aufzuschreiben wenn das Problem erneut auftreten sollte, damit es reproduzierbar wird.
