### ISSUE TITLE
WAS ist DAS???

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#260]
![kein titel](https://cloud.githubusercontent.com/assets/15977289/26065777/3c35deac-3995-11e7-8186-ca83d8ef1f22.png)
Liebe Frank, das ist etwas ganz Schräges.
Ich habe im Materialpool "Schulgottesdienste" aufgerufen, weil ich die alte Themenseite auf Entwurf setzen wollte, es gibt ja zu dem Thema eine neue.
Ich habe sie nicht gleich gefunden, aber hier diese beiden Specials "ohne Titel". Weil eine alte Themenseite ja auch ein Special ist, habe ich es angeklickt und DAS gefunden. Was ist das? Es ist von heute. Es wirkt, als wäre es die Themenseite, die ich heute geschrieben habe. Aber es steht 27.4. dahinter und "Staude". Schräg. Ich bin ganz sicher, dass es von heute ist, weil ein ganz neuer Beitrag dabei ist, den ich erst vor wenigen Stunden eingetragen habe. Aber das war zum Thema Pfingsten. Ich verstehe das ganze Ding nicht.
Oh, es wird noch viel schräger. Wenn man nicht nur auf Vorschau klickt, wie ich es bisher gemacht habe, sondern auf Bearbeiten, dann kommt man bei Luther raus. Oder bei evangelisch-katholisch. Junge, Junge.

Die alten Themenseite zu Schulgottesdienste konnte ich bisher nicht finden.

**Comment by staude** [comment]
In den Screensgot steht 21.4. und diese Daten habe ich in meinem min 1 1/2 Wochen alten Datenbestand ebenfalls - das sind alte Themenseiten die wir als Specials importiert haben. 
![2017-05-17_0658](https://cloud.githubusercontent.com/assets/870951/26139118/946770ce-3ace-11e7-93a4-604acf3f4e16.png)
>Es wirkt, als wäre es die Themenseite
Nein, die beiden Seiten haben (warum auch immer) keinen Slug und rufen daher dann /material auf was die Maerial Archivseite ist, also die Auflistung alle Materialenträge

Wenn man das Material noch mal speichert hat es auch einen Titel und einen Slug. 
Da muss irgendwas noch damals beim Importieren falsch gewesen sein.
