### ISSUE TITLE
Zuordnung zu Themengruppen erfordert harten Reload

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#261]
Beim Zuordnen von Materialien zu Themengruppen erscheint das Häkchen immer erst nach Reload.
Ich habe der Themenseite Trauer in der Suche Material zugordnet:
http://material.rpi-virtuell.de/facettierte-suche/?thema=13637&gruppe=49&fwp_suche=trauer
![image](https://cloud.githubusercontent.com/assets/1091954/26126429/d4acaf12-3a85-11e7-947a-d25b65ecccad.png)
Erst nach Reload erscheint die Checkbox:
![image](https://cloud.githubusercontent.com/assets/1091954/26126436/dfe2fff8-3a85-11e7-8760-12f144fb5c55.png)
Die Suche ergibt 7 Seiten Suchtreffer - Bei jedem Seitenwechsel fehlen die Checkboxen:
![image](https://cloud.githubusercontent.com/assets/1091954/26126472/00586cdc-3a86-11e7-93a3-2fa4ec5762b9.png)
Immer wieder nur mit Reload erreichbar:
![image](https://cloud.githubusercontent.com/assets/1091954/26126487/0c4091be-3a86-11e7-9385-88ff241a3a0e.png)

**Comment by staude** [comment]
Normales Neuladen reicht bei mir schon.
Tippe auf unterschied AJAX/REST nachladen beim Blättern und echten laden der Seite
