### ISSUE TITLE
Bei den Themenseiten sind nur die IDs nicht die Namen der Themengruppen angezeigt

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#265]
![image](https://cloud.githubusercontent.com/assets/1091954/26249616/94f769ce-3ca7-11e7-831e-671a9efd3d96.png)
Man müsste sich handschriftlich aufschreiben, welche ID zu welcher Themengruppe gehört. 
Es sollten auch im Backend die Namen angezeigt werden:
![image](https://cloud.githubusercontent.com/assets/1091954/26249661/b9aad0d0-3ca7-11e7-8957-3e287572893d.png)

**Comment by staude** [comment]
Ja, ist halt so in der pads Repeat Komponente, Einfach mal aufklappen, dann steht da unser Gruppennanme

<img width="1430" alt="2017-05-19_1530" src="https://cloud.githubusercontent.com/assets/870951/26249793/29909e02-3ca8-11e7-8df5-e2d45ec23eb7.png">

**Comment by empeiria** [comment]
ah das schaut ja prima aus (in firefox):
![image](https://cloud.githubusercontent.com/assets/1091954/26250621/ebce4094-3caa-11e7-99ea-31d231ee7cf0.png)
In Chrome sieht es allerdings so aus:
![image](https://cloud.githubusercontent.com/assets/1091954/26250639/f8deed38-3caa-11e7-8791-e89dde17bbe2.png)
Der Editier-Stift-Button überlagert das Speicher-Disketten-Symbol und kann nicht geklickt werden

**Comment by staude** [comment]
ja, in safari auch, seit sein letzten update. einfach den Stift am untersten ende anklicken, dann klappt

**Comment by johappel** [comment]
![image](https://cloud.githubusercontent.com/assets/307023/26252026/65c3bec0-3caf-11e7-8878-24bf92b6ba80.png)
Kann man mit anderen Pods Einstellungen übersichtlicher machen:
![image](https://cloud.githubusercontent.com/assets/307023/26252110/a592f0b6-3caf-11e7-85dd-e0c9aa5b33a2.png)

oder spricht etwas dagegen @staude ?

**Comment by staude** [comment]
Nicht da sich wüsste. Hab das mal umgestellt
