### ISSUE TITLE
Vorschlagsform material via grafityforms

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#271]
Vorschlagsform material via grafityforms

**Comment by johappel** [comment]
Hinweis: Erweiterung für custom post-types
https://de.wordpress.org/plugins/gravity-forms-custom-post-types/

**Comment by staude** [comment]
Hatten wir schon festgelegt was wir alles abfragen wollen?

**Comment by staude** [comment]
url
- parsen, Beschreibung ergänzen
Beschreibung (aus geparster Webseite)
name des vorschlagenden
email des vorschlagenden

name und email aus user, wenn angemeldet

**Comment by staude** [comment]
Es gibt imho keinen Grund das mit Gravity zu machen. Url und Beschreibung fragen wir ja schon ab und tragen diese in unseren CPT ein. Gravity kann auch mit dem genannten Plugin keinen eigenen Status setzen. Insgesamt wird es komplizierter wenn wir es damit machen, statt einfach die weiteren Felder und ein bisschen JS in das bestehende einzubauen
