### ISSUE TITLE
Eintragende Person sollte genannt werden

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#272]
Bei Eintragsvorschlägen: Ich finde es schwierig, dass weder ich noch andere User eine Ahnung haben, wer etwas eingetragen hat. Kann man das machen, auch ohne angemeldet zu sein? WEnn man angemeldet sei muss, müsste es doch gehen, dass der Eintragende zu sehen ist.

**Comment by staude** [comment]
???

<img width="475" alt="2017-05-22_2024" src="https://cloud.githubusercontent.com/assets/870951/26322759/a9d24ab2-3f2c-11e7-84ee-e8cfb98eb37e.png">

Was meinst du?

**Comment by beo9999** [comment]
Ich denke es geht um http://material.rpi-virtuell.de/material-vorschlagen/ . Das Formular sollte ja möglichst einfach gehalten sein, aber die Eintragenden sollten vielleicht wenigstens die Möglichkeit haben, ihren Namen und/oder E-Mail anzugeben. (OK, kann man auch in der Beschreibung machen, aber das ist ja eigentlich nicht Sinn der Sache. Und ich gehe mal davon aus, dass in den meisten Fällen die Personen, die Vorschläge eintragen, nicht unbedingt anonym bleiben wollen).
Außerdem wäre es evtl.. auch für die Redaktion hilfreich, weil eine entsprechende Angabe in einer Spalte auf http://material.rpi-virtuell.de/wp-admin/edit.php?post_status=vorschlag&post_type=material die Vorschläge leichter identifizierbar macht (ansonsten sehen in der Übersicht ja bis auf das Datum alle Einträge gleich aus).

**Comment by staude** [comment]
Vorschlagen sind aber weder Autoren des Materials noct Materialpoolautoren, es braucht also noch ein weiteres Feld im Material das im Backend ausgegeben wird und im Frontend auch?

**Comment by staude** [comment]
Ausgabe auch im Frontend
