### ISSUE TITLE
Leitartikel "Woran glaubst du?"

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#273]
Wenn ihr auf die Bearbeitungsseite des Beitrags "Woran glaubst du" zur ARD-Themenwoche geht, seht ihr, dass ich viele Formatierungen verwendet habe. Im Leitartikel sind aber alle Formatierungen gelöscht. Es wirkt etwas unglücklich, wenn die Überschrift nahtlos in den Text übergeht. Alles fließt ineinander über. Kann man daran etwas ändern?

https://news.rpi-virtuell.de/wp-admin/post.php?post=20494&action=edit

**Comment by staude** [comment]
Wenn du die vielen STRONG meinst
<img width="1240" alt="2017-06-03_1654" src="https://cloud.githubusercontent.com/assets/870951/26754575/76c06afa-487d-11e7-995b-98c10cf10ba2.png">
die sind doch da
<img width="927" alt="2017-06-03_1655" src="https://cloud.githubusercontent.com/assets/870951/26754577/7bfde7cc-487d-11e7-8fcd-4dafa5140dd7.png">

aber wenn ich mir den den Quelltext ansehe, frag ich mich schon was das ist? Copy und Paste von der Originalseite?
<img width="1260" alt="wasistdas" src="https://cloud.githubusercontent.com/assets/870951/26754580/90562d24-487d-11e7-89c8-8694d443ec88.png">

**Comment by staude** [comment]
Und mit dem Materialpool hat es auch nichts zu tun :) 
-> https://github.com/rpi-virtuell/reliwerk/issues
