### ISSUE TITLE
News-Seite Medienabteilung

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#274]
Auf der Newsseite habe ich den Film des Monats eingegeben und außer News auch noch "Medien" angehakt. Aber es erscheint dort nicht. Ich habe es auch mit einem anderen Beitrag versucht, aber es klappte einfach nicht. Mit den anderen Bereichen klappte es gut.

**Comment by staude** [comment]
Außer das es nichts me den Materialpool zu tun hat :) hab ich es mal @johappel zugewiesen, der da am meisten an dem Newstheme geschraubt hat.

**Comment by lehrruetsche** [comment]
Danke!

**Comment by staude** [comment]
ping @johappel

**Comment by lehrruetsche** [comment]
hat sich herausgestellt, dass die Kategorie Medien es nicht mag, wenn kein Bild dabei ist. Mit Bild gings. Bei der Kategorie "Aus den Instituten" funktioniert es seltsamerweise auch ohne Bild.
