### ISSUE TITLE
Neue Materialien erscheinen wann?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#275]
Wenn ich neue Materialien in den Materialpool eintrage, dann müssten sie bei den News erscheinen. Aber das tun sie nicht. Oder irgendwann. Aber nicht, solange ich daran arbeite. Müsste ich irgendein Passwort setzen? Müsste ich ein Häkchen irgendwo machen?

**Comment by staude** [comment]
Material tauch im RSS feed auf, wen es publiziert ist.
News importiert den Feed nd gibt es auf der Seite aus, aber selbstverständlich wird der Feed dort gecacht. Nicht bei jeden Seitenabruf der Newsseite läuft die Newsseite den Feed von Material neu.
