### ISSUE TITLE
Veranstaltungen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#276]
Was wirklich richtig Freude macht, ist Veranstaltungen einzutragen. Wenn man keine Straße hat, wie zum Beispiel bei den Toren der Freiheit in Wittenberg oder der 500schools Geschichte, dann wird die ganze Veranstaltung nicht angenommen. Und zwar wird der komplette Eintrag gelösch tund gessagt: Ätsch, geht nicht, Straße fehlt. 
Das nervt dermaßen, ich habe schon Straßen bei Google Maps gesucht, die ich eintragen kann. So kann man auch seine Arbeitszeit verbraten. Kann man da irgendwas machen??? Nicht jede Veranstaltung hat tatslich eine Straße oder Hausnummer, auch wenn das System das nicht glauben will. Ich glaube, den letzten Eintrag habe ich mindestens sechs mal geschrieben.

**Comment by staude** [comment]
im Materialpool gibt es keine Veranstaltungen -> https://github.com/rpi-virtuell/reliwerk/issues

**Comment by staude** [comment]
>So kann man auch seine Arbeitszeit verbraten.

Ja, und Einträge im falschen repo, dazu noch ohne die Infos wie URL, was wurde genau gemacht uns wird bei der Bearbeitung de Tickets auch noch Arbeitszeit verbrannt, weil jetzt vermutet und gemutmaßt wird.

Ich vermute du meinst das Veranstaltungsplugin auf news.

Da hab ich gerade mal einen Eintrage gemacht, da kommt dann der Hinweis.
>Deine Veranstaltung Details sind inkorrekt und können nicht veröffentlicht werden. Bitte korrigiere erst diese Fehler:
>Die Adresse des Veranstaltungsortsist erforderlich.
>Die Stadt des Veranstaltungsortsist erforderlich.

Aber das ist nichts einfach so dann weg.

Und meine persönliche Meinung ist. Veranstaltungen die keine Adresse haben will ich nicht haben. Ist total super im Internet eine tolle Veransltaung zu finden und dann nicht zu wissen wo man denn nun genau hinmuss. Ist ja schon wichtig ob man als nicht Autofahrer vom Bahnhof in 5 min da ist oder erst ne Stunde durch die Stadt wandert, oder ggf den ÖPNV nutzen muss/will. 

Ansonsten gilt: Anforderungen definieren, dann kann die Technik schauen wo mit man das abgebildet bekommt.

**Comment by lehrruetsche** [comment]
Nun ja, die sieben Tore der Freiheit haben nun mal keine Adresse. Wittenberg ist überschaubar :-)
Und das Festzelt neben Tor 5 - ich habe keine gefunden. Tut mir leid, ich muss noch mehr Favoriten anlegen. Ich vergesse immer, dass es in Github mehrere Streams gibt. Alte Gewohnheit...
Ich versuche, mich zu bessern.

**Comment by johappel** [comment]
Es handlet sich doch hier um Beschränkungen des Plugins Eventmanager. Warum müssen sich jetzt alle damit beschäftigen?

**Comment by lehrruetsche** [comment]
Weil man tatsächlich eine Veranstaltung wie die Weltausstellung in
Wittenberg nicht eintragen kann und ich dachte, daran ließe sich mit dem
Zauberstab des Programmierers etwas ändern.

Am 05.06.2017 14:32 schrieb "Joachim Happel" <notifications@github.com>:
