### ISSUE TITLE
Kein embed von mp4-Filmen

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#277]
Auf https://material.rpi-virtuell.de/material/aktion-schulstunde-zur-ard-themenwoche-woran-glaubst-du/ habe ich angefangen Unterrichtsmaterial zur ARD-Themenwoche "Woran glaubst du?" als special anzulegen. Leider wird die mp4 nicht erkannt und eingebettet:
![image](https://user-images.githubusercontent.com/1091954/26916543-136f7e3a-4c2b-11e7-9f6b-8784c98e8eb3.png)
Auf news.rpi-virtuell sieht der gleiche Artikel so aus: 
![image](https://user-images.githubusercontent.com/1091954/26916565-249399c6-4c2b-11e7-9f09-87ef3637e6e3.png)

**Comment by staude** [comment]
Returns :) 
Ein Return nach der URL wirkt wunder.
