### ISSUE TITLE
open graph - facebook & twitter

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#278]
Wie schaut's denn mit den Metadaten aus für open graph und TwitterCards? 
Wenn man Materialpooleinträge auf facebook oder Twitter postet, fehlen die Vorschaubilder und es schaut noch nicht so toll aus.

**Comment by empeiria** [comment]
Ich würde das gerne weiter oben priorisieren, da wir mit News und materialticker zunehmend Einzelmaterialien in den Sozialen Netzwerken teilen wollen. Kann einfach provisorisch ein Plugin installiert werden?

**Comment by staude** [comment]
Das wird nicht funktionieren weil wir alles in eigenen Feldern haben.

packe es nach oben auf meiner liste, nach dem User ins Blog einladen.
