### ISSUE TITLE
Registrieren auf der Materialpoolseite

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#279]
Könnte man es nicht so einrichten, dass man sich auf allen Seiten sowohl anmelden als auch registrieren lassen kann? Auf der Materialpoolseite kann man sich nicht registrieren lassen, obwohl wir wissen, dass dies die "Hauptseite" ist.

**Comment by staude** [comment]
auf news und material einen "Register" Button einbauen wie auf about bereits geschehen.
