### ISSUE TITLE
Werk

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#28]
Ich wollte eben einen Artikel mit dem dazugehörigen Gesamtwerk verknüpfen und eigentlich stand da "Start Typing", ich wusste nur gar nicht, wo ich das GEsamwerk vorher hätte erfassen können. Es gibt im Menü den Punkt "Verknüfpungen" nicht.

**Comment by staude** [comment]
Ein Werk wird ein Werk wenn entweder dem Material ein Band zugeordnet wird (dann ist das zu bearbeitend Material das Werl) oder wenn ein Material einem Werk zu geordnet wird  ( dann ist das zu bearbeitende Material das Band)

Dieses Material wird zu einem Werk, dadurch das ihm ein Band zugeordnet wird.
![2016-11-14_1845](https://cloud.githubusercontent.com/assets/870951/20275934/9cd057ea-aa9a-11e6-9916-230ddea409c5.png)
