### ISSUE TITLE
Trennstrich "More" funktioniert bei Leitartikeln nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#281]
Bei manchen Leitartikeln wäre es praktisch, wenn man einen Trennstrich verwenden könnte, zum Beispiel wenn danach Aufzählungen folgen. Aber das funktioniert leider nicht:
https://news.rpi-virtuell.de/
Leitartikel Schul- und Schülergottesdienste

**Comment by johappel** [comment]
Der Slider verwendet nicht die More Funktion sondern nur den Auszug:
![2017-06-22_13h44_41](https://user-images.githubusercontent.com/307023/27432690-81eea1f2-5751-11e7-8bbc-109a2bb0a131.gif)
Das Ergebnis ist dann wie gewünscht:
![image](https://user-images.githubusercontent.com/307023/27432701-931f04da-5751-11e7-91f1-3a96522d4b1f.png)
