### ISSUE TITLE
Hinweisbox Materialwiederholung

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#282]
Manchmal, wenn ich Material konvertiere, taucht ein Hinweis auf, dass der Titel dieses Materials schon einmal bei einem anderen Material verwendet wurde. Der Begriff Material ist blau unterlegt und wenn man ihn anklickt, landet man immer im Nichts - und nicht bei dem Material, das auch diesen Titel trägt.
Screenshot des Vorgangs in der Anlage.
![hinweis materialwiederholung](https://user-images.githubusercontent.com/15977289/27475403-6541d506-5805-11e7-836f-5c208878aa26.png)

**Comment by staude** [comment]
Kannst du. bitte die Ziel URL die ins "nichts" führt hier mal reinkopieren?

**Comment by lehrruetsche** [comment]
https://material.rpi-virtuell.de/wp-admin/post.php?post=15167&action=edit
