### ISSUE TITLE
Screenshot funktioniert hier nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#283]
https://material.rpi-virtuell.de/material/engagierter-buddhismus/

**Comment by johappel** [comment]
Das lag in dem konktreten Fall daran, dass du eine Adresse gewählt hast, die anschließend auf http://buddhanetz.org/ umgeleitet hat. Als ich diese Adresse eingetragen habe, hat auch der Sreenshot funktioniert.
