### ISSUE TITLE
Gliederung verschwindet bei der Übersichtsseite

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#284]
Wenn ich ein Material eingebe und Kapitel oder Abschnitte darstelle mit Gliederungsstrichen, so erscheinen diese nicht bei der Zusammenfassung, was dann etwas verwirrend wirkt:

https://material.rpi-virtuell.de/facettierte-suche/?fwp_paged=4

Siehe bei Jesus Christus - Worauf gründet das Christentum?

**Comment by staude** [comment]
In den Auflistungen erscheint nicht der vollständige Text, sonder wird ggf beschnitten, daher wird HTML entfernt, weil sonst ja evtl Tags nicht wieder geschlossen werden.
Eventuell kannst du vor der Auflistung ein MORE Tag setzten um zu verhindern das diese mit in der Übersicht ausgegeben wird.
