### ISSUE TITLE
Hier funktioniert der Viewer nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#286]
Hier wird von der ARD ein PDF angeboten, das leider im Viewer nicht zu sehen ist. Ich habe den Viewer jetzt rausgenommen:

https://material.rpi-virtuell.de/material/bestattungsriten-in-den-weltreligionen/

**Comment by staude** [comment]
danke, hab es in die Liste aufgenommen.
