### ISSUE TITLE
"Unterrichtende" wird nicht angezeigt

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#287]
Im Frontend wird die Bildungsstufe "Unterrichtende" nicht angezeigt. Ist das gewollt so?

**Comment by staude** [comment]
In der Facette wird es ausgegeben

<img width="792" alt="2017-06-28_1031" src="https://user-images.githubusercontent.com/870951/27627762-3b83588e-5bed-11e7-92cb-c19f34f91a1b.png">

in der Detailansicht eines Materials nicht, weil dort nicht die oberste ebene der Bildungsstufen ausgegeben wird. Sonst stände da auch  Schulstufen und Gemeinde als Bildungsstufe zusätzlich.
<img width="404" alt="2017-06-28_1032" src="https://user-images.githubusercontent.com/870951/27627791-5824c964-5bed-11e7-8a56-c1666d75cf65.png">

Daher, erst mal ja, das ist so gewollt.  Ansonsten muss das diskutiert werden.
