### ISSUE TITLE
Bei ZEIT Online funktioniert der Viewer nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#288]
https://material.rpi-virtuell.de/material/buddha-in-berlin/

**Comment by staude** [comment]
http://pdf.zeit.de/2013/33/buddhismus-kaiserreich-interview-martin-baumann.pdf redirected mich auch sofort auf http://www.zeit.de/2013/33/buddhismus-kaiserreich-interview-martin-baumann  inkl derer $%§$ Paywall.

habe den Viewer deaktiviert. Frage ist; Was ist die Verfügbarkeit in dem Fall. Kostenfrei nach Anmeldung stimmt ja auch nicht ganz, ich hab ja nicht beliebig viele Artikel frei.

<img width="1920" alt="2017-06-28_1023" src="https://user-images.githubusercontent.com/870951/27627392-eb6685d4-5beb-11e7-869f-6a28edd082dd.png">
