### ISSUE TITLE
Hier funktioniert der Screenshot nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#289]
https://material.rpi-virtuell.de/material/deutsche-buddhistische-union-e-v/

**Comment by johappel** [comment]
Interessanter weise wird da die Folge Imgage Url erzeugt

http://www.buddhismus-deutschland.de/wp-content/themes/modernize/images/Social-Thumbnail.jpg
die aus den Metatags der Seite stammen:
`<meta property="og:image" content="http://www.buddhismus-deutschland.de/wp-content/themes/modernize/images/Social-Thumbnail.jpg"/>`

Der Fehler liegt also offenbar in der Quellseite selbst.

**Comment by staude** [comment]
Ja, das ist ein weit verbreitetes Problem, das Seite defekte OG Metas in ihre Seiten schreiben. 
Auch bei diesen Kollegen schrieb ich mal den Webmaster an.

**Comment by johappel** [comment]
@staude Wie könnte man der Materialpoolredaktion helfen, das Problem selbst zu erkennen?

**Comment by staude** [comment]
http://www.buddhismus-deutschland.de/wp-content/uploads/Logo-Quader-375x275-300x220.png als Cover hinterlegt.

@johappel Wenn Screenshot fehlschlägt muss man halt eine cover url hinterlegen, da zu erkennen ist ja relativ einfach. Das Andrea das hier melden soll hat ja den Grund herauszufinden ob es noch Konstellationen gibt wo es Probleme macht. Aktuell ist es immer auf fehlerhafte Metaangaben zurückzuführen. Frage ist halt, wieviel Aufwand man da treiben will. Theoretisch müsste man alle og:image nehmen laden, wenn kein 404 diese in einer box zur Auswahl stellen welches verwendet werden soll. Aktuell nutze ich einfach das erst image.
