### ISSUE TITLE
Als "attackierend" gemeldete Website

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#290]
Das hatte ich auch zum ersten Mal:

http://www.donat-schmidt.de/files/downloads/philosophieundethik/religionen/buddhismus-stationen1.pdf

Donath Schmidt hat einen Stationenarbeit zum Buddhismus online gestellt, die sich nicht öffnen lässt, weil sie eine "attackierende Website" ist. Löschen oder Abwarten, was sich tut?

**Comment by johappel** [comment]
Das heißt auf jedenfall sollten wir unser Material erst mal nicht veröffentlichen, besser löschen.
