### ISSUE TITLE
Bild bei spezial

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#293]
Ich habe ein Spezial gemacht und wollte ein Bild hochladen, aber das Bild zeigt sich nicht  auf der Frontpage.
Was mache ich falsch?
https://material.rpi-virtuell.de/material/themen-des-buddhismus-beim-deutschlandfunk/

**Comment by staude** [comment]
Specials geben im Template das Beitragsbild/Cover nicht aus. Entweder wir ändern das  ( dann bitte neues Ticket für die Diskussion machen)  oder du fügst das Bild einfach in den Text im Editor mit ein.

**Comment by lehrruetsche** [comment]
okay
