### ISSUE TITLE
Bild-Plugin bei einem Spezial

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#295]
Das Bild-Plugin bei den Spezials des Materialspools entspricht nicht den anderen.
Sollte das geändert werden? Quellenangabe ist zum Beispiel nicht so eindeutig wie bei den anderen Materialien.

**Comment by staude** [comment]
??? 
URL?

**Comment by lehrruetsche** [comment]
https://material.rpi-virtuell.de/material/themen-des-buddhismus-beim-deutschlandfunk/

**Comment by staude** [comment]
Die eigentliche Frage lautet, kann bei einem Spezial im Template das Cover ausgegeben werden.
