### ISSUE TITLE
Kein Viewer, trotz pdf

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#296]
http://www.zwischentoene.info/themen/unterrichtseinheit/praesentation/mat/-/download/Unterrichtseinheit.html?type=1249058993&tx_uemat_uemat%5Bfile%5D=1372

Über diesen Link komme ich auf ein PDF, aber die Adresse gibt es irgendwie nicht anders her und es erscheint auch kein Viewer

https://material.rpi-virtuell.de/material/tod-und-sterben-zwischentoene/

**Comment by staude** [comment]
an der url kann die Seite nicht erkennen ob es ein pdf ist - hab mal einen dummyparamter &pdf=.pdf angefügt.
