### ISSUE TITLE
Ich krieg diese Bildquelle nicht gelöscht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#297]
Also, nicht Materialpool, sondern News: dort wird bei Mediathek, fehlende Bildquellen das hier angegeben:
https://news.rpi-virtuell.de/wp-admin/upload.php?page=isc_missing_sources_page

Ich habs versucht zu löschen, es wird im Papierkorb angezeigt, aber ist immer noch da. Da der Kirchentag vorbei ist, können wir das echt rausnehmen und kriegen keinen Ärger, irgendwas mache ich da falsch.

**Comment by staude** [comment]
Welche denn? da sind viele?
@empeiria kannst du da helfen?

![2017-06-29_1105](https://user-images.githubusercontent.com/870951/27680123-0c9bf69c-5cbb-11e7-8545-5555ae7a8f3d.png)

**Comment by empeiria** [comment]
Löschen geht nur in der Medienübersicht:
https://news.rpi-virtuell.de/wp-admin/upload.php
![image](https://user-images.githubusercontent.com/1091954/27680732-0bd4a00e-5cbd-11e7-9138-04fa765afbea.png)
Ist dir damit geholfen, @lehrruetsche ?

**Comment by lehrruetsche** [comment]
Cafe Bildung Flyer

**Comment by staude** [comment]
Problem behoben @lehrruetsche ? Dann bitte das Ticket schliessen
