### ISSUE TITLE
Mailpoet Materialpool: Bilder lassen sich nicht alle öffnen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#298]
Unser rpi-ticker von heute ist bei mir angekommen. Die Screenshots lassen sich nicht öffnen. Das Bild, das ich selbst eingefügt habe, ist da.

**Comment by staude** [comment]
Ich denke mal, du meinst das im Mailprogramme die Bilder nicht angezeigt werden. Der Link auf den Bilder ist da und funktioniert.
