### ISSUE TITLE
Umständlichkeiten beim Konvertieren

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#300]
Wenn ich Materialien konvertiere zu einem Thema, muss ich das Thema ständig neu eingeben. Also siebzigmal Gleichnisse. Früher gab es eine Art "Zwischenspeicherung", so dass ich immer direkt auf die Auswahl "Gleichnisse" zurückspringen konnte und nicht jedes Mal bei Null anfangen musste. Ist so etwas bei wordpress auch denkbar? Ich erläutere es gerne am Bildschirm, wenn ich mich hier unverständlich ausgedrückt habe.

**Comment by staude** [comment]
Wieso öffnest du die Detailseiten nicht einfach jeweils in einem neuen Tab?

**Comment by johappel** [comment]
[STRG] festhalten wenn du mit der Maus auf den Konvertieren Knopf klickst

**Comment by staude** [comment]
Eigentlich schon vorher. Wenn du das Suchergebnis hast, klickst du den link zum Material mit gedrückter STRG Taste an, dann wird die Seite in einem neuen Tab geöffnet.
Können wir gerne auch noch mal gemeinsam durchgehen.

**Comment by staude** [comment]
ist das geklärt @lehrruetsche ?
