### ISSUE TITLE
upload einfügen funktioniert bedingt

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#301]
Bei mir läuft's, aber bei @lehrruetsche geht es weder in Chrome noch in Firefox:
https://youtu.be/ubXZxy0dkVU

**Comment by staude** [comment]
Was sagt die Browserkonsole bei @lehrruetsche ? Müsste mit größter Wahrscheinlichkeit ein Javascript Problem sein.

**Comment by staude** [comment]
ping @lehrruetsche

**Comment by staude** [comment]
Das das identisch zu #314 ?

**Comment by empeiria** [comment]
oh :-) ja!

**Comment by empeiria** [comment]
evtl. liegt's an @lehrruetsche s neuem PC - Kann man da etwas unterstützend machen, um das Javascript-Problem zu finden?

**Comment by staude** [comment]
Ja per Teamviewer oder ähnlichem draufschauen lassen. 
Oder überhaupt mal die fehlerkonsole aufmachen und schauen was da steht. 
Siehe meinen Kommentar oben
