### ISSUE TITLE
Bild erscheint nicht

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#302]
Es kann sein, dass das mal wieder an meinem PC liegt. Könntet ihr schauen, ob das eingegebene Bild von Max Slevogt bei euch auftaucht?

https://material.rpi-virtuell.de/material/gleichnisse-in-der-grundschule/

Ansonsten gibt es ein Problem mit der Bildanzeige.

**Comment by johappel** [comment]
![image](https://user-images.githubusercontent.com/307023/27902425-fe616b40-6235-11e7-9bb5-3a0d929d546b.png)

Das Bild wird nur in der Listung angezeigt und nicht auf der Detailseite des Spezials,. Das hatten wir so vereinbart, damit man in Spezials die Bilder individuell im Text unterbringen kann. (War am Monta Thema in der Teamsitzung)

**Comment by empeiria** [comment]
![image](https://user-images.githubusercontent.com/1091954/27904178-1a3f2496-623c-11e7-993e-85e3f81770e7.png)
Nur in der Übersicht

**Comment by lehrruetsche** [comment]
okay
