### ISSUE TITLE
Mailpoet - Was wurde schon losgeschickt?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#304]
Eine gewisse Schwierigkeit ist für mich, dass ich nicht erkennen kann, welches Material ich für den Mailpoet schon ausgewählt habe. Ich muss entweder händisch eine Liste führen oder die alten schnell nochmals durchgucken. Früher war das Material einfach aus dem Redaktionstool verschwunden.
Gibt es hier die Möglichkeit einer technischen Unterstützung?

**Comment by staude** [comment]
Auf die schnelle hab ich kein Plugin gefunden das MailPoet derartig nachrüstet.

Ist das denn wirklich ein Problem? Ich dachte primär geht es darum, jeweils neues Material vorzustellen?  Und wenn du dann man einen Thema Newsletter machst und da was vorkommt das schon  mal als neues Material vorgestellt wurde, dann ist das so.  

Wenn ich mich irre, und das wirklich ein Problem ist, dann muss man mal schauen ob man diese Info irgendwie in den Dialog reinbekommt. Wobei das Problem ist, das man nicht weiß ob ein Material versendet wurde oder nicht. Du kopierst es in den Newsletter, das kann man evtl noch abfragen. Aber du kannst im Entwurf ja noch wieder löschen - man müsste also beim versenden des Newsletters die MaterialURLs Parsen um rauszufinden welches Material im Newsletter angeteasert wurde.

**Comment by lehrruetsche** [comment]
Es ist vermutlich einfacher, wenn mal alles vom alten in den neuen Materialpool übertragen ist. Dann wird die Reihe der neu erscheinenden Materialien übersichtlich sein. Aber wenn ich viel übertrage, dann kann es echt unübersichtlich werden.

**Comment by empeiria** [comment]
Das technisch zu lösen finde ich recht aufwändig - zumal man evtl. hin und wieder auch ein best-of verschicken will oder künftig noch an Abonnenten, die z.B. "nur Grundschulmaterialien" haben wollen. Dann wären alle bereits versendeten Materialien nicht mehr verfügbar. Es sollte ein Leichtes sein, beim letzten newsticker nochmal kurz nachzuschauen, ob sich nichts doppelt. Und selbst wenn und falls es überhaupt auffällt - fände ich es unproblematisch.

**Comment by lehrruetsche** [comment]
Was du "ein leichtes sein" nennst, ist rein technisch nicht schwierig, aber etwas nervig.
Aber wenns keine technische Lösung gibt, gibts halt keine. 

Nicht alles war schlecht...

**Comment by staude** [comment]
>Dann wären alle bereits versendeten Materialien nicht mehr verfügbar

Nein, das nicht, es müsste nur ein info in der Liste erscheinen das dieses Material schon mal verwendet wurde.  

>Aber wenns keine technische Lösung gibt, gibts halt keine.

es gibt keine Einfache, die Frage ist also ob das so richtig ist, das ich mich in der verbliebenen Zeit bis Ende September da dran setze.

**Comment by lehrruetsche** [comment]
ne, dann gibts wirklich wichtigere Probleme, die Themenseiten zum Beispiel, die Mails...
