### ISSUE TITLE
Leider kein Screenshot

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#306]
Hallo Frank, hier war leider kein Screenshot möglich:

https://material.rpi-virtuell.de/material/festjahr/

**Comment by staude** [comment]
Wieder mal der Klassiker - og:image fehlerhaft

< meta property="og:image" content="http://www.festjahr.de/">

**Comment by staude** [comment]
Webseitenbetreiber angeschrieben
