### ISSUE TITLE
Eintragende Personen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#307]
Wie ich die Sachlage einschätze, lässt sich daran nichts ändern. Aber alle Einträge sind von mir, obwohl sie vielleicht ursprünglich von Michael Beisel, Manfred Spieß, Christoph Terno u.a.m. sind.
Das finde ich nicht gerade glücklich. Ich kann auch nicht erkennen, wer sie eingetragen hat, weil immer Frank Staude angegeben ist.

**Comment by staude** [comment]
diese info wurde nicht mit importiert

**Comment by lehr-ruetsche** [comment]
Sehr bedauerlich. Langsam sieht das wie mein persönlicher Materialpool aus.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. September 2017 10:02
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Eintragende Personen (#307)

 

diese info wurde nicht mit importiert
