### ISSUE TITLE
Für Frank: Screenshot zur EKD funktioniert leider nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#309]
https://material.rpi-virtuell.de/material/reformation-5/

**Comment by staude** [comment]
<meta property="og:image" content="https://www.ekd.de" />
Langsam muss ich mir mal gedanken machen kaputt og:image abzufangen. Das scheint ja echt unglaublich Kompliziert zu sein das was reinzuschreiben.

**Comment by lehr-ruetsche** [comment]
Ja, ist halt blöd, dass es gerade bei der EKD und der bpb ist. Wobei es mir bei der EKD bisher nicht aufgefallen wäre, bei der bpb war es immer schon so.
