### ISSUE TITLE
Name wird falsch geschrieben

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#31]
Bei Autoren habe ich eingetragen: Frieder Harz
Im Material wird daraus: Frieder Harrz
Und ich kanns nicht ändern.

**Comment by staude** [comment]
Frieder Harz existierte schon als Autor, ich hatte den damals aus dem vorherigen Testsystem übernommen, vermutlich aber einmal mit doppel r eingetragen. Hab den gelöscht und das dem zugeordnete Material dem neuen Autoren zugeordnet.
