### ISSUE TITLE
Für Frank: Seltsamer Screenshot

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#310]
https://material.rpi-virtuell.de/material/einfuehrung-in-die-reformation-in-ulm-ein-rollenspiel/

Weißt Du, was hier passiert?

**Comment by staude** [comment]
@lehr-ruetsche  Ja, das ist die erste als og:image referenzierte Datei im Seiten Quelltext. Ist halt dummerweise das logo das verwendeten CMS http://www.schule-bw.de/logo.png

Bleibt nur Screenshot löschen und das korrekte logo als cover hinterlegen
