### ISSUE TITLE
Protokoll nicht berücksichtigen bei URL Check

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#311]
Eben kam der Artikel von der EKD zur Reformation nochmals. Ich habe die Adressen verglichen, sie sind gleich. Das hätte angezeigt werden müssen???

https://material.rpi-virtuell.de/material/reformation-5/

https://material.rpi-virtuell.de/material/reformation-8/

Ich habe jetzt beide angelegt, damit ihr es anschauen könnt.

**Comment by staude** [comment]
http://www.ekd.de/glauben/abc/reformation.html
https://www.ekd.de/glauben/abc/reformation.html

einmal http einmal https

**Comment by lehr-ruetsche** [comment]
bissle blöd, oder?

**Comment by staude** [comment]
>bissle blöd, oder?

 sind erst einmal unterschiedliche URLs, die theoretisch sogar unterschiedlichen Inhalt ausliefern könnten ( dürfte in der Praxis aber nicht vorkommen)

Featurerequest: Protokoll nicht berücksichtigen bei URL abgleich

**Comment by staude** [comment]
ich lösche dann mal https://material.rpi-virtuell.de/material/reformation-8/ damit das Material nicht doppelt ist

**Comment by lehr-ruetsche** [comment]
okay
ist nichtdie https seite die eigentlich sicherere? dachte ich immer...

**Comment by staude** [comment]
ja, und -5 ist die mit https
