### ISSUE TITLE
Hier funktioniert leider der Viewer nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#312]
allerdings kommt man ja auch nicht direkt auf das Material.

https://material.rpi-virtuell.de/material/reformation-und-bildersturm/

Soll ich den Viewer rausnehmen?

freidoc haben wir öfters

**Comment by staude** [comment]
mit der passenden url und ein bisschen tricksen sie dann vom Viewer noch akzeptiert wird
->https://freidok.uni-freiburg.de/fedora/objects/freidok:3578/datastreams/FILE1/content?.pdf

klappts auch

**Comment by lehr-ruetsche** [comment]
toll!!!
