### ISSUE TITLE
Bindestrick verwandelt sich in Fragezeichen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#313]
Lieber Frank, du wolltest doch, dass ich dich aufmerksam mache, falls mir das mit dem Bindestrich wird zum Fragezeichen nochmals passiert. Das war eben der Fall.
Ich habe diesen Link:
http://worthaus.org/mediathek/der-mensch-und-die-tiere-genesis-2-19-20-3-3-2/ aus der alten Redaktion in den neuen Materialpool übertragen. Dort sah er dann so aus: (Ich lasse den Fehler drin):
https://material.rpi-virtuell.de/material/der-mensch-und-die-tiere-genesis-2-1920/

**Comment by lehr-ruetsche** [comment]
Bindestrich natürlich :-)

**Comment by johappel** [comment]
Scheint ein copy & paste problem zu sein. Wird ein "echter" Bindestrich und kein langer Bindestrich eingefügt wie hier: (Genesis 2, 19–20)
funktioniert es

**Comment by staude** [comment]
War es denn bei dem "alten" Material noch korrekt? So wie bei diesen hier https://material.rpi-virtuell.de/archiv/?fwp_suche=genesis ? Und erst nach dem konvertieren war der Bindestrich falsch?

**Comment by lehr-ruetsche** [comment]
Irgendwo hatte ich das doch schon mal beantwortet :-)  Ich kann mich nicht erinnern, dass das Problem im alten aufgetaucht wäre. Falls mal was entsprechendes von Worthaus kommt, kann ich es ja probieren. Aber wenn das so ein eng eingegrenztes Problem ist, dann kann man es ja wirklich händisch lösen.

**Comment by staude** [comment]
Ich finde das nicht als altes Material in meiner lokalen Testinstallation. 

Kann es sein, das es nicht um die Konvertierung von "alten" Material im WordPress geht, sondern das du aus dem alten System den Titel per Copy&Paste übernommen hast?  
Wenn ja, ist der Eintrag da noch vorhanden?  Wie kann ich Darauf zugreifen?

Wenn ich den Titel von der Seite des Materials ( http://worthaus.org/mediathek/der-mensch-und-die-tiere-genesis-2-19-20-3-3-2/ ) per Copy&Paste übernehme kann ich den Fehler auch nicht reproduzieren.
