### ISSUE TITLE
Für Frank: Screenshot funktioniert hier nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#315]
https://material.rpi-virtuell.de/material/katharina-von-bora-2/

**Comment by staude** [comment]
OG:Image http://frauen-und-reformation.de/upload/7489d941752cf216b5349223f861de62.jpg Seite gibt es nicht. Der Klassiker - ich versteh es nicht das so viele Seiten defekte Metadaten haben.

Screenshot manuell als cover gemacht
