### ISSUE TITLE
Für Frank: Hier wird das PDF nicht im Viewer hochgeladen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#316]
https://material.rpi-virtuell.de/material/luthers-schriften-ueber-die-juden/

**Comment by empeiria** [comment]
Quelle: file:///C:/Users/lehr-ruetsche/Downloads/Texte_168_Luthers_Schriften_ueber_Juden_2013.pdf
Die URL zeigt auf ein lokales Verzeichnis auf deinem Computer, @lehr-ruetsche

**Comment by empeiria** [comment]
Ich schlage vor, diesen Link zu nehmen: http://www.velkd.de/publikationen/texte-aus-der-velkd.php?publikation=251&kategorie=22

**Comment by empeiria** [comment]
oder wir stellen es bereit: https://material.rpi-virtuell.de/wp-content/uploads/2017/07/Texte_168_Luthers_Schriften_ueber_Juden_2013.pdf

**Comment by lehr-ruetsche** [comment]
erledigt
