### ISSUE TITLE
Für Frank: Screenshot funktioniert nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#317]
Kann sein, dass wir ZEITZEICHEN schon mal hatten:

https://material.rpi-virtuell.de/material/spiel-auf-der-nationalen-klaviatur/

Hier klappts erstaunlicher weise:

https://material.rpi-virtuell.de/material/verblueffte-feinde/

**Comment by staude** [comment]
Seite keine keine Metadaten drin und blockt offensichtlich den WP Screenshot Dienst. Habe ein Screenshot erstellt und manuell hochgeladen
