### ISSUE TITLE
Das Problem der "alten Themenseiten"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#318]
Egal welches Schlagwort ich eingebe, es tauchen unendlich viele alte Themenseiten auf. Gebe ich Kirchenjahr ein, rechne ich schon mit Advent, Weihnachten usw., aber nicht unbedingt mit Jakob, Josef, Web 2.0
Sie "verstopfen" die Suche. Ich weiß nicht, ob es reicht, dass irgendwo in den themenseiten das Wort Kirche oder Jahr vorkommt, vermutlich schon. Ehrlich gesagt, zerstören diese Themenseite unsere ganze Mühe, was die facettierte Suche angibt. Spätestens nach drei bis fünf Seiten gibt man auf. Sie nerven einfach. Wenn sie wenigstens einigermaßen passen würden, aber das tun sie nicht.

**Comment by staude** [comment]
Die Suche nach Kirchenjahr https://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=kirchenjahr sagt das es 80 Treffer im alten Material gibt https://material.rpi-virtuell.de/archiv/?fwp_suche=kirchenjahr
 Seiten Jakob, Josef oder Web 2.0 sehe ich da nicht. ( URLs?)

Und bei Seiten wie https://material.rpi-virtuell.de/zeit-der-vorbereitung/ lautet die Antwort nach dem Treffer. Die Material URL _> http://www.katholisch.de/glaube/unser-kirchenjahr/zeit-der-vorbereitung

Grundsätzlich: URLS, screenshots, videos, irgendwas.

Ich weiss nicht, wo ich was sehen kann von dem was du beschreibst

**Comment by lehr-ruetsche** [comment]
Ich meine ja nicht das alte Material, sondern das neue. Wenn ich in den Sucher "Kirchenjahr" eingebe, kommen nacheinander Konfessionelle Kooperation, dann Advent (okay), Jom Kippur, auf Seite 4 kommen vier oder fünf Themenseiten, davon eine zu Ehe, auf Seite 5 kommen Schuld, Tod, Amos usw.; das meine ich.

**Comment by staude** [comment]
> zerstören diese Themenseite unsere ganze Mühe, was die facettierte Suche angibt. Spätestens nach drei bis fünf Seiten gibt man auf

Dafür sind dann ja die Facetten da. um weiter zu filtern

ich seh schon, bedarf auch der Besprechung

**Comment by lehr-ruetsche** [comment]
Ja, tatsächlich ergibt sich das Problem, wenn man nicht facettiert sucht. Ich mache das gerne am Anfang (um einen Überblick zu bekommen) und am Schluss (zur Kontrolle). Und wenn man nur das Schlagwort eingibt und keine weiteren Details, dann hat man vor allem das "Alte-Themenseiten-Problem". Sobald man in die FAcetten geht, wird es gleich viel besser.

**Comment by empeiria** [comment]
Sieht so aus, dass es ein Erklärung zur facettierten Suche braucht. Anleitung: "Wie suche ich im Materialpool"?
