### ISSUE TITLE
Bei der facettierten Suche werden nicht nur Schlagworte abgesucht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#319]
Eben habe ich eine Themenseite zu Kirchenjahr angelegt. Bei der facettierten Suche ist mir aufgefallen, dass mehrere Seiten kamen, in denen es nur um Weihnachten ging, oder Ostern, oder Buß-und Bettag. Ich habe mich dann über mich selbst geärgert, dass ich da das Stichwort Kirchenjahr zusätzlich eingegeben habe. Als ich die einzelnen Seiten durchging, um den Tag Kirchenjahr herauszulöschen, weil es ja eigentlich nur um einzelnen Feiertag ging, stand da nur ein einziges Mal kirchenjahr. Bei allen anderen stand tatsächlich nur der einzelne Feiertag in den Tags. Aber Kirchenjahr stand in der Überschrift. Wäre das irgendwie möglich, dass man den Tag höher gewichtet als die Überschrift? Oder gibt es sonst eine Lösung, dass das Stichwort, das man sucht, auch als solches zuerst angezeigt wird und nicht, weil es irgendwie im Zusammenhang halt auftaucht?

**Comment by staude** [comment]
>Bei der facettierten Suche

Es gibt eine Suche, die ganz viele Felder berücksichtig und unterschiedlich gewichtet.
Und es gibt eine favettierte Navigation, die die Suchergebnisse weiter einschränkt.

ja, wir können Schlagworte höher Gewichten.  Sinnvollerweise überlegt man das mal gemeinsam und ändert nicht jedes mal auf Zuruf was und nöchstemal wenn und was auffällt wo einem das Ergebnis nicht gefällt dann erneut ohne die vorherigen Suchen erneut zu prüfen.

Aktuell ist die Gewichtung so
![2017-07-27_1408](https://user-images.githubusercontent.com/870951/28669591-28f3259c-72d5-11e7-83d4-5b9253df6dfe.png)

**Comment by lehr-ruetsche** [comment]
ja, dann besprechen wir das mal, weil ich ja auch nicht weiß, welche Konsequenzen manche Änderungen dann wieder auf andere Felder haben.
