### ISSUE TITLE
Medientypen ERzählung ergänzen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#32]
Bei den Medientypen finde ich den Unterschied zwischen einer Herausforderung und einer Aufgabenstellung sehr eng, und was ist eine Lektion in Religion? 

Da immer mal wieder Erzählungen eingetragen werden, würde ich diesen Bereich noch um "Erzählung" ergänzen.

**Comment by staude** [comment]
Erstellung eines Kriterienkatalogs wann die Redaktion so etwas selbst hinzufügt.
