### ISSUE TITLE
Suche Beispiel Schulgottesdienste

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#320]
Ich habe eben bei Schulgottesdienste etwas nachgeschaut. Als ich das erste Mal Schulgottesdienste eingab, kam zuerst die Themenseite usw., alles korrekt. Dann habe ich die Themenseite aufgerufen und dort einen Fehler festgestellt. Ich habe den Fehler verbessert. Dann habe ich wieder Schulgottesdienste aufgerufen. Als erstes wurde das verbesserte Material angezeigt, dann kam die Klimakollekte (why ever) und die Themenseite auf allen fünf angezeigten Seiten gar nicht mehr. Ich habs noch zweimal probiert, es blieb so.

**Comment by staude** [comment]
>Dann habe ich die Themenseite aufgerufen und dort einen Fehler festgestellt. Ich habe den Fehler verbessert. Dann habe ich wieder Schulgottesdienste aufgerufen. 
>Als erstes wurde das verbesserte Material angezeigt

Dann war das doch die Themenseite

>Klimakollekte (why ever) 

Links / Vorbereitung -> schulgottesdieste.. Kommt halt im Inhalt vor.

>e Themenseite auf allen fünf angezeigten Seiten gar nicht mehr. Ich habs noch zweimal probiert, es blieb so.

??? Sorry, ich versteh es nicht.
