### ISSUE TITLE
Spezial-Problem bei der Anzeige

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#321]
Specials werden gelb angezeigt und damit hervorgehoben. Aber wie wir in der Besprechung bereits beredet haben, gibt es wirkliche Specials und Specials, die nur entwickelt wurden, um Materialien eingeben und mit einer rpi-Adresse anlegen zu können. Diese Seiten sind ganz normales Material, nichts hervorhebenswertes. Aber sie werden natürlich auch gelb hervorgehoben. Wie könnte man das anders lösen?

Beispiel: https://material.rpi-virtuell.de/material/themen-des-buddhismus-beim-deutschlandfunk/

**Comment by staude** [comment]
is_special prüft aktuell auf das "ist ein special", muss geändert werden das die Überprüfung auf den Medientyp vorgenommen wird. 
heisst aber auch, das sich die ID und/oder der Name des Medientyps nicht ändern darf.
Alternativ lassen wir die Specials wie sie sind und führen einen Typ "lokales Material" ein.

Bedarf Diskusison  @lehr-ruetsche @johappel @empeiria

**Comment by lehr-ruetsche** [comment]
ja, sollte auf die Besprechungsliste.
