### ISSUE TITLE
suche im alten Material ignoriert Schlagworte

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#322]
https://material.rpi-virtuell.de/archiv/?fwp_suche=Märchen. liefert keinen Treffer auf https://material.rpi-virtuell.de/knusper-knusper-knaeuschen/

**Comment by empeiria** [comment]
Naja, der Treffer liefert nicht "Sexualität" sondern deren Erwachen bei "Dornröschen", das ist doch richtig!
Und dein "knusper-knusper-knaeuschen" @staude ist kein Material sondern ein Beitrag! :-)

**Comment by empeiria** [comment]
...achso das ist unkonvertiertes Material, das irgendwie anders gesucht wird. sorry - ich nehme alles zurück ;-)

**Comment by staude** [comment]
Der Beitrag ist altes Material und er hat das Schlagwort Märchen und müsste daher in der liste erscheinen

**Comment by staude** [comment]
Schlagworte bei alten Material sind nur als Interims Schlagwort gespeichert, Habe die Suche geändert das diese mit gefunden werden. Suchindex wird gerade neu erstellt.
