### ISSUE TITLE
Material vorschlagen - Formular bleibt ausgefüllt | wpadmin veröffentlicht automatisch

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#323]
**Alles ohne Anmeldung:**
Nach Eintrag von URL und Beschreibung und dem Drücken von "Vorschlagen" bleibt alles im Formular stehen und darunter erscheint:
"Vielen Dank für ihren Vorschlag. Ihr Materialvorschlag wird nun Redaktionell geprüft."
![image](https://user-images.githubusercontent.com/1091954/28658851-7095a41a-72ad-11e7-8f5b-11c17d72d881.png)
Das irritiert zum Einen - zum Anderen: Wenn man nun nochmal auf "Vorschlagen" klickt, weil man denkt, dass es nicht geklappt hat erscheint Folgendes:
"Vielen Dank für ihren Vorschlag. Das Material befindet sich bereits im Materialpool."
![image](https://user-images.githubusercontent.com/1091954/28658942-d4cae6ca-72ad-11e7-9c19-86990716276a.png)
Und tatsächlich, das Material welches unangemeldet eingetragen wurde ist automatisch durch wpadmin veröffentlicht worden:
https://material.rpi-virtuell.de/material/die-prinzessin-auf-de-erbse-starke-verben/

**Comment by staude** [comment]
Formular sollte sich eigentlich leeren, ja. 
Veröffentlich ist es nicht, es ist im Status "Vorschlag", taucht damit auch nicht in den Listen oder der suche auf, aber ja, man kann es Aufrufen, wenn man die URL kennt.
