### ISSUE TITLE
Facettierte Suche in der Bildungsstufe

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#324]
Folgendes habe ich eben gemacht:
Im Materialpool "Reformation" eingegeben
Dann "Unterrichtsentwürfe" eingegeben
Dann "Sek. I" eingegeben, es tauchten 24 Treffer auch
Dann habe ich noch "Oberstuf"e ergänzt, jetzt hätten es ja mehr Treffer sein müssen, aber jetzt werden nur noch 11 Treffer angegeben. Kann eigentlich nicht sein, oder?

Jetzt habe ich mal nur "Oberstufe" angehakt, da waren es 13 Treffer.

**Comment by johappel** [comment]
In deinem Fall müssen folgende Kriterien erfüllt sein:
**Materialien zum Suchwort Reformation die
sowohl für Oberstufe als auch für Sek1 geeignet sind.**

Der Filter wirkt ausschließlich eingrenzend. Je mehr Filter du anklickts, desto weniger Ergebnisse gibt es.

Also alles korrekt.
