### ISSUE TITLE
Doppeltes Material

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#326]
Diese Adresse wurde gerade konvertiert:

https://material.rpi-virtuell.de/wp-admin/post.php?post=16610&action=edit

Weitergeleitet wird zu:

http://www.lutherpedia.de/hingehen/luther-360-grad

Mir kam es bekannt vor. Dieses Material war schon da:

https://material.rpi-virtuell.de/material/luther-360-2/

Das ist die Verlinkung:

http://www.lutherpedia.de/hingehen/luther-360-grad

Hätte das nicht angezeigt werden müssen?

**Comment by staude** [comment]
Nein, denn das  der Eintrag
https://material.rpi-virtuell.de/material/luther-360/
zeigt auf die Material URL http://blogs.rpi-virtuell.de/reformation/2017/01/04/luther-360/
wo hingehen der Eintrag von
https://material.rpi-virtuell.de/material/luther-360-2/
auf die Material URL http://www.lutherpedia.de/hingehen/luther-360-grad zeigt.
