### ISSUE TITLE
Für Frank: Auch hier wurde der Bindestrich zum Fragezeichen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#329]
![bindestrich fragezeichen](https://user-images.githubusercontent.com/17722241/28818644-fd69dcc4-76ab-11e7-8772-ba6b24339d7f.png)

https://explizitnet.wordpress.com/2017/07/22/islam-religion-oder-konfession/

**Comment by retinasilk** [comment]
Dieser Bindestrich ist ein Halbgeviertstrich https://de.wikipedia.org/wiki/Halbgeviertstrich Auf Windows-PC ist das mit ALT+0150 (Nummernblock) einzugeben.
