### ISSUE TITLE
Was machen wir mit unseren ganzen Daten, wenn sie veraltet sind?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#33]
Schon zu Andreas Ziemer wird es in einem Jahr nicht mehr stimmen.

**Comment by staude** [comment]
Jein. Das Material das bis dahin von Andreas erfasst ist ändert sich ja nicht, auch die Orga Zugehörigkeit der Materials verändert sich nicht. Er ist dann halt einer neuen (weiteren) Organisation zugehörig.

**Comment by lehrruetsche** [comment]
Ja, wir werden eine Menge an Autoren haben, das werden wir irgendwann nicht mehr bewältigen.
