### ISSUE TITLE
Zählung stimmt nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#331]
Heute habe ich im Materialpool 29 Einträge gemacht. Außerdem habe ich 11 Einträge gelöscht, die vermutlich auch angezeigt werden. Macht insgesamt 40 Einträge.
Angezeigt werden für den 1. August 83 Einträge.

**Comment by lehr-ruetsche** [comment]
Heute, 2. August, habe ich mal sorgfältig darauf geachtet, wie gezählt wird: es werden gezählt alle Neueinträge, alle Konvertierungen, alle Löschungen und Änderungen in den Adresszeilen. Trotzdem und bei allem kann ich am 1. August, nicht 83 Einträge gemacht haben. Es kommen wenige Adressänderungen vor. Und alles andere kann man online nachzählen. Heute hatte ich den Eindruck, die Zählung stimmt einigermaßen.

**Comment by staude** [comment]
Fehler in der Datumsberechnunung, der letzte Tag des Vormonats wurde mit reingerechnet.
