### ISSUE TITLE
Schlagwort Problem: Josef, von Nazareth

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#334]
Folgendes Problem ist aufgetaucht: Ich habe von den Bibliotheksdamen gelernt, dass es bei schwierigen Namen wie Josef, der allein in der Bibel mehrmals vorkommt, Zusätze gibt. Diese Zusätze werden mit einem Komma verbunden. Also: Josef, von Nazaret  oder Josef, Patriarch.

Nun aktzeptiert das System einfach nicht "Josef, von Nazareth". Es sagt immer: ein solcher Begriff sei in der Taxonomie schon vorhanden.

https://material.rpi-virtuell.de/wp-admin/post.php?post=17297&action=edit

Einfach selbst mal ausprobieren. Ich habe es auf verschiedenen Wegen viermal probiert, ging nicht.
Josef, Patriarch klappt übringes auch nicht.

**Comment by johappel** [comment]
Kommata trennen zwischen den einzelnen Tags in Wordpress und sind deshalb innerhalb einer Zeichenkette nicht nutzbar

**Comment by staude** [comment]
Direkt im Backend auf https://material.rpi-virtuell.de/wp-admin/edit-tags.php?taxonomy=schlagwort kann man die sehrwohl mit Komma eintragen. Habe gerade mal den "Josef, von Nazaret"  eingetragen und dem genannten Material zugeordnet.

**Comment by johappel** [comment]
@staude Stimmt. Allerdings ist der Weg über das Backend je eher ein nicht so ergonomisches Verfahren. 
Denkbar wäre ja auch, das Komma einfach wegzulassen, Oder was spricht dagegen?

**Comment by staude** [comment]
Von meiner Seite aus nichts.

**Comment by lehr-ruetsche** [comment]
Ich habe jetzt mal folgendes versucht und direkt bei den Schlagworten: Josef (Erzvater) eingegeben und geschaut, ob es auch gefunden wird. Das mit der Klammer wird tatsächlich auch akzeptiert. Da ich das mit dem Komma schwierig finde: Josef, von Nazareth würde ich die Klammer vorschlagen oder ein direktes Anhängen. Ich könnte mir vorstellen, dass das direkte Anhängen u.U. auch mal seltsame Wirkung zeigt und von daher fände ich die Klammer nicht schlecht. Mir würde es nichts ausmachen, das bei den Schlagworten direkt anzulegen, denn das scheint ja gut zu funktionieren.

**Comment by staude** [comment]
ok, dann mit (), wie besprochen
