### ISSUE TITLE
Schlagworte und gleiche Namen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#335]
Ich weiß nicht, ob es dafür eine technische Lösung gibt, aber es ist schon nervig, dass, wenn man Josef eingibt, Themen wie Abendmahl erscheinen, weil einer der Autoren Josef Fath heißt (zum Beispiel). Das war früher so und ist jetzt wieder so und bei allen Namen ein Problem.

**Comment by staude** [comment]
dann sucht man nach josef und filtert über die Facetten weiter nach dem Schlagwort 
wo ist jetzt das Problem?

**Comment by staude** [comment]
<img width="1319" alt="2017-08-24_0939" src="https://user-images.githubusercontent.com/870951/29655202-77ed0a8c-88b0-11e7-8895-299f65b76cb2.png">

**Comment by lehr-ruetsche** [comment]
Das Problem liegt darin, dass ich angehalten wurde, mich an die Regeln des BSZ zu halten und ich dies Frage nach Personen wie Karl V. usw. mit den Bibliothekarinnen des CI besprochen habe.

Die Vorgaben des BSZ lassen sich nicht mit Wordpress in Einstimmung bringen.

Das habe ich rückgemeldet. Joachim hat geschrieben, dass es dafür keine Lösung gibt und damit ist die Sache geklärt. Jetzt steht halt Josef drin und man muss dann selbst rausfinden, welcher Josef das denn sein könnte. Josef von Arimathia, Josef von Nazareth, Josef und seine Brüder, Josef Goebbels oder Josef Fath.

Dazu gäbe es Lösungen, aber eben nicht bei wordpress.

Damit ist für mich das Thema geklärt. Kommentare wie „Wo ist das Problem?“ die ich mit „stell dich nicht so blöd an“  übersetze, sind nicht wirklich motivierend.

 

Von: Frank Staude [mailto:notifications@github.com] 
Gesendet: Donnerstag, 24. August 2017 09:31
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Schlagworte und gleiche Namen (#335)

 

dann sucht man nach josef und filtert über die Facetten weiter nach dem Schlagwort
wo ist jetzt das Problem?

**Comment by staude** [comment]
?? ich glaube das du da zwei tickets miteinander vermischt. 

Ich habe einen Vorschlag gemacht wie das Vorgehen ist und gefragt ob es dran ein Problem gibt.

EIne Gedankenlesende Suche haben wir nicht, die weiss nach was für einen Josef gesucht ist

Wir haben eine Volltextsuche, die alle Josef findet. Und wir haben Facetten um das Suchergebnis weiter zu filtern und einzuschränken

**Comment by staude** [comment]
Und wenn ich frage "wo ist das Problem" ist das auch genau so gemeint, weil sich MIR dann auf dem ersten Blick nicht erschliesst.
