### ISSUE TITLE
Bilder löschen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#337]
In den News gibt es ein Bild zur diesjährigen Didacta. Was immer da war und welche Rechte gelten - das Bild könnte einfach gelöscht werden. Wenn ich nur wüsste wie.

**Comment by staude** [comment]
>Was immer da war und welche Rechte gelten
????

Ein Link wäre schon Hilfreich. Welches Bild?

>Bild könnte einfach gelöscht werden. Wenn ich nur wüsste wie.

Mediathek, Bild anklicken , unten löschen - oder geht das nicht? Kommt eine Fehlermeldung?
<img width="1628" alt="2017-09-06_0921" src="https://user-images.githubusercontent.com/870951/30099098-dbc806cc-92e4-11e7-827a-151e70dc52c6.png">

**Comment by lehr-ruetsche** [comment]
https://news.rpi-virtuell.de/wp-admin/media.php?attachment_id=20364&action=edit

**Comment by lehr-ruetsche** [comment]
Es ist ein Problem, das immer wieder auftaucht: Bei den fehlenden Bildquellen könnten Bilder gelöscht werden, die gar nicht mehr gebraucht werden, wie zum Beispiel das zum Cafe Bildung. Das war eine hausinterne Regelung, das ich das Bild verwendet habe, weil es sozusagen "aus meinem eigenen Laden" war. Aber jetzt könnte man es auch einfach löschen, die Didacta ist vorbei, das Cafe Bildung ist vorbei. Und ich weiß nicht, wie man aus der Liste Fehlende Bildquellen etwas löschen kann.

**Comment by staude** [comment]
Über den Link in der Liste der Bildquellen geht das nicht. Dazu Bitte in die Mediathek wechseln 
und nach dem Namen suchen

<img width="1628" alt="2017-09-06_0929" src="https://user-images.githubusercontent.com/870951/30099532-42ce9506-92e6-11e7-8d57-3ed983e83eab.png">

dann anklicken und da dann löschen

<img width="1628" alt="2017-09-06_0929b" src="https://user-images.githubusercontent.com/870951/30099542-4dd8c552-92e6-11e7-917a-b1d642bce984.png">

Die genannte Datei hab ich mal gelöscht.
