### ISSUE TITLE
"Zuschalten weiterer Facetten"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#338]
Eben habe ich zu "Luther" - Grundschule - Medien Materialien gesucht. Es wurden einige wenige angezeigt. Ich wollte die Sek. I noch dazunehmen, aber das funktionierte nicht. Es wurden weiterhin nur 6 angezeigt. Bei einem Neuaufbau der Suche kam ich auf 17 Treffer.

**Comment by staude** [comment]
Was genau ist die frage oder der Fehler?

Suche nach Luther -> 198 Treffer
![2017-09-06_1523](https://user-images.githubusercontent.com/870951/30114171-514791b0-9317-11e7-8013-99417e071939.png)

Facette Grundschule -> 54 Treffer
![2017-09-06_1523b](https://user-images.githubusercontent.com/870951/30114200-6c1993b2-9317-11e7-802b-5917ed96cd95.png)

Facette Medien dazu -> 19 Treffer
![2017-09-06_1524](https://user-images.githubusercontent.com/870951/30114230-832a9920-9317-11e7-82f8-00beeff53db3.png)

Facette Sek1 dazu -> 17 Treffer
![2017-09-06_1525](https://user-images.githubusercontent.com/870951/30114268-9bbcd5de-9317-11e7-8603-d8e01c9a71e3.png)


Alles wie erwartet. Wollen wir kurz gemeinsam draufschauen per Bildschirmfreigabe?

**Comment by lehr-ruetsche** [comment]
Nunja, wenn ich zuerst nur 6 Treffer für Luther - Grundschule - Medien habe und dann zusätzlich noch die Sekundarstufe anhake, müssten ja mehr Treffer kommen. Aber kamen nicht. Auch nicht bei einem Reload. Beim Neuaufbau des Ganzen kamen 17 Treffer.

**Comment by lehr-ruetsche** [comment]
Die Frage ist: kann ich noch etwas weiteres Anhaken und dann verändert sich die Anzahl der Treffer? Oder muss ich immer neu aufbauen.

**Comment by staude** [comment]
du kannst immer weiter einschränken durch weiteres anhaken. 

Aber Luther - Grundschule - Medien muss 19 Treffer liefern

Welchen Browser nutzt du ?

**Comment by lehr-ruetsche** [comment]
In dem Fall wollte ich ja nicht einschränken, sondern erweitern.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. September 2017 15:31
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] "Zuschalten weiterer Facetten" (#338)

 

du kannst immer weiter einschränken durch weiteres anhaken.

Aber Luther - Grundschule - Medien muss 19 Treffer liefern

Welchen Browser nutzt du ?

**Comment by staude** [comment]
Das sind aber UND Bedingungen.

**Comment by lehr-ruetsche** [comment]
okay
