### ISSUE TITLE
Lernorte

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#339]
Eben habe ich Luther - Lernorte gesucht. Es gab geografische und virtuelle. Ich habe zuerst nur die geografischen angehakt. Die habe ich mir durch gesehen. Dann dachte ich, jetzt schaue ich mir doch auch noch die virutellen an, aber die wurden jetzt gar nicht mehr angezeigt! Die Möglichkeit des Anhakens war sozusagen verschwunden.
https://material.rpi-virtuell.de/facettierte-suche/?fwp_medientyp=real-place&fwp_suche=Luther

Ich weiß nicht, ob man das hier sieht auf diesem Link.

**Comment by staude** [comment]
Facetten sind immer UND. Man schränkt die Auswahl immer weiter ein und bekommt nur weitere Facetten angezeigt, die noch Treffer liefern, um zu verhindern das der User eine Suche hat, die 0 Treffer liefert,

Es wird wohl keine Lernorte geben die beides sind :-)

**Comment by lehr-ruetsche** [comment]
Ja, aber ich könnte bei Themenseiten unter Lernorte durchaus beides angeben.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. September 2017 15:35
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Lernorte (#339)

 

Facetten sind immer UND. Man schränkt die Auswahl immer weiter ein und bekommt nur weitere Facetten angezeigt, die noch Treffer liefern, um zu verhindern das der User eine Suche hat, die 0 Treffer liefert,

Es wird wohl keine Lernorte geben die beides sind :-)

**Comment by staude** [comment]
Aber Themenseiten haben nichts mit Facetten zu tun - bin verwirrt.
