### ISSUE TITLE
Jeweils ein Teil fehlt

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#34]
Vermutlich ist das technisch nicht anders lösbar: aber trage ich zuerst den Autor ein, fehlen mir unten Organisation und Material. Trage ich zuerst die Organisation ein, fehlen mir der Autor und das Material, trage ich zuerst das Material ein, fehlen mir unten der Autor und die Organisation. Und jeweils muss ich das andere nochmals aufmachen, um das fehlende nachzutragen. Umständlich und aufwändig.

**Comment by staude** [comment]
Siehe #1
