### ISSUE TITLE
Mediathek bei den Materialien

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#341]
Ich glaube, ich habe es schon mal eingebracht: bei den Materialien wird mit Bildern ganz anders umgegangen als mit News. Warum kann es nicht das gleiche Tool sein, wenn schon ein gemeinsames nciht geht. Man kann auch nicht zum Beispiel auf "Fehlende Bildquellen" klicken. Die Bilder bei den Materialien stehen eigentlich viel länger online und sind daher eher "gefährlicher".

**Comment by staude** [comment]
Was meinst du genau? Material hat kaum eigene Medien. 
geht es nur um das Bildquellen Plugin oder was genau ?

**Comment by lehr-ruetsche** [comment]
Ja, es geht um die Bildquellen. Bei den News war das ganz wichtig, dass das alles supergenau eingegeben wird. Bei den Materialien könnte man doch genau das gleiche Tool verwenden, oder nicht? Das dortige Tool ist viel ungenauer und doch stehen die Bilder dort viel länger.

**Comment by staude** [comment]
>Das dortige Tool ist viel ungenauer und doch stehen die Bilder dort viel länger.

macht was anderes, weil wir die Bilder in der Regel nicht kopieren und sie daher auch nicht in der Mediathek stehen.

-> Diskussionsrunde

**Comment by lehr-ruetsche** [comment]
bei den Themenseiten zum Beispiel kopieren wir schon und wenn die Sache mit dem Screenshot nicht funktioniert

**Comment by lehr-ruetsche** [comment]
Jetzt erscheint Erntedank bei der Materialsuche gar nicht mehr :-(
