### ISSUE TITLE
Schlagwort wird im Suchfeld nicht gefunden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#342]
Das Wort Konfession existiert im Schlagwortregister sowohl in Einzahl als auch im Plural. Das wollte ich ändern, aber als ich in das Suchfeld "Konfession" eingab, erschien nur eine graue Seite.
Bei dem Wort "Abbild" klappte alles tadellos. Jörg hat die Gegenkontrolle gemacht, bei ihm ist es genauso. Ein seltsames Phänomen.

**Comment by staude** [comment]
Das Suchfeld im backend in der Schlagwortliste meinst du?

**Comment by lehr-ruetsche** [comment]
Ja

 

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. September 2017 16:26
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Schlagwort wird im Suchfeld nicht gefunden (#342)

 

Das Suchfeld im backend in der Schlagwortliste meinst du?

**Comment by lehrruetsche** [comment]
Ja

Am 19.09.2017 16:29 schrieb "lehr-ruetsche" <notifications@github.com>:

**Comment by staude** [comment]
Tritt nur auf wenn man den Suchbutton anklickt, wenn man im Feld direkt einfach return drückt geht es.

**Comment by staude** [comment]
Tritt bei allen Taxonomiesuchen auf. "Konfession" führt zu einen weißen Screen, "Konfessio" liefert entsprechende Ergebnisse.

Auch bei Konfession sind die Ergebnisse kurz sichtbar, dann meldet die Konsole aber einen JS Fehler.

[Error] TypeError: undefined is not an object (evaluating 'a("#the-list").attr("data-wp-lists").substr')
	init (load-scripts.php:7:164)
	(anonyme Funktion) (load-scripts.php:7:2733)
	i (load-scripts.php:2:27455)
	fireWith (load-scripts.php:2:28215)
	ready (load-scripts.php:2:30018)
	K (load-scripts.php:2:30374)
