### ISSUE TITLE
Abstände eingeben ist schwierig - Textfeld

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#343]
https://material.rpi-virtuell.de/material/maria-eine-besondere-frau/

Es ist mir nicht das erste Mal passiert, dass ich mit Abständen eingeben meine Schwierigkeiten habe. 

Ich wollte das Zusatzmaterial mit einem Abstand zum Text eingeben und habe das im Backend auch so gemacht. Aber egal, wie viel Abstand ich eingebe, es klebt am Text. Was kann ich da machen?

Auch hier:

https://material.rpi-virtuell.de/wp-admin/post.php?post=17517&action=edit

Wobei ich sagen muss, ich habe die Links reinkopiert.

**Comment by staude** [comment]
Hmmm Seit wann generiert den Editor denn keine P Tags mehr sondern wirft alles in Divs?

**Comment by staude** [comment]
Durch copy und paste war alles in divs eingefasst.
Divs entfernt, p Tags eingesetzt.
