### ISSUE TITLE
Bilder beschriften (News)

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#344]
Ich hätte gerne zu einem Bild in den News eine ausführlichere Beschreibung gemacht, die man auch im Frontend lesen kann. Ich habe etwas in "Beschriftung" eingetragen, ich habe etwas in "Beschreibung" eingetragen, aber im Frontend erscheint nichts von beidem. Ist das normal?

**Comment by empeiria** [comment]
URL @lehr-ruetsche

**Comment by staude** [comment]
ping @lehr-ruetsche

**Comment by lehr-ruetsche** [comment]
Das ist jetzt natürlich schon ewig her und eigentlich auch ein grundlegendes Problem bei den News. Konkret ging es um dieses Bild:
https://news.rpi-virtuell.de/2017/09/18/reckahner-reflexionen-zur-ethik-paedagogischer-beziehungen/
Dazu gab es eine etwas längere Beschreibung.

**Comment by johappel** [comment]
Das lässt sich in dem Fall nur Per Hand im Text eintragen.  Haben wir denn die Rechte für das Bild?
