### ISSUE TITLE
Themenseiten bei "Besonderer Tipp"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#345]
Leider kann ich bei den "Besonderen Tipps" auf der Startseite die Themenseiten nicht aufnehmen. Oder geht es, und ich weiß nur nicht wie?

**Comment by staude** [comment]
Ja, es gibt direkt unter der Materialauswahl eine Auswahl für Themenseiten

<img width="923" alt="2017-11-10_1948" src="https://user-images.githubusercontent.com/870951/32673663-4c77f67c-c650-11e7-903b-1d72c0b2db2d.png">
