### ISSUE TITLE
Link anzeigen im Vorschlagspool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#346]
Wenn ich Material aus dem alten in den neuen Materialpool konvertiere, kann ich sofort den neuen Link ansteuern und nachschauen, ob das Material wirklich was taugt.
Wenn ich neue Vorschläge von Eintragern aufrufe, funktioniert das nicht. Da kommt immer eine Fehlermeldung. Lässt sich daran was ändern oder ist das halt einfach so?

**Comment by staude** [comment]
das Konvertierte Material ist auch Publiziert. Vorschläge sind nicht publiziert (dann wären es ja keine Vorschläge mehr)

**Comment by lehr-ruetsche** [comment]
Okay
