### ISSUE TITLE
PTZ Stuttgart taucht nicht auf bei der Organisationseingabe

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#35]
Ich wollte das PTZ eingeben, dachte mir aber, es müsste schon drin sein. Angezeigt wurde es mir aber bei den Organisationen nicht. Dann habe ich die Organisationseinträge insgesamt geöffnet und dort war das PTZ sehr wohl zu finden. Auch genau unter dem Namen. Andere Einträge wie PTI wurden mir angeboten, aber das PTZ nicht.
Bei den Materialien ist es aufgetaucht.

**Comment by staude** [comment]
Ich versteh nicht was du meinst.

Sowohl beim Autor als auch beim Material in dem Dialog taucht das auf.

![2016-11-14_2117](https://cloud.githubusercontent.com/assets/870951/20281280/2d24319e-aab0-11e6-9c3d-6f6650ea38f0.png)
![2016-11-14_2116](https://cloud.githubusercontent.com/assets/870951/20281281/2d43c00e-aab0-11e6-9b49-e9878563e4eb.png)

**Comment by lehrruetsche** [comment]
Es war so, dass ich beginnen wollte zu schreiben. Normalerweise müsste nach dem Eintippen des P sofort ein Angebot kommen. Aber es kam nur das PTI, obwohl das PTZ unter den Organisationen bereits eingetragen war.
