### ISSUE TITLE
Viewer funktioniert - Download nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#350]
Das ist mal ein interessantes Phänomen: Im Viewer ist der Artikal da, aber unter Material herunterladen kommt man auf eine 404-Seite. Wie geht das? Ich habe natürlich immer angenommen, was ich im Viewer sehen kann ist auch da. 

https://material.rpi-virtuell.de/material/zwischen-gottes-krieg-und-feindesliebe/

**Comment by johappel** [comment]
Das Problem liegt an der Adress des PDF
https://www.uni-due.de/unikate/ressourcen/grafiken/PDF's/21/21-schart.pdf
@staude  die URL müsste wohl escaped werden, oder?
