### ISSUE TITLE
zum Thema Blogs - Blog wird nicht gefunden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#351]
Habe eben an einem Blog gearbeitet. Bis zur Vorschau war alles okay:

http://blogs.rpi-virtuell.de/klassenblog/wp-admin/post.php?post=48&action=edit

Dann habe ich gespeichert und weg war er:

http://blogs.rpi-virtuell.de/klassenblog/2017/10/02/sondergruppen-und-sekten/?preview_id=48&preview_nonce=b5c8b4b871&post_format=standard&_thumbnail_id=-1

Was ist schief gelaufen?

**Comment by empeiria** [comment]
Der Artikel ist dieser hier, oder @lehr-ruetsche ?:
http://blogs.rpi-virtuell.de/klassenblog/2017/10/02/sondergruppen-und-sekten/

**Comment by lehr-ruetsche** [comment]
ja
jetzt ist er aufzufinden, vorher trotz Reload nicht...

**Comment by johappel** [comment]
ich vermute, dass es daran lag, dass es der Vorschaulink war:
http://blogs.rpi-virtuell.de/klassenblog/2017/10/02/sondergruppen-und-sekten/?preview_id=48&preview_nonce=b5c8b4b871&post_format=standard&_thumbnail_id=-1

**Comment by lehr-ruetsche** [comment]
Okay

 

 

Von: Joachim Happel [mailto:notifications@github.com] 
Gesendet: Montag, 2. Oktober 2017 15:54
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] zum Thema Blogs - Blog wird nicht gefunden (#351)

 

ich vermute, dass es daran lag, dass es der Vorschaulink war:
http://blogs.rpi-virtuell.de/klassenblog/2017/10/02/sondergruppen-und-sekten/?preview_id=48 <http://blogs.rpi-virtuell.de/klassenblog/2017/10/02/sondergruppen-und-sekten/?preview_id=48&preview_nonce=b5c8b4b871&post_format=standard&_thumbnail_id=-1> &preview_nonce=b5c8b4b871&post_format=standard&_thumbnail_id=-1
