### ISSUE TITLE
Interimsautoren zu "richtigen Autoren" machen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#352]
Ich bin eben auf einen Artikel von Elisabeth Reil gestoßen. Ich dachte, sie kommt nicht so häufig vor und wollte sie als Interims-Autorin anlegen. Ihr Name wurde sofort erkannt, sie muss also schon mal vorgekommen sein. Ich kann sie aber nirgends finden. Ich habe sie jetzt angelegt und hätte gern das frühere Material von ihr "umgeschrieben", so dass ihr Bild erscheint usw.
Ich finde aber leider nichts. Gibt es da Möglichkeiten?

**Comment by empeiria** [comment]
https://material.rpi-virtuell.de/wp-admin/post.php?post=16311&action=edit
Da hattest du sie als Interim eingegeben. Einfach auf Autor ändern, oder? @lehr-ruetsche

**Comment by staude** [comment]
@lehr-ruetsche was heisst "Ihr Name wurde sofort erkannt"? Wo wurde er erkannt? Kann auch einfach von deinem Browser kommen, der Vorschlag weil du den Namen ja schon mal eingegeben hast.

**Comment by johappel** [comment]
Wäre es denkbar, dass Autoren in den interimsfeldern automatisch nach eingetragenen Autoren  suchen, und die Zuordnung machen, wenn fündig?

**Comment by lehr-ruetsche** [comment]
Wie hast du sie gefunden? Ich habe sie nicht gefunden!

 

Von: Jörg Lohrer [mailto:notifications@github.com] 
Gesendet: Freitag, 6. Oktober 2017 09:18
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Interimsautoren zu "richtigen Autoren" machen (#352)

 

https://material.rpi-virtuell.de/wp-admin/post.php?post=16311 <https://material.rpi-virtuell.de/wp-admin/post.php?post=16311&action=edit> &action=edit
Da hattest du sie als Interim eingegeben. Einfach auf Autor ändern, oder? @lehr-ruetsche <https://github.com/lehr-ruetsche>

**Comment by lehr-ruetsche** [comment]
Der Name wurde sofort erkannt, als ich begonnen habe, ihn ins Interimsfeld zu schreiben. Dann habe ich versucht, herauszufinden, was sie bei uns noch geschrieben hat. Aber ich habe sie nicht gefunden. Jörg schon. Aber wie?

 

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Freitag, 6. Oktober 2017 09:30
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Interimsautoren zu "richtigen Autoren" machen (#352)

 

@lehr-ruetsche <https://github.com/lehr-ruetsche>  was heisst "Ihr Name wurde sofort erkannt"? Wo wurde er erkannt? Kann auch einfach von deinem Browser kommen, der Vorschlag weil du den Namen ja schon mal eingegeben hast.

**Comment by empeiria** [comment]
Ich habe im Dashboard bei Materialpool - Materialien in die Suche "Elisabeth Reil" eingegeben:
![image](https://user-images.githubusercontent.com/1091954/31271440-cd317eda-aa87-11e7-86e9-3492d541d40a.png)
Dann kamen alle Treffer, bei denen Sie Interim oder eben vollwertige Autorin ist

**Comment by lehr-ruetsche** [comment]
Ah, cool, ich habe nur auf der Frontseite im Materialpool gesucht, war natürlich cleverer, im Backend zu suchen.

 

Von: Jörg Lohrer [mailto:notifications@github.com] 
Gesendet: Freitag, 6. Oktober 2017 11:17
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Interimsautoren zu "richtigen Autoren" machen (#352)

 

Ich habe im Dashboard bei Materialpool - Materialien in die Suche "Elisabeth Reil" eingegeben:
 <https://user-images.githubusercontent.com/1091954/31271440-cd317eda-aa87-11e7-86e9-3492d541d40a.png> 
Dann kamen alle Treffer, bei denen Sie Interim oder eben vollwertige Autorin ist
