### ISSUE TITLE
Foto vom Special wird auf der Seite des Special nicht angezeigt

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#353]
In der Materialsuche wird das Bild dazu angezeigt:
![image](https://user-images.githubusercontent.com/1091954/31490575-b2a7aa32-af44-11e7-928b-761591cb87bf.png)
Auf der Materialseite selbst dann jedoch nicht:

https://material.rpi-virtuell.de/material/interreligioeser-obstsalat/

**Comment by staude** [comment]
Ja, in dem Template das Spezials ausgibt wird das nicht mit ausgeben. Soll das jetzt für alle Specials geändert werden? @johappel @empeiria @lehrruetsche

**Comment by johappel** [comment]
Gibt es eine Grund, warum es auf der Seite selbst nicht ausgegeben werden sollte?
Vielleicht weil man ein eigenes Bild dort verwendet?
