### ISSUE TITLE
Lizenzierung wird nicht angezeigt

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#354]
Bei  https://material.rpi-virtuell.de/material/interreligioeser-obstsalat/ habe ich angegeben, dass es zur Wiederverwendung und Veränderung gekennzeichnet wurde.
Weder auf der Übersichtsseite noch beim Material selbst ist jedoch die Lizenz ersichtlich.
Hinzu kommt die Frage, wie eine CC-Lizenz erfasst werden sollte - im Volltext oder via checkbox? Als Metadaten?

**Comment by staude** [comment]
Bei den Lizenzen haben wir damals lang und breit diskutiert und das Ergebnis war, das wir die genaue Bezeichnung nicht angeben wollen sondern nur die Umschreibung wie sie jetzt in der Lizenztaxonomie zur Auswahl stehen.
Diese werde ich noch bei den Metadaten mit Ausgeben.
