### ISSUE TITLE
Themenseiten: Zahlen der Facetteierten Materialien sind Fehlerhaft

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-materialpool#359]
solange man nicht aktiv eine facette ausgesucht hatte werden die Zahlen aller Materialien der entsprechenden Facette angezeigt:

![grafik](https://user-images.githubusercontent.com/307023/31882016-c0eb7250-b7e5-11e7-8531-f8a1c371ef12.png)

**Comment by staude** [comment]
da bricht das JS ab, die Bereiche sind auch nicht zugeklappt- Interessanterweise bekomme ich aber keinen JS Fehler

**Comment by johappel** [comment]
kommt evtl. eine ajax Abfrage in die Quere?
