### ISSUE TITLE
Bild der EKBO erscheint nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#361]
Bei der Organisation der EKBO erscheint das Bild nicht, ich verstehe nicht ganz, warum:

https://material.rpi-virtuell.de/material/rahmenlehrplan-der-ekbo/

**Comment by staude** [comment]
welches fehlt?

<img width="547" alt="2017-10-27_1007" src="https://user-images.githubusercontent.com/870951/32094044-cfed72dc-bafe-11e7-98a6-241940c9178a.png">

**Comment by staude** [comment]
<img width="1733" alt="2017-11-08_1433" src="https://user-images.githubusercontent.com/870951/32551789-f4d45c86-c491-11e7-856d-9b918f34c405.png">

**Comment by staude** [comment]
Sowohl beim Material als auch bei der Organisation sehe ich da das Logo.
@lehr-ruetsche welches Bild so da wo fehlen?
