### ISSUE TITLE
Autoren und Organisationen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#362]
die Eintragsfelder für Autoren und Organisationen sind verschwunden. Es gibt nur noch die Interimsfelder!!! Bitte schnell gucken, dringend!
![autoren und organisationen](https://user-images.githubusercontent.com/17722241/32436289-d961a40e-c2e3-11e7-89c6-00cfbcb04866.png)

**Comment by johappel** [comment]
![image](https://user-images.githubusercontent.com/307023/32436359-1936893c-c2e4-11e7-95e5-37fb2b223c16.png)

**Comment by lehr-ruetsche** [comment]
Versuchst du es mal mit einem Neueintrag?

**Comment by johappel** [comment]
Bei mir wird alles nach wie vor korrekt angezeigt-
Vielleicht mal den Browser neu laden?
![image](https://user-images.githubusercontent.com/307023/32436418-50e60d80-c2e4-11e7-9bd2-ca8676c62094.png)

**Comment by beo9999** [comment]
Bei mir sah es eben beim ersten Aufruf auch so aus wie bei Andrea, Strg F5 hat aber geholfen.

**Comment by lehr-ruetsche** [comment]
Ich habe hochgefahren, das nützte nichts. F 5 nütze was.

**Comment by lehr-ruetsche** [comment]
War aber in zwei verschiedenen Browsern ein Problem.

**Comment by johappel** [comment]
Vielleicht ein Caching Problem?
