### ISSUE TITLE
Wechsel der Kernbereiche

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#363]
Ich versuchte eben vom Materialpool auf die News zu kommen über die "ausgefahrenen Schildchen", diese wurden angeboten, aber wenn ich News anklickte, passierte nichts.

**Comment by lehr-ruetsche** [comment]
In Chrome dasselbe.

**Comment by beo9999** [comment]
Problem ist bei mir auch vorhanden, auch blogs und news (oder irgendeiner der angezeigten Links) ist von https://material.rpi-virtuell.de aus über das "Ausfahrmenü" nicht errreichbar. (Bisher getestet: Chrome)

**Comment by staude** [comment]
Problem in Safari ebenfalls vorhanden

**Comment by johappel** [comment]
fixed mit 1.1.5
https://github.com/rpi-virtuell/rw-multiinstanz-navigation/releases/tag/1.1.5
