### ISSUE TITLE
Weiterleitung

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#367]
![suchfeld](https://user-images.githubusercontent.com/17722241/32773289-fe5bee5e-c928-11e7-86c9-ace5f48e84a0.png)
Ich habe eben in Google Schulgottesdienste zu Buß- und Bettag gesucht und landete bei einem Vorschlag für das alte rpi-virtuell. Ich habe es angeklickt und landete auf Fehler 404. Es gab aber ein Suchfeld, in den man seinen Begriff eintragen konnte. Ich habe also Schulgottesdienst eingetragen und das system meldete, dass es diesen Begriff leider nicht gäbe. Den es aber selbstverständlich gibt. Sucht nun dieser Suchschlitz im alten oder im neuen? Im alten rpi wäre es sinnlos und im neuen findet er das Wort nicht? Mir ist nicht ganz klar, was da abläuft.

**Comment by staude** [comment]
Der sucht weder im alten noch im neuen, weil du auf der about seite bist.

Eigentlich sollten material URL auf den Materialpool umleiten @johappel 

welche MaterialURL hattest du bei google gefunden @lehr-ruetsche

**Comment by lehr-ruetsche** [comment]
https://about.rpi-virtuell.de/memorylist/84F51D41-F6FC-42DF-ACD7-16A9A1E1EDC6

**Comment by lehr-ruetsche** [comment]
www.rpi-virtuell.net/tagpage/3D0C7242-1E1D-422F-82E8-B5DCABF6CAA6#!/CC/

**Comment by staude** [comment]
Das sind beides keine Materialien. Materialien gehen mit /material los
z.b. /material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD 

http://www.rpi-virtuell.net/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD  wird nur umgeleitet auf https://about.rpi-virtuell.de/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD das ist falsch - dort musste /material erkannt werden und an https://material.rpi-virtuell.de/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD umgeleitet werden @johappel 

Der Materialpool kann die alten Materal URLS auflösen, wenn das Material importiert wurde.
https://material.rpi-virtuell.de/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD wird korrekt zu https://material.rpi-virtuell.de/about-gender/

**Comment by johappel** [comment]
Stimmt das gab es im alten rpi-virtuell.
Das sind Listen von Materialien, die sich User zusammengesetellt hatten. Im neuen materialpool gibt es dafür keine Funktion:
![image](https://user-images.githubusercontent.com/307023/32776869-53ea65c0-c934-11e7-8655-f4d788eb702c.png)

**Comment by staude** [comment]
Die MATERIAL Weiterleitung funktioniert aber noch nicht.

**Comment by johappel** [comment]
Es sind ja auch nicht alle Metrialien übenommenworden

**Comment by staude** [comment]
http://www.rpi-virtuell.net/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD wird nur umgeleitet auf https://about.rpi-virtuell.de/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD das ist falsch - dort musste /material erkannt werden und an https://material.rpi-virtuell.de/material/8A79D21D-66FD-4E4B-895E-CA9D515C83FD umgeleitet werden

**Comment by johappel** [comment]
fixed
