### ISSUE TITLE
Themenseiten Doppelung

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#368]
Wenn man die Themenseite Erntedank aufruft, steht da Themenseite: Themenseite ERntedank.
Ich habe unter "Themenseiten" das Wort Themenseite aus dem Titel herausgenommen, und trotzdem steht immer noch das gleiche da, auch bei Mose. Bei Abraham habe ich nichts verändert und es steht auch zweimal da.
![themenseite abraham](https://user-images.githubusercontent.com/17722241/32775858-eedca628-c930-11e7-8d53-1d346f54696e.png)

Die neue Seite zu Buß- und Bettag, die ich heute erst gemacht habe, scheint richtig zu funktionieren.

**Comment by staude** [comment]
In der Suchergebnisliste wird vor Themenseiten automatisch ein "Themenseite:" vorgesetzt
Ist nur noch keinem aufgefallen, das du bei den meisten Themenseiten noch das Wort Themenseite in den Titel setzt, aber halt nicht bei allen. 

<img width="1749" alt="2017-11-14_1149" src="https://user-images.githubusercontent.com/870951/32776218-235b05d8-c932-11e7-905d-843015077a24.png">

Das Problem bei der Mischung ist, das die Alphabetische Sortierung  auf  https://material.rpi-virtuell.de/themenseiten/ nicht mehr funktioniert wenn mal mit und mal ohne Themenseite begonnen wird.

**Comment by lehr-ruetsche** [comment]
Ja, aber bei Erntedank hatte ich das Wort Themenseiten rausgenommen und es steht trotzdem noch da.
Ist das eine Sache der Dauer, bis es verschwindet?
Ich dachte, ich arbeite alles nach, d.h., nehme das Wort Themenseite raus, weil es ja jetzt automatisch eingefügt wird. Aber es verschwand nicht.

**Comment by lehr-ruetsche** [comment]
jetzt erscheint die Themenseite Erntedank unter der Materialsuche "Erntedank" gar nicht mehr :-(

**Comment by lehr-ruetsche** [comment]
Ja, deswegen wollte ich ja überall den Begriff Themenseiten rausnehmen.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. November 2017 11:53
An: rpi-virtuell/rw-materialpool <rw-materialpool@noreply.github.com>
Cc: lehr-ruetsche <lehr-ruetsche@comenius.de>; Author <author@noreply.github.com>
Betreff: Re: [rpi-virtuell/rw-materialpool] Themenseiten Doppelung (#368)

 

In der Suchergebnisliste wird vor Themenseiten automatisch ein "Themenseite:" vorgesetzt
Ist nur noch keinem aufgefallen, das du bei den meisten Themenseiten noch das Wort Themenseite in den Titel setzt, aber halt nicht bei allen.

 <https://user-images.githubusercontent.com/870951/32776218-235b05d8-c932-11e7-905d-843015077a24.png> 

Das Problem bei der Mischung ist, das die Alphabetische Sortierung auf https://material.rpi-virtuell.de/themenseiten/ nicht mehr funktioniert wenn mal mit und mal ohne Themenseite begonnen wird.

**Comment by staude** [comment]
Ah, beim speichern von Themenseiten wird der Eintrag in unserem Fragmentcache für das Sucheergebnis nicht verworfen. Ändere ich. 

Du kannst einfach weiter ändern

**Comment by staude** [comment]
Hab die restlichen Themenseiten gleich noch geändert.
