### ISSUE TITLE
Organisation Anzahl der Materialien

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#371]
Wenn man auf die Materialpoolseite geht und dort unter den Reitern auf "Einrichtungen" klickt, kommt als oberstes die Katholische Kirche im Kanton Luzern. Dort werden zwei Materialien angezeigt. Das ist richtig. Klickt man allerdings auf die Organisation, taucht nur ein Material auf. Oder braucht das einfach länger?

**Comment by staude** [comment]
Ist jetzt da. Kann schon sein, wenn es von der Suche/Facet noch nicht indexiert wurde taucht es in der Orgaseite noch nicht auf, während die Zahl in der Übersicht direkt in der Datenbank zusammengesucht wird.

<img width="1781" alt="2017-11-15_1441" src="https://user-images.githubusercontent.com/870951/32839091-87a45bde-ca13-11e7-9204-5e30905f0f1e.png">
