### ISSUE TITLE
'Entwürfe' im neuen Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#372]
Im Backend des neuen Materialpools tauchen oben "Entwürfe" auf. Dort waren plötzlich erstaunlich viele, zehn. Ich hatte vielleicht zwei dort abgelegt, bei denen Unklarheiten bestanden.
Von den Materialien, die dort sind, sind einige von mir. Sie waren in den alten Ordnern von rpi-virtuell.net gewesen und wurden beim Umzug vernichtet. Und nun tauchen einige wieder mit Fehler 404 in Entwürfen auf. Wie kommt das? Hat das jemand per Hand gemacht? Ist da eine Automatik drin (aber dann müssten es viel mehr sein).

**Comment by staude** [comment]
Das Schulgottesdienste mit der ID 1352 hab ich in meiner lokalen Version überhaupt nicht. War es evt im Papierkorb und irgendjemand hat die Sachen aus dem Papierkorb wieder hergestellt?
Lokal bei mir hab ich den Papierkorb mal gelöscht. das würde dann erklören warum ich den Post nicht habe. Könnte mal in dem Backup schauen das ich damals runtergeladen hatte.
das ist momentan auch so ziemlich die einzigste Erklärung die ich dafür habe.

**Comment by staude** [comment]
> Und nun tauchen einige wieder mit Fehler 404 in Entwürfen auf
Was heisst das, mit 404 in den Entwürfen auftauchen?

**Comment by staude** [comment]
Erinnerung @lehr-ruetsche
