### ISSUE TITLE
Portfolios

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#373]
Es ist auch ein Portfolio in den Entwürfen mit Fehler 404. Wo sind eigentlich die Portfolios des alten rpi-virtuell.nets? Die sollten doch im Sommer umziehen - oder habe ich das falsch in Erinnerung?

**Comment by staude** [comment]
>Es ist auch ein Portfolio in den Entwürfen mit Fehler 404. 

Was heisst das?

**Comment by lehr-ruetsche** [comment]
Das kannst Du eigentlich nicht wissen. Im alten rpi-virtuell gab es das sogenannte "Portfolio", ein sehr praktisches kleines Tool, in dem man gut Online-Aufgaben stellen konnte. Ich habe da einiges erstellt. Es würde micht interessieren, wo diese Sachen nun zu finden sind.

**Comment by staude** [comment]
Pportfolios wurden imho im chat #materialpool geklärt.
