### ISSUE TITLE
Herzlich Willkommen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#374]
Ganz ehrlich, ich weiß nicht recht, was ich von dem Herzlich willkommen halten soll. Es geht jedes Mal auf, wenn ich auf die Seite gehe, steht immer so lange da, dass ich denke, ist da jetzt ein Fehler? Außerdem klemmt es bei mir links ob klein in der Ecke und drumrum ein riesiger Rahmen. Also designmäßig auch nicht so der Bringer. Beim ersten Mal dachte ich echt, es handelt sich um einen Fehler im System. Könnte man das auch anders gestalten? Ist das was für unseren Berufsdesigner?

**Comment by staude** [comment]
??? Welches Herzlich Willkommen?  Und was meinst du mit "geht auf"?

**Comment by lehr-ruetsche** [comment]
MIr gefällt es immer noch nicht. Vor allem, weil ich zuerst da lande, wo ich eigentlich hinwill. Dann, nach einem Sekündlein, kommt man auf das Willkommen, dann wartet man zwei Sekunden und dann geht es wieder zurück. Ehrlich gesagt, fühle ich mich da eher etwas veräppelt als Userin.

**Comment by staude** [comment]
Ich kann mich nur wiederholen

??? Welches Herzlich Willkommen? Und was meinst du mit "geht auf"?

**Comment by staude** [comment]
Vielleicht mal nen Screenshot oder ein Video machen.

**Comment by staude** [comment]
Erinnerung @lehr-ruetsche :-)
