### ISSUE TITLE
Schlagwort Ritual

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#376]
Ich habe das Schlagwort Ritual in Einzahl und Mehrzahl. Nun will ich es nur noch in Einzahl haben und habe bis auf ein Material auch alle geändert, die das Wort Rituale in der Mehrzahl als Schlagwort hatten. Ich finde nun dieses allerletzte Material nicht, das Rituale als Mehrzahl im Schlagwortfeld hat. Gibt es da irgendeinen Trick?

**Comment by johappel** [comment]
normalerweise würde ich erwarten, dass ich die Materialien Finde wenn ich auf die Anzahl der Materialien hinter dem Schlagwort klicke. Die ist in diesem Fall jedoch ohne Link.
![image](https://user-images.githubusercontent.com/307023/32982210-ea24b6b8-cc80-11e7-8411-de1bdd72c5cd.png)

**Comment by staude** [comment]
Das letzte Material war https://material.rpi-virtuell.de/wp-admin/post.php?post=15970&action=edit
habe es geändert und das Schlagwort gelöscht. Aus nicht nachvollziehbaren Gründen war bei den genannten Artikel die Taxonomieverknüpfung schon entfernt, nur die Pods Metadata mit der SchlagwortID war noch vorhanden. Bei der Einweiterung die Anzahl in der Ansicht anzuzeigen zählte ich bisher nur die Metadata durch. 
Da die Taxonomieverknüpfung nicht mehr vorhanden war, tauchte auch das Schlagwort in der Materialübersicht nicht mehr als Schlagwort auf, weil es laut Taxonomieverknüpfungen nicht verwendet wurde.
Werde die Methode zu, zählen ändern und einen Link einbauen auf auf Materialliste.
