### ISSUE TITLE
Screenshot erscheint im Backend, aber im Frontend nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#378]
https://material.rpi-virtuell.de/material/kindergebaerden-adventskalender/

Manchmal kommt es vor, dass im Backend ein Screenshot angezeigt ist und im Frontend taucht er nicht auf. Gibt es da eine Möglichkeit, daran etwas zu ändern? Können wir als Eintragende etwas machen?

**Comment by staude** [comment]
Weil im Material einmal als CoverURl http://sprechende-haende.de/cms/front_content.php?idart=1060 eingetragen war, welches eine Seite ausliefert und keine Grafik, und ein Screenshot.
Die CoverURL wird aber mit höherer Priorität behandelt, wenn sie vorhanden ist. 
Hab die CoverURL gelöscht, jetzt wird der Screenshot ausgegbene.
