### ISSUE TITLE
Logo erscheint im Frontend nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#379]
In der Organisation (ZEIT ONLINE) ist das Logo defekt gewesen. Ich habe es ersetzt, aber im Frontend erscheint es nicht. Vielleicht auch eine Frage der Zeit...

https://material.rpi-virtuell.de/material/zuckerfest-weihnachten-und-chanukka-wie-kinder-religioese-feste-feiern/

**Comment by staude** [comment]
ist bei der orga und beim materual korrekt
<img width="1079" alt="2017-11-25_1542" src="https://user-images.githubusercontent.com/870951/33231562-6a8d7d64-d1f7-11e7-84a2-13e08c41238c.png">

<img width="447" alt="2017-11-25_1543" src="https://user-images.githubusercontent.com/870951/33231564-6ccb803a-d1f7-11e7-8c6b-78190e5621d6.png">

**Comment by lehr-ruetsche** [comment]
ja, dann dauerts vielleicht einfach ein bisschen, oder wie Joachim immer sagt: hast du den Cache geleert?
