### ISSUE TITLE
Keine Alpika erscheint Alpika: Nein

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#38]
Könnte Alpika nicht einfach wegfallen, wenn es nicht Alpika ist?

**Comment by staude** [comment]
Die Idee ist ja das Alpika Institute irgendwie hervorgehoben werden. 
Da es noch kein Design gib gebe ich halt ja oder nein aus

Sinn ist, das ich diese Daten überhaupt schon Anfragen kann
