### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#380]
Woran liegt es nochmals, wenn man Docs nicht im Viewer sehen kann, sondern herunterladen muss? Kommt öfters vor:
https://material.rpi-virtuell.de/material/religionsunterricht-unverzichtbar-fuer-alle-die-ihn-nicht-besuchen/

https://material.rpi-virtuell.de/material/nikolaus-von-myra-2/

**Comment by staude** [comment]
z.b. weil der ausliefernde Server einen Download erzwingt
