### ISSUE TITLE
Kommentarfunktion News und Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#381]
Michael Beisel hat im Materialpool einen Kommentar abgegeben, den man hätte freischalten müssen (was ich aber nicht gemacht habe, weil es um fehlendes Material ging).
In den News hat er auch einen Kommentar geschrieben, der aber offensichtlich sofort freigeschaltet wurde, ich habe nichts freigegeben.
Ist das so gedacht? Unterschiedliche Kommentarfunktionen in News und Materialpool? Wie ist es mit den Rechten von Michael? Könnte es auch daran liegen?

**Comment by staude** [comment]
Nein, die Einstellungen sind identisch. Der Entscheidende Punkt ist, das ein Kommentar automatisch durchgeht, wenn der User bereits einen KOmmantar geschrieben hat der veröffentlicht wurde.

Alle Einstellungen dazu kannst du dir auch ansehen unter Einstellungen/Diskussion

<img width="1259" alt="2017-11-26_1000" src="https://user-images.githubusercontent.com/870951/33238578-f954f6f0-d290-11e7-8a6f-82df45ecfa18.png">
