### ISSUE TITLE
falsches Bild

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#382]
Mir ist nicht ganz klar, wie es zu diesem Bild kommt:

https://material.rpi-virtuell.de/material/wann-wurde-jesus-geboren/

Es ist nicht der Autor, es kommt nicht auf der Seite vor, im Backend wird ein anderer Screenshot angezeigt... und dann erscheint dieses Bild?

**Comment by staude** [comment]
Es ist das erste als og:image im Quelltext der Seite referenzierte Bild.
