### ISSUE TITLE
Absatz

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#383]
https://material.rpi-virtuell.de/material/warten-im-advent/

Warum gelingt es nicht, vor das "Zusatzmaterial" einen Absatz zu machen? Alle Versuche waren vergebens, Das hatte ich schon mal. Welchen Trick gibt es hier?

**Comment by johappel** [comment]
ist wegen paste und copy. 
Da hattest du jede menge DIVS drin, die aber bei uns auf padding / margin  = 0 gesetzt sind

Es lohnt sich deshalb bei Paste und copy die entsprechenden Button im Editor zu nutzen
![image](https://user-images.githubusercontent.com/307023/33244244-3115e1c2-d2f4-11e7-95bd-0ab5002a0255.png)

**Comment by lehr-ruetsche** [comment]
okay, Danke.
