### ISSUE TITLE
Fehler 404

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#384]
https://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=rpi-impulse+4%2F2017

Hier taucht Fehler 404 beim Bild auf. Das sieht nicht so gut aus. Woran liegt das? Ich wollte hier etwas für Uwe Martini ausprobieren, aber so kann ich es ihm nicht schicken.

**Comment by staude** [comment]
Auf der Seite 1 der Suchergebnisse seh ich kein Material mit einem 404Fehler beim Bild.

Nach dem ich alle Ergebnisseiten einmal durchgeblättert habe, habe ich beim Material
https://material.rpi-virtuell.de/material/luther-2017-das-reformationsjubilaeum  ein kaputtes Bild gefunden.

Expliziete CoverURL (in dem Fall https://www.ekd.de/ekd_de/ds_img/assets_3420_x/2017_06_23_HERZAU_Global_Schools-Day_Wittenberg-0114_3420_rdax_1140x541_60.jpg ) überschreibt automatischen Screenshot. 
O.g. URL liefert aber kein Bild. Habe sie entfernt.

Meinstet du das Material oder ein anderes?

**Comment by staude** [comment]
da kommt doch jetzt was
![2017-11-27_0934](https://user-images.githubusercontent.com/870951/33257370-41ed7aca-d356-11e7-8f1f-da9fc8ab72ce.png)

und ja, es gibt dienste die sperren das screenshot tool aus das wir nutzen

**Comment by lehr-ruetsche** [comment]
Also, ich habe das Bild von der Seite abgespeichert und auf der von mir angelegten Seite wieder hochgeladen. Eigentlich müsste es doch dann angezeigt werden, oder? Ich habe keine Url übernommen oder so etwas.

**Comment by lehr-ruetsche** [comment]
Jetzt wird ein ganz normaler Screenshot gemacht, gut!
