### ISSUE TITLE
Titelsuche :-(

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#385]
Ich gebe "rpi-impulse 4/2017" ein und was immer als erstes kommt: rpi-impulse 2/2017.
Ich habe "rpi-impulse 1/2017" eingegeben und das System hat hübsche Sachen ausgespuckt, aber erst auf Seite 2 oder 3 das gesuchte Heft. Woran liegt das?

**Comment by staude** [comment]
Keine Phrasensuche siehe #200
