### ISSUE TITLE
LearningApps von Michael Beisel

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#387]
Michael Beisel hat einen LearningApps Beitrag vorgeschlagen. Aber wenn ich ihn abspeichere, wird der Beitrag nicht gefunden. Liegt das nun an mir oder ist da wirklich etwas schiefgelaufen? Könntet ihr mal nachschauen unter Materialpoolvorschläge. Ist der einzige, der momentan vorrätig ist.

**Comment by staude** [comment]
In der Veröffentlichen Metabox den Status ändern. Hab ich mal gemacht. Das Material liegt nun unter Entwürfe. Bitte noch die Metadaten nachpflegeb und dann kann es veröffentlicht werden. 

Screenshot kann ich gerade keine. Hochladen, hab es in der sbahn auf den Handy gemacht

**Comment by staude** [comment]
In der Veröffentlichen Metabox den Status ändern. Hab ich mal gemacht. Das Material liegt nun unter Entwürfe. Bitte noch die Metadaten nachpflegeb und dann kann es veröffentlicht werden. 

Screenshot kann ich gerade keine. Hochladen, hab es in der sbahn auf den Handy gemacht

**Comment by lehr-ruetsche** [comment]
Hat Michael Beisel keine Redaktionsrechte in unserem Materialpool? Das hatte ich eigentlich angenommen...
I
