### ISSUE TITLE
Warum gibt es eigentlich neuerdings zwei Mailpoets im Materialpool?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#388]

**Comment by staude** [comment]
Weil irgendjemand die neue Version 3 installiert hat ohne das zu kommunizieren und ohne einen Plan zur Migration zu besprechen.

**Comment by lehrruetsche** [comment]
Das kann ja eigentlich nur ich gewesen sein. Wobei ich dachte, es ginge um
ein Update.

Am 30.11.2017 23:03 schrieb "Frank Neumann-Staude" <notifications@github.com

**Comment by lehr-ruetsche** [comment]
Kannst Du den zweiten, den wir ja nicht nutzen, problemlos wieder löschen? Oder wolltest Du eh mal die neue Variante aufspielen?
