### ISSUE TITLE
Bildungsstufen und Medien: trotz Anhaken werden sie rot angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#389]
Bildungsstufen und Medien werden als nichtexistent (rot) angezeigt, obwohl man sie schön ordentlich ausgefüllt hat. Das ging Manfred Spieß so und mir so.

**Comment by lehr-ruetsche** [comment]
Irgendwie sieht das Fenster der Bildungsstufe anders aus. Früher waren die "Überschriften" deutlicher abgehoben.

**Comment by lehr-ruetsche** [comment]
Außerdem habe ich Mühe, eine Organisation einzutragen. Ich schreibe sie rein, sie wird erkannt, alles gut. Und wenn ich das Ganze aktualisiere und im Internet aufrufe, fehlt die Organisation.

**Comment by staude** [comment]
Pods Update  wurde zurückgenommen.
