### ISSUE TITLE
Keine Bildadresse

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#390]
Wenn ich keinen Screenshot machen kann und deswegen ein foto einsetze, kann ich keine Bildquelle so angeben, dass man sie im Frontend sieht. Ich kann nur Angaben im Backend machen.

**Comment by staude** [comment]
Brauchen wir ein extra Feld Bildquelle? @all

**Comment by lehr-ruetsche** [comment]
Ja, ich denke, es geht nicht anders.
