### ISSUE TITLE
Materialticker abonnieren

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#393]
Mir ist aufgefallen, dass man den Materialticker erst abonnieren kann, wenn man auf einem einzelnen Material ist. Ich denke, dass sollte in die Menüleiste des Materialpools.

**Comment by staude** [comment]
ist ein Untermenüpunkt unterhalb von Material entdecken

![2017-12-08_1140](https://user-images.githubusercontent.com/870951/33762453-c3e8e208-dc0c-11e7-8b4f-f474f3bf06ab.png)
