### ISSUE TITLE
Überschriften Themenseiten

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#394]
Die Unterseiten der Themenseiten, sozusagen die Kapitelüberschriften, ließen sich mal "zusammenfalten". Jetzt ist immer alles "entfaltet" zu sehen. Jeder Container ist offen.

https://material.rpi-virtuell.de/themenseite/weihnachten/

**Comment by staude** [comment]
JS minifiezierung in Rocket abgeschaltet. Das führt dazu das das JS nicht mehr sauber läuft.
