### ISSUE TITLE
Bild bei Doc funktioniert, bei Pdf nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#396]
Wenn ich ein Doc einpflege und einen Screenshot mache, kommt das blaue Doc-Icon. Wenn mich dies stört, kann ich ein zum Thema passendes Bild suchen und das erscheint auch unter "Material entdecken".
Wenn ich ein PDF einpflege, erscheint ebenfalls ein Doc-Symbol. Aber wenn ich hier das gleiche Bild hochlade, erscheint es bei "Material entdecken" nicht, sondern es bleibt bei dem Doc-Icon. Was ist der Unterschied bei einem PDF und einem Dokument, was das Bild angeht?
Es ist natürlich die Frage, ob man sich den Aufwand mit dem Bild machen will. Wenn man das Icon sieht, weiß man gleich, woran man ist.

**Comment by johappel** [comment]
Kannst du mir eine konkrete Url geben`?
