### ISSUE TITLE
in synonymen view nach Normwort suchen

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#397]
in synonymen view nach Normwort suchen

**Comment by lehr-ruetsche** [comment]
Es wäre gut, wenn man bei den Schlagworten die Synonyme mit angezeigt bekäme. Es wäre so oder so praktisch, aber es hat sich herausgestellt, dass nicht automatisch alle Synonyme übernommen werden.
Bei den Jesiden zum Beispiel kam Yeziden nicht, obwohl angezeigt auf ONGD, dafür drei andere, recht ungewöhnliche Synonyme.

**Comment by staude** [comment]
>Es wäre gut, wenn man bei den Schlagworten die Synonyme mit angezeigt bekäme. 
@lehr-ruetsche An welcher Stelle?

**Comment by staude** [comment]
So? @lehr-ruetsche 

![2017-12-21_1149](https://user-images.githubusercontent.com/870951/34252837-79aeadf6-e645-11e7-9a5f-26d096dc7f8d.png)

**Comment by staude** [comment]
Wenn an anderer Stelle geünscht, bitte Ticket wieder öffnen

**Comment by johappel** [comment]
Wäre es denkbar dass die Synonyme auch im Datensatz des Materialsangezeigt werden etwa unter den Schlagworten? Weil man ja wahrscheinlich nicht immer in die Schlagwort ansicht wechseln will

**Comment by johappel** [comment]
Ja das wäre perfekt, denke ich
