### ISSUE TITLE
ALPIKA ersetzen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#399]
Da mit ALPIKA niemand etwas anfangen kann, diesen Begriff ersetzen.
Religionspädagogisches Institut?

**Comment by lehr-ruetsche** [comment]
Hallo Frank, vielleicht warst Du bei der Sitzung nicht dabei, in der Manfred Spieß, meiner Meinung nach völlig zu recht, bemerkt hat, dass ALPIKA eigentlich ein Begriff ist, den man nur innerhalb der Institute verwendet und den sonst "keine Sau" kennt. Alpika sollte eigentlich eine Art Qualitätsnachweis sein, aber wenn niemand den Begriff kennt, nützt er nichts. Deswegen war die Fragen, ob man anstelle von ALPIKA etwas anderes verwenden könnte, was die User besser verstehen. Ich hatte nur das Gefühl, dass dieses berechtigte Anliegen von Manfred Spieß wieder etwas aus dem Blick geraten ist.

**Comment by staude** [comment]
Nein, war ich nicht dabei. Ich zeichne in der Regel Issues mit "Question" aus, über die in der Runde Diskutiert werden muss, wenn ich die Entscheidung nicht treffen kann.
