### ISSUE TITLE
Filme: nur Url zu sehen oder der ganze Film?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#40]
Bisher ist bei der Veröffentlichung eines Videos nur die URL zu sehen. Bisher konnte man im alten rpi-virtuell direkt auf den Film gehen und im allgemeinen bemüht sich vor allem Jörg bei Veröffentlichungen immer darum, dass man gleich auf den Film kommt. Wie möchten wir das in Zukunft haben?

**Comment by staude** [comment]
via oEmbed implementieren.
