### ISSUE TITLE
Schlagwortsynonyme

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#401]
Wenn ich etwas konvertiere oder neu eintrage, stehen (egal was ich eintrage) folgende Schlagworte unter Schlagwortsynonyme: Zweiregimenlehre, Zwei-Reiche-Lehre, Zwei-Regimente-Lehre, Zwangsumsiedlung, Zwangsmigration 
![schlagwortsynonyme](https://user-images.githubusercontent.com/17722241/34325842-1bb7490a-e89e-11e7-97f9-465e193e4da7.png)
Wenn ich nun zum Beispiel "Bergpredigt" bei den Schlagworten eingebe, dann erscheint das, und zwar nur das, was ich selbst als Synonym eingebe. Also nicht, was die ONGD vorschlägt.
![schlagwortsynonym eigenes](https://user-images.githubusercontent.com/17722241/34325855-7360c3ac-e89e-11e7-835f-27d2f80a7db7.png)

**Comment by lehr-ruetsche** [comment]
In der Zwischenzeit ist mir noch folgendes passiert:
Ich habe am Thema Paralympics gearbeitet und habe als erstes Schlagwort das Wort Behinderung eingegeben. DAnn erschien richtig "Behinderungen" bei den Synonymen. Die Synonyme habe ich noch mit Handicap ergänzt. Als ich dann auf "Aktualisieren" ging, erschienen die beiden richtigen Synobnyme plus eine ganze Latte falscher Synonyme und zwar die, die immer da stehen: Zweireichelehre usw.
![schlagwortsynonyme falsche erganzung](https://user-images.githubusercontent.com/17722241/34326096-8a48ce00-e8a5-11e7-85f4-c4198e2bcedc.png)

**Comment by lehr-ruetsche** [comment]
Außedem ist mir noch aufgefallen: ich gebe ein Schlagwort ein, die eingegebenen Synonyme erscheinen. Ich gebe ein weiteres Schlagwort ein, und es kommen keine weiteren Synonyme mehr. Obwohl es zum zweiten Schlagwort auch welche gäbe.

**Comment by johappel** [comment]
Bei mir steht das:
![image](https://user-images.githubusercontent.com/307023/34374695-ab46f796-eae2-11e7-9c64-6659ecedc874.png)

**Comment by lehr-ruetsche** [comment]
ja, warum steht das da, selbst wenn man noch gar nichts eingegeben hat?

**Comment by lehr-ruetsche** [comment]
Gestern wollte ich es ganz gründlich machen. Gudrun hat Holocaust bearbeitet. Das Schlagwort heißt aber "Judenvernichtung". Also habe ich mehrere Synonyme eingegeben: Holocaust, Schoah, Shoah usw.
Was erscheint aber?
![shoah synonym](https://user-images.githubusercontent.com/17722241/34378045-5933d692-eaf4-11e7-91ae-8b3d9162c85c.png)
Das habe ich nicht eingegeben und so steht es auch nicht bei der OGND

**Comment by lehr-ruetsche** [comment]
Ich denke, das mit Schlagworten und Synonymen müssen wir uns nochmals anschauen.
