### ISSUE TITLE
Schlagwortsynonyme bei der Rubrik Schlagworte

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#402]
Wenn ich auf das Feld "Schlagworte" gehe, erscheinen hinter einzelnen Begriffen keine Synonyme, einzelne Synonyme oder ganz viele und zum Teil recht ungewöhnliche Synonyme. Wonach richtet sich diese Auswahl? Was immer erscheint, sind die selbst eingegebenen und das ist gut. Aber nach welchem Kriterium füllen sich die Synonyme bei manchen Schlagworten so ausführlich und bei anderen gar nicht? Und muss ich jetzt praktisch immer noch nachschauen, was da steht und gegebenfalls ergänzen?

**Comment by staude** [comment]
??? Das Normwort das der Bibliotheksservice liefert wird als Schlagwort eingetragen und alle Synonyme dieses Normworts als Synonym in de Synonymtabelle zu diesen Normwort/Schlagwort. 
In der Schlagwortansicht werden hinter jeden Schlagwort die Synonyme ausgegeben ´, die diesen Schlagwort/Normwort zugeordnet sind.

**Comment by lehr-ruetsche** [comment]
Mit welcher Normwortdatei arbeitest Du? Ich verwende - so wie mir Martin Wünsch es gezeigt hat - OGND.

**Comment by lehr-ruetsche** [comment]
Und die Synonyme, die dort angegeben werden, erscheinen so nicht bei den Schlagworten.
