### ISSUE TITLE
Fehler beim Schlagwort Gleichnis

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#403]
Ich habe versucht, die "Gleichnis"-_Seiten zu überarbeiten, weil ich ja grundsätzlich alles als Einzahl ausgewiesen habe, es aber bei Gleichnisse Einzahl und Mehrzahl gibt. Es waren ich glaube 69 Gleichnisse. Was ja ausgereicht hätte. Durch irgendeinen Befehl, den ich irgendwie ausgelöst habe, habe sie sich jetzt verhundertfacht. Ich kann sie aber auch nicht in den Papierkorb schieben. Jedes einzelnen Gleichnis wird jetzt eine ganze Seite lang wiederholt (im Bereich der Schlagworte). Ich glaube, im Frontend wirkt es sich nicht aus. Kann man den Befehl rückgängig machen? Ich glaube, ich habe beim Antippen von "alle öffnen" gleichzeitig Strg gedrückt. Oder die Lösung ermöglichen, die vielen überflüssigen Darstellugnen in den Papierkorb zu verschieben?

**Comment by beo9999** [comment]
Ich sehe im Backend 60 Einträge für Schalgwort "Gleichnis" und 3 für "Gleichnisse", sieht eigentlich ok aus.

**Comment by lehr-ruetsche** [comment]
Bei mir sieht es leider so aus: 
![gleichnise](https://user-images.githubusercontent.com/17722241/34385792-725f320c-eb25-11e7-9f41-0b5ce43ba58c.png)
Ich weiß nicht, was ich da gemacht habe :-(

**Comment by staude** [comment]
Fehler in der Backend-Suche, danke für den Hinweis

**Comment by staude** [comment]
Der Workaround ist, einfach das Schlagwort als Filter zu nehmen, was eh viel Sinnvoller ist alle eine Volltextsuche, wenn es um das bearbeiten von Schlagwörtern geht.

![2018-01-08_1414](https://user-images.githubusercontent.com/870951/34672347-5fc69d94-f47e-11e7-89f4-dd35b3f4a04f.png)
