### ISSUE TITLE
Auf Chrome werden keine Seiten angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#404]
Vielleicht ist das ein singuläres Ereignis, aber ich habe heute Abend zweimal auf Chrome den Materialpool geöffnet und dann "Material entdecken" angeklickt. Dann wurde die 1. Seite der Materialien angezeigt, aber ich konnte auf keine weiteren mehr kommen. Es gab keine Seitenanzeigen.

**Comment by johappel** [comment]
Kann ich nicht nachvollziehen

**Comment by lehr-ruetsche** [comment]
![chrome material entdecken](https://user-images.githubusercontent.com/17722241/34377822-2399dc76-eaf3-11e7-8bdf-e8723c4ef2d5.png)
So sieht es bei mir aus.

**Comment by staude** [comment]
Evt überfleissiger Adblocker, Javascript abgeschaltet oder sonstige Security Einstellungen?
Kann ich ebenfalls in meinem Chrome nicht nachvollziehen.

**Comment by lehr-ruetsche** [comment]
Ja, ich habe jetzt bei Chrome nach dem Cache gesucht und tatsächlich geht es jetzt. Ich muss allerdings nie bei einer anderen Internetseite den Cache leeren, damit alles funktioniert. Ich verstehe es nicht so ganz, warum das bei rpi-virtuell so ist.
