### ISSUE TITLE
Autoren-Mails

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#406]
Gestern habe ich mal eine Reihe Autorenmails losgeschickt. Und weil ich gerade mit Margit Metzger sowieso Kontakt habe, habe ich gefragt, ob sie bei ihr angekommen sei. Darauf bekam ich folgende Antwort von ihr:

ja, danke, es ist angekommen.
 
Überraschend waren die Grüße am Ende:
Sind die Angaben korrekt? Möchten Sie ein neues Foto von sich einstellen?
Wenn Sie Änderungswünsche haben, lassen Sie uns dies bitte wissen.

Mit freundlichen Grüßen
margit-metzger
Redaktion rpi-virtuell/Comenius-Institut Münster redaktion@rpi-virtuell.de
 
Das sieht so, aus, als ob es von mir selbst wäre.
 
Und beim Aufrufern kam dann, dass ich bisher keine Beiträge hätte. Jetzt habe ich gleich mal einen von mir gemacht, da kommt immer noch, 0 Beiträge .
Deshalb auch die Frage gestern zu der Autorenschaft – da müsste ich doch immerhin jetzt schon mehr als einen Beitrag haben?

**Comment by staude** [comment]
Ist doch richtig, sie hat sich selbst eingetragen

![2017-12-29_2150](https://user-images.githubusercontent.com/870951/34447241-6adc77ce-ece2-11e7-995c-2e1be9a8f458.png)

Welches Material soll denn von ihr sein?

**Comment by lehr-ruetsche** [comment]
ah, okay, alles klar. Sie hat sich selbst eingetragen, als wir zusammen das Eintragen besprochen haben. Daran habe ich nicht mehr gedacht.
