### ISSUE TITLE
Texte bei "externen Materialpooleinträgen"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#407]
Ich habe zwei Vorschläge von Michael Beisel in den Materialpool übernommen: 
https://material.rpi-virtuell.de/material/luthers-wappen/
https://material.rpi-virtuell.de/material/03a-mahnmale-berlin-schlachtensee/

Für beide Vorschläge hat Michael Texte entwickelt, die aber nicht auftauchen, sondern nur die Einleitungstexte von Learning-Apps tauchen auf. Das war von ihm so nicht beabsichtigt. Was könnte mit seinen Texten passiert sein, die er eingetragen hat?

**Comment by lehr-ruetsche** [comment]
Ich habs jetzt selbst getestet, tatsächlich taucht der eingetragene Beschreibungstext nicht auf. Bei dem Vorschlag, den ich eingereicht habe, taucht nur mein Name, meine Emailadresse und im Titel der Bezugsort und der Titel auf.

**Comment by staude** [comment]
Duplikat: #360
