### ISSUE TITLE
Gliederung verschwindet in der "Material entdecken - Ansicht"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#408]
WEnn ich im Beschreibungstext eine Gliederung darstelle, bleibt die in der Einzelansicht erhalten. In der Übersicht von "Material entdecken" verschwindet sie aber, was den Text manchmal eigenartig wirken lässt. Lässt sich daran etwas ändern?

https://material.rpi-virtuell.de/facettierte-suche/

**Comment by staude** [comment]
HTML Cpde wird da entfernt, weil die Text abgeschniten wird. Lösung wäre, wenn man einen extra Anreisser Textfeld hätte, wo nur Text erlaubt ist.  
Muss Diskutiert werden.

**Comment by lehr-ruetsche** [comment]
Ich habe das ähnliche Phänomen auf anderen Internetseiten jetzt auch beobachtet. Es wirkt halt seltsam. Ist immer die Frage von Aufwand und Ertrag im Verhältnis.
