### ISSUE TITLE
Logo riesig

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#41]
Das Logo der EKHN, das in der Beschreibung unter "klein" läuft, kommt hier riesig raus. Gibt es hier eine automatische Begrenzung? (Das gleiche Problem wie bei den Fotos).

**Comment by lehrruetsche** [comment]
http://material.rpi-virtuell.de/organisation/evangelische-kirche-in-hessen-und-nassau/

**Comment by staude** [comment]
Gibt ja noch kein design
