### ISSUE TITLE
Statistik im Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#410]
Für die News werden über Statify statistische Zahlen ziemlich genau erhoben. Vielleicht finde ich es auch nicht, aber im Materialpool geht das nicht so einfach. Wie könnte man dort zum Beispiel feststellen, was die am meisten aufgerufenen Materialien sind? Könnte man dort auch Statify nutzen?

**Comment by staude** [comment]
Wir haben lange darüber gesprochen welche Daten erhoben werden sollen und daraus ist dann das Materialdashboard entstanden mit allen den Graphen. 
Ggf könnte man ja in der Materiallist die Abrufe als Sortierkriterium einführen.

**Comment by lehr-ruetsche** [comment]
ja, das wäre wirklich interessant. Man kann natürlich sehen, wie oft ein einzelnes Material aufgerufen wurde und ich habe mir mal die Zeit genommen, ein paar Seiten durchzuklicken. Auf diesen Seiten waren mit Abstand die IS-Seiten und andere Islamseiten, die Manfred konvertiert hat, die Spitzenreiter. Das hat mich ziemlich überrascht. Deswegen dachte ich, es wäre interessant zu wissen, was wird am häufigsten aufgerufen. Und da gibt es bei den News eine Übersichticht und bei den Materialien nicht. Deswegen meine Frage.

**Comment by lehr-ruetsche** [comment]
Wenn das machbar wäre, wäre das eine tolle Sache!
