### ISSUE TITLE
Themenseite: Reaktion bei Löschung eines Titels

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#411]
Heute habe ich ein Material gelöscht. Das Material war bis dahin auch allerdings aufgeführt in einer Themenseite. Dort allerdings tauchte es immer noch auf. Beim Anklicken wurde es dann natürlich nicht gefunden. 
War das jetzt nur, weil nicht genügend Zeit vorhanden war zwischen Löschen und Kontrolle?
Oder ist das ein grundsätzliches Problem? Weil bei den Themenseiten war das Häkchen mit dem Titel immer noch vorhanden.

**Comment by johappel** [comment]
Kannst du dazu schreiben, auf welche Themenseite welcher Link jetzt ins Leere führt?

**Comment by staude** [comment]
ja, ggf müsste das löschen eines Materials da noch was triggern

**Comment by lehr-ruetsche** [comment]
Es war zur Themenseite Bergpredigt. Aber ich habe den Link natürlich gelöscht. Man müsste da einfach einen Testballon starten.
