### ISSUE TITLE
Text verschwindet

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#412]
Es sieht so aus, als würde der Text bei Materialeinträgen "von außen" verschwinden. Michael Beisel hat Material vorgeschlagen und einen längeren Text dazu geschrieben, der nicht aufgetaucht ist. Ich habe einen Test gemacht mit ähnlichem Ergebnis. Irgendwo habe ich es schon vermerkt, aber nicht hier auf github.

**Comment by staude** [comment]
siehe #360

**Comment by lehr-ruetsche** [comment]
ah, okay, dann schließen wir das hier. Kann der Text von Michael Beisel noch gefunden werden? Er war wohl ziemlich aufwändig. Zu seinen Learning Snacks Einträgen.
