### ISSUE TITLE
Antwortmails bei Autoren und Organisationen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#413]
In den Weihnachtsferien habe ich eine ganze Reihe von Autorenmails losgeschickt. Anscheinend sind auch Antworten zurück gekommen. Nur leider habe ich sie nicht erhalten. Kann es so eingerichtet werden, dass ich die Antwortmails auch erhalte? Und dass ich die bereits eingegangenen Mails weitergeleitet bekomme?

**Comment by staude** [comment]
Wie besprochen ist die replayto adresse redaktion@rpi-virtuell.de

![2018-01-09_0958](https://user-images.githubusercontent.com/870951/34712602-a108316e-f523-11e7-812c-5e786b754afa.png)

@johappel ist das nur im chat falsch geschrieben oder ist die weiterleitung an Andrea wirklich falsch eingetragen?

**Comment by lehr-ruetsche** [comment]
Du meinst, eine Kopie auch der nach außen gegangenen Mails?

**Comment by lehr-ruetsche** [comment]
Also, ich verstehe den Text oben nicht, aber die Mails kommen nach der Korrektur der Adresse jetzt bei mir an. Damit ist das Problem für mich erledigt.
