### ISSUE TITLE
Screenshot bleibt nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#414]
Manchmal mache ich einen Screenshot und sehe, dass er auftaucht. Wenn ich das Material dann aktualisiere und betrachte, ist der Screenshot wieder verschwunden. Auch wenn ich nachträglich Änderungen vornehme, muss ich jedesmal den Screenshot wieder neu machen. Ich meine, das wäre früher nicht so gewesen. 
Zum Beispiel hier:
https://material.rpi-virtuell.de/material/juedisches-leben-in-hessen-vor-dem-holocaust/

Ich glaube, diesen Screenshot habe ich mindestens fünf mal gemacht.

**Comment by staude** [comment]
Interessant. Lokal kann ich das verhalten nicht nachvollziehen. Betrifft auch nur neuere Einträge. 
Die PostMeta ist da, aber er glaubt da da nichts ist.
