### ISSUE TITLE
Warum kommen bei der Bergpredigt "Die Frauen am Grab"?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#415]
Ich würde es gerne verstehen: Weder im Titel, noch im Text noch in den Schlagworten kommen in den "Frauen am Grab" die Bergpredigt vor. Warum taucht das Material dann trotzdem bei der Suche auf?
https://material.rpi-virtuell.de/facettierte-suche/?fwp_medientyp=worksheet&fwp_suche=Bergpredigt

**Comment by staude** [comment]
Kommt im Text vor

<img width="657" alt="2018-01-09_0953" src="https://user-images.githubusercontent.com/870951/34712436-1ad41f54-f523-11e7-8a11-154f40332fbc.png">
