### ISSUE TITLE
Darstellung Text Bild

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#416]
https://material.rpi-virtuell.de/material/reichskristallnacht-novemberpogrome-1938/

Kann man an dieser Darstellung etwas ändern? Der Text sitzt zu nahe am Bild.

**Comment by staude** [comment]
css in  https://github.com/rpi-virtuell/rw-materialpool-theme  angepasst.
https://github.com/rpi-virtuell/rw-materialpool-theme/commit/32a8727c532f35e30bc86a1feef7f7ea27f7d068
