### ISSUE TITLE
Sprachanzeige

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#417]
Heute habe ich zum ersten Mal die englische Sprache angehakt, bei der Shoa Foundation. Allerdings wird sie im Frontend gar nicht angezeigt.
https://material.rpi-virtuell.de/material/usc-shoah-foundation-institute/

**Comment by staude** [comment]
Das wird auch aktuell nur als Facette zum Filtern benutzt.
<img width="431" alt="2018-01-09_1656" src="https://user-images.githubusercontent.com/870951/34729911-3664c210-f55e-11e7-8ca8-146611a6c70d.png">

**Comment by staude** [comment]
Kann man ja drüber diskutieren ob das auch in der Detailansicht ausgegeben werden muss

**Comment by lehr-ruetsche** [comment]
Es kommt selten vor und ich kanns auch in den Text schreiben. Aber warum sollte man es nicht anzeigen lassen?

**Comment by lehr-ruetsche** [comment]
Nur, dass ich es richtig verstehe: wir geben englisch an, nur damit man bei rpi-virtuell nach Dokumenten in englischer Sprache suchen kann, oder Seiten etc.
