### ISSUE TITLE
Vorschau Mailpoet

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#418]
Als der Mailpoet für die Materialien eingerichtet wurde, ging es mit der Vorschau-Mail super fix.
Ich habe sie abgeschickt, sie kam bei mir an, ich hab sie mir angeschaut und entsprechend weiter gearbeitet. Seit einiger Zeit dauert es ewig. Woran könnte das liegen? Ist ein bisschen schwierig, wenn ich noch spät eine rausschicken will und nicht Stunden warten. Manchmal sieht das Schriftbild beim Arbeiten anders aus als beim Verschicken, deswegen finde ich die Vorschau-Mail nicht schlecht.

**Comment by staude** [comment]
Dann musst du in die Headerdaten der Mail reinschauen, da steht dann drin welcher Server sie zu welcher Uhrzeit bearbeitet hat. Wenn Mailserver eine große Last haben, weil z.b. gerade ein großé Spamwelle auf sie einprasselt kann das auch schon mal um Stunden verzögert sein. 
Email ist KEINE Echtzeitkommunikation.
