### ISSUE TITLE
Blog anlegen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#419]
Also, ich möchte gerne mein nicht mehr öffentlich auffindbares Material zu Euthanasiemorden im Dritten reich als neuen Blog anlegen.
Ich berichte von meinen Erfahrungen.
Ich glaube, ich bin jetzt beim 5. Versuch, der Seite einen Webseiten-Namen und einen Webseiten-Titel zu geben. Ich weiß nicht genau, was was ist und es gelingt mir auch nicht, weil einer von beiden nur mit kleinen buchstaben und zahlen geschrieben werden darf. Also nicht Euthanasie-Morde, nicht Online-lernen. Okay, nun zum 6. Versuch.
Okay, ich habe alles klein geschrieben (absurd) und habe alle Bindestriche herausgenommen (nützte auch nichts). Oh, im achten Durchgang ist es gelungen, nachdem ich es komplett runterreduziert habe und anhand der früheren blogs geschlossen habe, was ich machen müsste.

**Comment by johappel** [comment]
Beim ersten anlegen des Blogs oder beim späteren bearbeiten?

**Comment by empeiria** [comment]
![image](https://user-images.githubusercontent.com/1091954/34981164-01914e16-faa7-11e7-9281-93a791fc8bda.png)
Wahrscheinlich schaut es so aus.
War es nur das Problem, dass Website-Namen  nur aus Kleinbuchstaben (a-z) und Zahlen bestehen dürfen oder gab es weitere Probleme?

**Comment by lehr-ruetsche** [comment]
Website-Name und Website-Titel: ich glaube, für euch ist völlig klar, wo der Unterschied ist. Für mich war es nicht klar. Ich habe es über Versuch und Irrtum herausgefunden.

**Comment by staude** [comment]
Ist kein Materialpool Problem

**Comment by lehr-ruetsche** [comment]
stimmt, ist kein Materialpoolproblem.

**Comment by lehr-ruetsche** [comment]
Könnte man das klarer machen, was mit Websitename und Website-Titel gemeint ist?

**Comment by staude** [comment]
Beschreibung hinzufügen

![2018-02-22_0950](https://user-images.githubusercontent.com/870951/36528574-dd977252-17b5-11e8-8a53-e990da17d6af.png)

**Comment by empeiria** [comment]
"teil der url" ist nicht korrekt - es müsste "teilderurl" heissen, weil ja keine Leerzeichen erlaubt sind

**Comment by empeiria** [comment]
Habe ein Tutorial dafür erstellt, das diese Probleme gleich berücksichtigt und bespricht:
https://youtu.be/rxiBlhEbvac
