### ISSUE TITLE
eva Stuttgart

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#420]
Im Moment trage ich zwei Autorinnen bei der eva Stuttgart nach. Da bin ich auf folgendes Phänomen gestoßen: Wenn ich über "Einrichtungen" alle Materialien der eva suche, finde ich selbstverständlich auch das zuletzt von Frau Herbold eingetragene Material zu Vertrauen:
https://material.rpi-virtuell.de/material/starke-gefuehle-vertrauen-materialien-der-eva-zur-diakonischen-arbeit-fuer-den-unterricht/

Wenn ich über das Suchfeld gehe und dort "Starke Gefühle" eingebe, kommen mehrere Beiträge der eva, die alle mit diesem Leitbegriff anfangen, aber das Material zu Vertrauen fehlt. Woran könnte das liegen?

Was mir auch noch aufgefallen ist bei der eva Stuttgart: Manchmal sind die Entwürfe direkt verlinkt und werden mit dem PDF-Icon angezeigt. Manchmal taucht das Bild eines Kreuzes auf. Dieses Material ist dann mit der Übersichtsseite verlinkt, auf der das Material zu finden ist. Ist es möglich, dieselbe Adresse mehrmals einzugeben? Eigentlich nicht, oder?
https://material.rpi-virtuell.de/organisation/evangelische-gesellschaft-eva/

**Comment by johappel** [comment]
1. Die Adresse dees Materials scheint sich geändert zu haben. @staude wieso passiert das?
https://material.rpi-virtuell.de/material/starke-gefuehle-vertrauen
2. Wenn ich suche kommt bei mir auch der Beitrag auf Seite 2
![grafik](https://user-images.githubusercontent.com/307023/34989721-e659662a-fac3-11e7-92db-291d594d87f6.png)
3. die Urls für die Materuialien sind oft falsch :-(
Zum Beispiel ist die materialurl bei "Starke Gefühle: Melancholie": http://www.eva-stuttgart.de/nc/unsere-angebote/angebot/unterrichtsmaterialien
Da muss also einfach die richtige Url hin

**Comment by staude** [comment]
Weil sich der Titel geändert hat.  Der Titel ist der Slug

**Comment by johappel** [comment]
@staude ok. Das Verhalten ist allerdings ungünstig, wenn bereits Links zu dieser Materialseite existieren und nachträglich der Titel geändert wird. Müsste man da was machen? Bei "normalen" Beiträgen bleibt der slug erhalten, auch wenn sich der Titek ändert.

**Comment by lehr-ruetsche** [comment]
Also, das ist zum Glück selten der Fall, aber bei der EVA gab es sowohl Änderungen im Namen der Organisation (zweimal) und wahrscheinlich auch Titeländerungen. Ist das für das System ein Problem?
