### ISSUE TITLE
Bilder

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#421]
Die Bilder beim Anne Frank Haus sind von hervorragender Qualität. Dennoch kommen sie in der Detailseite (Screenshot) nur unscharf raus. Liegt das daran, dass es ein Screenshot ist?
https://material.rpi-virtuell.de/material/anne-frank-webguide/

**Comment by empeiria** [comment]
Ich würde eher so einen Screenshot machen:
![image](https://user-images.githubusercontent.com/1091954/35040199-8b9c531a-fb80-11e7-8676-a65ba48bd233.png)

**Comment by staude** [comment]
Es ist das Bild, welches die Webseite den Sozialen Medien per og:image bereit stellt.
http://www.annefrank.org/ImageVaultFiles/id_12272/cf_7336/AFK2011_CB194.JPG
