### ISSUE TITLE
Darstellung bei den Einrichtungen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#423]
Von der EVA Stuttgart gibt es 17 Materialien. Wenn ich auf die Einrichtung gehe, werden diese auch angezeigt. Aber wenn ich dann die einzelnen Materialien durchgehe, wiederholen sich manche und andere werden gar nicht angezeigt.
Bei mir wiederholen sich: Lebensfreude, Schmerzen, Wut, Solz, Trauer.
Gar nicht angezeigt werden: Melancholie, Ohnmacht, Erleichterung, Geborgenheit.
Sie sind aber im Materialpool.
Außerdem habe ich versucht, die Chronologie über das Eingabedatum zu regeln. Aber das hat auch nicht geklappt. Nach welcher Reihenfolge die Sachen in den Einrichtungen erscheinen, ist mir nicht klar.
Allerdings haben wir zwischendurch auch zweimal den Namen der Einrichtung gewechselt. Könnte das eine Rolle spielen?

**Comment by staude** [comment]
>Wenn ich auf die Einrichtung gehe, werden diese auch angezeigt. Aber wenn ich dann die einzelnen
> Materialien durchgehe, wiederholen sich manche und andere werden gar nicht angezeigt

Heisst was?

>Nach welcher Reihenfolge die Sachen in den Einrichtungen erscheinen, ist mir nicht klar.

Das neuste oben.  Da du auch in der Einrichtungsansicht Suchen und per facette Filtern kannst macht eine Sortierung nicht wirklich Sinn.

**Comment by lehr-ruetsche** [comment]
das neueste ist Tag des Eintrags?
Damit ist aber die Frage nicht geklärt, dass es 17 verschiedene Einträge gibt, aber bei der Einrichtung Eva nicht 17 verschiedene Einträge angezeigt werden, sondern manche mehrmals und andere gar nicht. 
Welche angezeigt werden, habe ich oben beschrieben. Welche nicht angezeigt werden, auch. Aber alle haben die Organisation EVA, das habe ich nachgeprüft. Warum werden dann welche angezeigt und das auch noch doppelt und andere gar nicht?

**Comment by staude** [comment]
Da  Du weder Screenshots anhängst, noch konkrete URLs nennst kann ich ja nur raten.

Wenn ich nach eva in den Organisationen suche, komme ich auf https://material.rpi-virtuell.de/organisation/evangelische-gesellschaft-eva/ 

Die haben 17 Materialien und da sehe ich 

Seite 1 (https://material.rpi-virtuell.de/organisation/evangelische-gesellschaft-eva/) 

Starke Gefühle: Vertrauen
Unterrichtsmaterialien: Eva Stuttgart
Starke Gefühle: Ungeduld
Starke Gefühle: Begeisterung
Starke Gefühle: Melancholie
Starke Gefühle: Sehnsucht
Starke Gefühle: Erleichterung
Starke Gefühle: Hoffnungslosigkeit
Starke Gefühle: Geborgenheit
Starke Gefühle: Angst

Seite 2 ( https://material.rpi-virtuell.de/organisation/evangelische-gesellschaft-eva/?fwp_paged=2 )

Starke Gefühle: Lebensfreude
Starke Gefühle: Schmerzen
Starke Gefühle: Heimweh
Starke Gefühle: Wut
Starke Gefühle: Stolz
Starke Gefühle: Trauer
Mit allen Sinnen: Schmecken


Ich kann da keine Dopplung sehen. Was (Screenshot) ist wo (URL) deiner Ansicht nach falsch?

Seite 1

![firefox_screenshot_2018-01-25t23-08-28 381z](https://user-images.githubusercontent.com/870951/35417314-3041e878-022d-11e8-8ca8-c048687d0b55.png)


Seite 2

![firefox_screenshot_2018-01-25t23-09-00 970z](https://user-images.githubusercontent.com/870951/35417319-340f3bb8-022d-11e8-9e41-727137e85716.png)

**Comment by lehr-ruetsche** [comment]
Ja, perfekt, genauso habe ich es mir vorgestellt! Nur dass es sich mir, als ich es bearbeitet habe, nicht so dargestellt hat. Auch nicht mit verschiedenen Browsern. Dem Materialpool muss man offensichtlich manchmal Zeit geben, was ich auch nicht so ganz verstehe, weil die meisten Sachen setzt er ja sofort um.
Also, alles in Butter bei der Eva (hoffe ich wenigstens).
