### ISSUE TITLE
Gleiche Adresse wird nicht mehr gemeldet?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#425]
Ich habe vor kurzem Ufuq eingegeben und Manfred Spieß heute Morgen auch. Beide Adressen lauteten:
http://www.ufuq.de/
Müsste doch etwas gemeldet werden, oder?
Bei der EVA laufen bis auf ein Material alle unter der gleichen Adresse (zum Glück), aber das System hat sich beim Eintragen auch nie beschwert, dass es diese Adresse schon gäbe.
Ist diese Funktion irgendwie ausgefallen?

**Comment by staude** [comment]
@lehr-ruetsche  Hast du mal die Materialpool URLs zu den beiden Materialien? 
Ich sehe 4 von Manfred von heute, da hat keine die URL von.

**Comment by staude** [comment]
Ah, schon gefunden - Manfreds Eintrag war vom 22.1. nicht von heute.

**Comment by staude** [comment]
ja, scheint nicht mehr zu funktionieren.
