### ISSUE TITLE
Werk und Bände bei zeitspRUng

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#426]
Ich habe die Zeitschrift der AKD "Zeitsprung" als Werk angegeben und einzelne Zeitschriften als Bände.
Das ging lange Zeit ganz gut, aber jetzt kann ich als Werk die Seite "Zeitsprung" nicht mehr eingegeben. Und ich weiß nicht, warum.
Zum Beispiel hier:
https://material.rpi-virtuell.de/wp-admin/post.php?post=22246&action=edit

**Comment by staude** [comment]
Ich vermute mal das Pods da nur maximal 15 Treffer zurückliefert damit es nicht zu unübersichtlich wird. Wenn natürlich jeder Beitrag auch den Namen des Werks noch mal mit drin hat funktioniert das nicht. 
Auch die Anzahl auf z.b. 30 zu erhöhen löst das Problem ja nicht langfristig

Workaround, damit du die verknüpung überhaupt eintragen kannst, wöre, vom Werk ausgehend die neue seite, die ja einen eindeutigen Tiel hat, zuzuordnen. Hab ich mal bei der genannten Seite gemacht, geht so, ist aber ein klein bisschen mehr Aufwand.

**Comment by staude** [comment]
Suche manipulieren, ZS1603 als Bibliografisches Tag in einem Metafeld in dieser Suche berücksichtigen.
