### ISSUE TITLE
Normwort und Synonym

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#427]
In den Anfangsphasen habe ich oft Plural eingegeben anstelle von Einzahl. Wenn ich auf solche Fälle treffe, verbessere ich diese in der Regel umgehend. Ich habe nun aus "Flüchtlinge" die Einzahl "Flüchtling" gemacht. Ich erinnerte mich aber daran, dass Joachim als Synonym zu Flüchtlinge "Geflüchtete" eingegeben hat.
Das Synonym Geflüchtete hat aber das Normwort "Flüchtlinge" behalten. Es hat sich nicht automatisch mit meiner Verbesserung von Flüchtlinge in Flüchtling gewandelt (im Synonymbereich). Ich habe das Wort von Hand geändert. Aber das konnte ich nur, weil ich mich daran erinnert habe.
Ich weiß, alles etwas kompliziert, ich erkläre es auch gerne mündlich. Nichts Schlimmes, aber halt etwas, was nicht so gut funktioniert, wie es funktionieren könnte.

**Comment by staude** [comment]
Synonym und Normwort sind auch nur einfach Zeichenketten und keine Verknüpfung zum Schlagwort. Nicht jede Synonym/Normwort Kombination ist auch automatisch ein Schlagwort (nur die, die über den Schlagwort/Bzbw Mechanismus kommen), aber wenn man über die Suchstatistiken herausfindet das Anwendende über andere Begriffe suchen oder wir entscheiden mal eine synonymdatenbank zu importieren, dann werden das nicht automatisch Schlagwort sein.
