### ISSUE TITLE
Mails versenden funktioniert nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#428]
Ich wollte eben eine neue Runde Autorenmails verschicken, aber der Status blieb bei "nicht versendet".

**Comment by staude** [comment]
Die Mailfunktionen sind in den Einstellungen auch deaktiviert

**Comment by staude** [comment]
<img width="1283" alt="2018-01-30_1442" src="https://user-images.githubusercontent.com/870951/35569233-f2e97886-05cb-11e8-85a2-dfd9e58a058e.png">
