### ISSUE TITLE
Adressen der alten Portfolios???

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#430]
Ich weiß, dass es die alten Portfolios noch gibt. Aber ich kenne die Adresse nicht. Irgendein M, das man groß schreiben muss, aber welches? Hier bräuchte ich mal eine Einführung.

https://material.rpi-virtuell.de/material/e-portfolio-zu-anne-frank/

Ich glaube, das habe ich mal gemacht.

**Comment by staude** [comment]
Portfolios wurde mal im Chat im #materialpool diskutiert im Dezember. Da findet man auch einen link auf http://www.rpii.net/workspace/9A772A02-52E8-429A-8D84-F852344C8E37/Portfolios/

Ansonsten weiß ich nix von Portfolios

**Comment by staude** [comment]
@beo9999 vielleicht?

**Comment by lehr-ruetsche** [comment]
ja, ich frag ihn mal, er konnte mir auch bei der Euthanasie-Geschichte helfen.
