### ISSUE TITLE
Neue Materialien auf der Newsseite verschwunden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#432]
Mir ist eben aufgefallen, dass die neu eingebenen Materialien auf der Newsseite nicht mehr auftauchen. Da gab es ja diverse Probleme in letzter Zeit. Wird das wieder eingerichtet?

**Comment by staude** [comment]
A: Kein Materialpool Problem
B: Da News -> @empeiria @johappel Wer hat da geschraubt?

**Comment by empeiria** [comment]
ist noch nicht gelöst - das ist das bislang ungelöste RSS-Problem:
https://github.com/rpi-virtuell/rw-materialpool/issues/439
Ich kann das auch mit Pluginwechsel für RSS-Feeds nicht beheben.
