### ISSUE TITLE
Mails an Organisationen und Autoren können nicht versandt werden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#433]
Leider funktioniert der Versand von Emails an Autoren und Organisationen nicht mehr. Ich meine, ich hätte es auch schon mal irgendwo eingetragen, finde es aber momentan nicht.

**Comment by staude** [comment]
Siehe auch #428 

Die Mailfunktionen sind in den Einstellungen auch deaktiviert

**Comment by staude** [comment]
<img width="1283" alt="2018-01-30_1442" src="https://user-images.githubusercontent.com/870951/35569206-d8bd7296-05cb-11e8-9086-a8d2ab59ee8e.png">
