### ISSUE TITLE
Mailpoet: Auswahl begrenzt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#434]
Wenn ich in den Mailpoeten Material einfügen will, geht ein Fenster auf, und ich kann aus verschiedenen artikeln auswählen. Leider funktioniert der Scroll nach unten nicht mehr. Ich habe also nur etwa zehn Materialien zur Auswahl.
![auswahl](https://user-images.githubusercontent.com/17722241/35579223-6b889582-05e6-11e8-85ee-d7e185f54c15.png)

**Comment by staude** [comment]
Kann ich nicht nachvollziehen, wenn ich den Balken bis nach **ganz** unten ziehe werden weitere Einträge nachgeladen

<img width="807" alt="2018-01-31_1129" src="https://user-images.githubusercontent.com/870951/35618084-292dda96-067a-11e8-8a2c-80660c598755.png">

Welcher Browser? Irgendwelche Fehlermeldungen in der Browserkonsole?

**Comment by lehr-ruetsche** [comment]
Firefox

**Comment by lehr-ruetsche** [comment]
![ergebnisse werden geladen](https://user-images.githubusercontent.com/17722241/35636374-355edf0e-06b1-11e8-9c9c-fb3159dbd508.png)

**Comment by staude** [comment]
kann ich mit Firefox nicht nachvollziehen

<img width="1155" alt="2018-01-31_1953" src="https://user-images.githubusercontent.com/870951/35641479-962c2f6c-06c0-11e8-9114-a4be23538617.png">
