### ISSUE TITLE
Wiederholungen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#435]
Seit einiger Zeit werden Adress-Wiederholungen nicht mehr angezeigt. Das erschwert meine Arbeit SEHR!
Es gibt ständig Doppelungen. Oder Manfred trägt was ein und ich nochmal.

**Comment by staude** [comment]
geht wieder 
<img width="763" alt="2018-02-15_1146" src="https://user-images.githubusercontent.com/870951/36252773-fdbab4a6-1245-11e8-9bcb-c02dec453eba.png">
