### ISSUE TITLE
Wiederholungen bei den Materialien im Backend

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#438]
Also, wahrscheinlich könnt ihr es euch nicht vorstellen, aber es ist WIRKLICH ein SCHEISS-BUG! Ich wiederhole mich: wenn ich ein Material suche und gebe bei Materialien im Backend ein Suchwort ein, dann kommt das:
![wiederholungen](https://user-images.githubusercontent.com/17722241/36433411-b73c8c00-165c-11e8-8a16-460749da39cb.png)

33 mal wiederholt sich dasselbe! Es ist schwierig, so zu arbeiten.

**Comment by staude** [comment]
Siehe #403 
Da steht  auf der Workaround zumindest für Schlagworte oder andere der Filter in der obigen Liste.

Ansonsten kann ich mich leider nicht klonen, Stichwort Prioritäten
