### ISSUE TITLE
RSS-Feeds funktionieren nicht

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#439]
Der Feed https://material.rpi-virtuell.de/feed/?post_type=material wird auf https://news.rpi-virtuell.de/ nicht im Widget angezeigt.
Gleicher Fehler für den Feed https://material.rpi-virtuell.de/feed/?bildungsstufe=elementary&post_type=material, der eigentlich auf http://rpq.pti-elementar.de/ im Footer eingebunden ist:
![image](https://user-images.githubusercontent.com/1091954/36529365-713f7f02-17b8-11e8-8339-1ce97a81e04a.png)

**Comment by staude** [comment]
Auf http://rpq.pti-elementar.de funktioniert das wieder. Ich habe mit https://github.com/rpi-virtuell/rw-materialpool/commit/a252f5767af64379918da41e51642843f9143d89 als Workaround eingebaut, das wenn ein & in der codierte URL im XML ist, das dann das enclosure unterdrückt wird.

Ganz Fehlerfrei kann ich den Feed nicht machen, dazu fehlen uns schlicht Daten, ausser wir nehen die Beitragsbilder wieder raus.

**Comment by staude** [comment]
Nach entfernen und neueintragen des Widgets wird es nun auch auf news wieder ausgegeben. 

Ich schiesse das nun, aber bitte noch im Augebehalten ob das nun Dauerhauft erledigt ist oder wie doch noch mal wieder Material haben wo es Probleme  bei gibt.

**Comment by empeiria** [comment]
brauchen wir dann den Workaround für alle Seiten, die einen RSS-Feed aus dem Materialpool anzeigen wollen? Dann sollte ich evtl. eine Anleitung dazu erstellen?

**Comment by staude** [comment]
Du hast aber schon gesehen das https://github.com/rpi-virtuell/rw-materialpool/commit/a252f5767af64379918da41e51642843f9143d89 eine Änderung im RSS Generierungscode des Materialpools ist .)

**Comment by empeiria** [comment]
Vielen Dank für diesen geduldigen Hinweis :-) Dann ist ja alles gut! (hatte ich nicht gesehen)
