### ISSUE TITLE
Verweise

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#440]
Worthaus hat bei einigen seiner älteren Materialien die Adressen verändert. Dabei ist mir aufgefallen, dass bei "Verweisen" etwas mit nicht ganz rechten Dingen zugeht:
https://material.rpi-virtuell.de/material/gleichnisse-i/
Wenn man sich die Detailseite anschaut, wird auf alles mögliche verwiesen, nur nicht auf die Gleichnissse II und III. Was könnte hier vorliegen?

Hier liegt ein dasselbe Phänomen vor: https://material.rpi-virtuell.de/material/luthers-reformatorischer-durchbruch/

**Comment by staude** [comment]
Die Themenseiten Facetten stimmen auch nicht. FacetWP hat seinen Renderer geändert, unsere Art die IDs vorzugeben funktioniert nicht mehr :(
