### ISSUE TITLE
Optik

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#441]
Kann sein, dass das nur bei mir so aussieht:

https://material.rpi-virtuell.de/organisation/worthaus/?fwp_paged=3

Die Autoren sind bei mir ganz weit nach unten gerutscht. Sozusagen "aus dem Bild".

**Comment by staude** [comment]
Nein, ist hier auch so das auf Seite 3 dieser Liste der Contentbereich breiter läuft und darum die Autoren umgebrochen werden. @johappel

**Comment by staude** [comment]
In Firefox 58.0.2 auf dem Mac ist es korrekt. In Safari, Opera und Chrome ist es defekt

<img width="1191" alt="seite2" src="https://user-images.githubusercontent.com/870951/36790460-318ed8c6-1c95-11e8-95e7-dd746ead175e.png">

<img width="1182" alt="seite3" src="https://user-images.githubusercontent.com/870951/36790463-3422ce3a-1c95-11e8-945d-0b8fd7540593.png">

**Comment by staude** [comment]
Diese URl bricht nur im FF um, in den anderen Browser wird das Element erst noch verbreitert.

![2018-02-28_1445](https://user-images.githubusercontent.com/870951/36790773-30283558-1c96-11e8-8fed-6c331874950e.png)

**Comment by staude** [comment]
Mit https://github.com/rpi-virtuell/rw-materialpool-theme/commit/25bebdcd96e436e98eb13d22291fff3d16d2823a gefixed
