### ISSUE TITLE
zuordnung stimmt nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#444]
Wenn man im Materialpool Autoren anklickt, erscheinen auch die Autoren.
Aber rechts daneben, wo einzelne Autoren mit ihren Materialien zu sehen sein sollen, stehen Organisationen!
Das sollte bis Donnerstag noch geändert werden.
![zuordnung autor und organisation](https://user-images.githubusercontent.com/17722241/36665429-cd747a8e-1ae7-11e8-9a72-7beeb7624c05.png)

**Comment by staude** [comment]
Das ist korrekt so.
Das ist die Liste der Autoren und ich kann über die Organisations Facette auf Organisationen Filtern

**Comment by lehr-ruetsche** [comment]
Ah, okay, ich habs verstanden.
