### ISSUE TITLE
Konvertierung?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#448]
Zurzeit recherchiere ich das Abendmahl. Ich habe neu eingetragen und es wurde nicht kritisiert: Abendmahl - Power und Schauer. Unter "Beiträge" sozusagen im alten Materialpool, war es unter keinem Stichwort zu finden, im neuen Materialpool auch nicht. Soweit so gut. 
Nun zeigt aber die alten Themenseite genau dieses Material an. Irgendwo müsste es also sein. Warum kann ich es nicht finden?
![abendmahl power und schauer](https://user-images.githubusercontent.com/17722241/37030548-9c92b9da-213b-11e8-9859-16ad47fb3329.png)

**Comment by staude** [comment]
Das "Abendmahl - Power und Schauer" hat die URL http://www.konfirmandenarbeit-ekhn.de/downloads/power-und-schauer.pdf 
Ist also kein Link erst zur einem Materialpooleintrag.
