### ISSUE TITLE
Falsche Schlagworte 

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#451]
Ich weiß nicht, ob man folgendes Problem lösen kann. Wenn ja, wäre es sehr schön. Wenn wir ein Schlagwort falsch eingegeben haben und merken das, verbessern wir es und löschen das alte Schlagwort.
Wenn aber ein anderer Redakteur das nicht weiß und immer noch das alte Schlagwort eingibt, wird dieses munter aktzeptiert. Es erscheint kein roter Rahmen, der anzeigt, dass mit diesem Schlagwort etwas nicht in Ordnung ist. Das System übernimmt das Schlagwort sofort. So wird das falsche Schlagwort wieder angelegt. Kann man da was machen?

**Comment by staude** [comment]
@lehr-ruetsche  Hast du im aktuellen System mal ein Beispiel dafür?

**Comment by lehr-ruetsche** [comment]
Ganz aktuell ist es mit "Nahtod" so, das habe ich gelöscht, es heißt "Nahtoderfahrung", aber das ist vielleicht noch zu frisch. Wenn ich wieder auf ein "altes" komme, schreibe ich Dir. Kommt öfters vor.

**Comment by staude** [comment]
Jetzt ging es, offenbar ein Caching Problem. 

<img width="1247" alt="2018-03-21_1138" src="https://user-images.githubusercontent.com/870951/37705500-86e78544-2cfc-11e8-8277-c7d4f9029eb4.png">

**Comment by staude** [comment]
Ich kann das Problem nicht nachstellen.

Im Konkreten Fall ist es Sinnvoll Nahtod noch als Synonym für Nahtoderfahrung zu hinterlegen, das fehlt noch.

Ansonsten kann es halt mal passieren, das das JS vielleicht nocht geht oder in einen Timeout läuft oder den Materialpool nicht erreichen kann. Aber das müsste man sich halt genau in dem Moment dann in dem Browser ansehen bei der Person, wo es gerade aufgetreten ist.

Aktuell kann ich das fehlverhalten gerade nicht reproduzieren.
