### ISSUE TITLE
sceenshot

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#455]
es tauchen viele 404 auf, wo sie nicht müssten. Mir scheint, der screenshot schwächelt. Es gelingt mir nicht, hier einen herzustellen:
https://www.bibelwissenschaft.de/stichwort/100018/
Das war früher kein größeres Problem.

**Comment by staude** [comment]
das liegt leider an den kaputten Servern von bibelwissenschafft.de

wenn man z.b. mit curl die Seite abruft ohne browseragent usw wird auch nur eine leere Seite ausgeliefert.

da haben wir keinen Einfluss drauf. Einzigste Abhilfe ist, selbst einen Screenshot zu erstellen.
