### ISSUE TITLE
Fehler 404

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#456]
Ich habe den Eindruck, dass langsam alle PDFs Fehler 404 aufweisen. Wenn ich zum Beispiel die Themenseite "Pfingsten" aufmachen, sehe ich nur noch gelb. Ich bin mir sehr sicher, dass das nicht so aussah, als ich die Themenseite gebaut habe. Die vielen 404 sind mir schon seit einiger Zeit aufgefallen.

https://material.rpi-virtuell.de/themenseite/pfingsten/

Woran kann das liegen?

Ich denke, dass hier früher ein Symbol war. Wir haben ab und zu ein Bild für das Symbol eingesetzt, aber nicht immer. Könnte man das wieder einrichten, dass bei PDFs ein Symbol auftaucht? Das Fehler 404 Zeichen macht einen unguten Eindruck.

**Comment by staude** [comment]
>Woran kann das liegen?

Das der ScreenshotServer von Wordpress.com die Datei nicht lesen kann/darf und einen 404 Fehler bekommt. Ansonsten würde er ja unter ein Doc Icon liefern. 

Dann müssen wir mal schauen ob es einen anderen Dienst gibt den wir einbinden können oder sonst wie was bauen.

**Comment by lehr-ruetsche** [comment]
Aber ich denke, dass da früher wirklich ein Icon kam. Ich weiß noch, dass sich Joachim über die Ansammlung von Icons beschwert hat und nicht über die Ansammlung von Fehler 404.

**Comment by staude** [comment]
Dann hat sich was beim Seitenbetreiber(Serverconfig oder bei wp.com geändert, beides Dinge auf die wir keinen Einfluss haben

**Comment by staude** [comment]
Bin ganz angetan von https://www.screenshotapi.io 
10.000 screenshots Kostenlos, danach 1$ pro 3000 Screenshots.
Wenn wir die selbst speichern nach der Erzeugung kommen wir ja mit den 10000 auch erst mal recht weit.

**Comment by lehr-ruetsche** [comment]
Mir ist einfach wichtig, dass wir die vielen Fehler 404 rauskriegen, das kommt einfach nicht gut. Die User denken ja, da gibts nix. Natürlich kann man auch händisch Bilder eintragen, aber bei Sünde, Hoffnung usw. da brauchst du einfach viel Zeit. Das würde ich mir und den anderen Eintragern gerne ersparen.
