### ISSUE TITLE
blog Einträge im Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#457]
Es kann sein, dass ich zu diesem Thema einiges vergessen habe, was wir bereits besprochen haben: unter "unvollständige Materialpooleinträge" sind mir mehrere Blogbeiträge aufgefallen, die ich jetzt praktisch nacharbeiten muss, d.h., ich muss raten, was der Blogeintrager eigentlich sagen wollte.
Ist das so gedacht? 
https://material.rpi-virtuell.de/wp-admin/post.php?post=16915&action=edit 
Als beispiel

**Comment by lehr-ruetsche** [comment]
oh shit, ich habe die falsche Adresse eingetragen. Entschuldige, ich arbeite gerade mal wieder an mehreren Baustellen gleichzeitig.
Ich meinte diesen hier:
https://material.rpi-virtuell.de/wp-admin/edit.php?post_type=material&mode=incomplete

**Comment by staude** [comment]
Siehe https://chat.rpi-virtuell.de/channel/redaktion?msg=NWBSeXmXdp5v3wYFX und folgend.
