### ISSUE TITLE
Chronologie?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#458]
Lieber Frank, die letzten drei Einträge von gestern sind zwar im Materialpool, aber nicht ganz vorne, wo so chronologisch gesehen ja sein müssten. Ich finde sie nur über die Suche. Das Stichwort "Ehe" zu finden, ist übrigens fast unmöglich. Bei diesem hier erscheinen auch nicht im Viewer die Arbeitsblätter: kann man daran noch etwas ändern oder ist das halt so?
https://material.rpi-virtuell.de/material/steckbriefe-der-fuenf-weltreligionen/

**Comment by staude** [comment]
>seit gestern Abend keine neuen Einträge mehr auf.

Kann ich so nicht bestätigen. 

![2018-04-26_0953](https://user-images.githubusercontent.com/870951/39292879-b90edf7a-4937-11e8-9a73-91cce949a31e.png)

**Comment by lehr-ruetsche** [comment]
Ich habs mit drei Browsern probiert

**Comment by staude** [comment]
> Das Stichwort "Ehe" zu finden, ist übrigens fast unmöglich.

Was meinst du damit? 

 Suche nach Ehe https://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=ehe liefert als zweien Treffer das Special zu Ehe, was übrigens Ehe nicht als Schlagwort hat.

**Comment by lehr-ruetsche** [comment]
Über die Startseite auf "Material entdecken" gehen, dann kommen nur Sachen von gestern. Wobei jetzt eins mehr kommt als vorher. Aber die ganzen heutigen Sachen nicht.

**Comment by lehr-ruetsche** [comment]
![material entdecken](https://user-images.githubusercontent.com/17722241/39293349-ee4084ae-4938-11e8-86e3-bb78d5fdc727.png)

**Comment by staude** [comment]
Ich vermute mal ein Problem bei dir. Hab es auf verschiedenden Geräten über 4 verschiedene Internetanbindungen probiert. Überall sind die neuen Nahostkonflikt Materialien das neuste.

Schon mal Shift-Reload und Cachelöschen probiert?  Was für eine Internetanbindung`Gibt es da ggf noch einen (Zwangs)Proxy
