### ISSUE TITLE
Materialsuche

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#459]
Diese Material kann ich über die Suche einfach nicht finden:

https://material.rpi-virtuell.de/material/fragekarten-zum-kirchenraum/

Ich bin unter Materialpool - Material entdecken gegangen und habe folgende Begriffe eingegeben: Fragekarten, Kirchenraum und das Schlagwort Kirchraumpädagogik.
Ich hatte das Bilder verändert und wollte es mir anschauen. Aber das Material kam nicht mal mit 404, es kam einfach gar nicht, obwohl es natürlich da ist.

**Comment by staude** [comment]
Kann ich beim besten willen nicht nachvollziehen


Suche nach Fragekarten liefert nur dieses eine Material
https://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=fragekarten

Schlagwort Kirchenraumpädagogig liefert 9 Treffer, an dritter Stelle das genannte Material
https://material.rpi-virtuell.de/facettierte-suche/?fwp_schlagworte=kirchraumpaedagogik

Suche nach Kirchenraum liefert das material auf der zweiten seite
https://material.rpi-virtuell.de/facettierte-suche/?fwp_suche=Kirchenraum&fwp_paged=2

**Comment by lehr-ruetsche** [comment]
Oh, wenn ich Uni Bonn eingebe, funktioniert es. Obwohl in der Titelzeite Universität Bonn steht.
Aber auf der Homepage steht uni-bonn.
Ist das irgendwie gerankt?

**Comment by staude** [comment]
die url wird ebenfalls durchsucht

Wenn ich in Einrichtungen nach Universität Bonn suche 
https://material.rpi-virtuell.de/organisation/?fwp_organisation_suche=Universität%20bonn
bekomme ich zwei, passende Treffer

<img width="1748" alt="2018-04-27_1041" src="https://user-images.githubusercontent.com/870951/39353347-a699839c-4a07-11e8-9cfc-4be6406584ab.png">

Hast du das Universität Bonn per hand in das suchfeld getippt oder per copy&paste von irgendwo übernommen?

**Comment by lehr-ruetsche** [comment]
Per Hand eingetippt

**Comment by lehr-ruetsche** [comment]
Sie ist launisch, die Diva. Jetzt klappt es. Kann es sein, dass es eine Rolle spielt, dass ich kurz vorher etwas an den Seiten geändert habe? Deswegen wollte ich mir ja anschauen, wie sie jetzt aussehen.
