### ISSUE TITLE
Suche im Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#462]
Bei meiner Themenseiten-Suche nach Unterrichtsentwürfe wurden vier Ergebnisse gemeldt zu Ramadan. Es waren aber nur zwei Entwürfe zu Ramadan, die anderen zur christlichen Fastenzeit.
Bei diesen steht aber nur "Fasten" und "Fastenzeit" als Schlagwort. Warum findet er die Unterrichtsentwürfe unter "Ramadan"? Ich möchte es einfach nur verstehen.

**Comment by staude** [comment]
Weil Ramadan das Normwort zu den Synonymen Fasten und Fastenmonat ist
https://material.rpi-virtuell.de/wp-admin/edit.php?s=Ramadan&post_status=all&post_type=synonym&action=-1&m=0&paged=1&action2=-1

**Comment by staude** [comment]
Wobei das unter https://xgnd.bsz-bw.de/Anfrage nicht nachvollziehbar ist,

@lehr-ruetsche kannst du ja unter https://material.rpi-virtuell.de/wp-admin/edit.php?s=Ramadan&post_status=all&post_type=synonym&action=-1&m=0&paged=1&action2=-1 wieder löschen, zumal Fasten auch ein eigenes Schlagwort bei uns ist.
