### ISSUE TITLE
Bildgröße bei Material entdecken

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#465]
https://material.rpi-virtuell.de/material/glauben-wir-alle-an-denselben-gott/

Warum kommt das Bild so riesig raus? Das ist doch sonst nicht so?

**Comment by staude** [comment]
Weil bei einen Special/Dossier das Bild auf die Breite des Bereichsskaliert wird und dieses Bild im Gegensatz zu einem Screenshot auch noch ein Hochkantstehendes Bild ist.
