### ISSUE TITLE
Werden gleiche Adressen noch angezeigt?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#467]
Ich habe eben diese Adresse eingegeben:
https://www.zeit.de/campus/2018-01/gottesbeweis-glaube-wissen-naturwissenschaft-religion

weil ich mich aber noch an das Bild erinnern konnte, habe ich nachgeschaut und das hier gefunden:

https://material.rpi-virtuell.de/material/gottesbeweis-kann-man-beweisen-dass-gott-existiert/?sq=https%3A%2F%2Fmaterial.rpi-virtuell.de%2Ffacettierte-suche%2F%3Ffwp_suche%3DGottesbeweis%26fwp_paged%3D2

Ich meine, es wäre diesselbe Adresse. Oder übersehe ich etwas?

**Comment by staude** [comment]
Das eine ist http das andere eine https Adresse
