### ISSUE TITLE
YouTube - Einbettung klappt nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#468]
Ich habs mit dem Einbettungscode proberiert und mit allen anderen auch, irgendwie klappts nicht:
https://material.rpi-virtuell.de/material/die-bibel-aus-juedischer-sicht-hiob/

**Comment by staude** [comment]
Das. liegt an dem Video. Wenn man die den ifram embed code von YT verwendet, bekommt man ein Fenster mit diesem Hinweis. Bei dem "normalen" einbetten nur über die URL kommt tatsächlich nichts zurück.

<img width="578" alt="2018-07-16_1216" src="https://user-images.githubusercontent.com/870951/42753747-2b70c372-88f2-11e8-9cfd-68a7b7814815.png">
