### ISSUE TITLE
existiert bereits in dieser Taxomonie

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#469]
Also, ich weiß immer noch nicht, wodurch diese Rückmeldung ausgelöst wird. Irgendwie vermute ich, dass es mit den Schlagworten zu tun hat. Es hat auf jeden Fall nichts mit dem Titel zu tun und nichts mit der Url.
![existiert bereits](https://user-images.githubusercontent.com/17722241/42385166-49faa41a-813c-11e8-9508-270af37767c6.png)

**Comment by staude** [comment]
Kann ich so nicht reproduzieren. Vermutung: Schalgworte können auch darüber eingetragen werden, evt war die Überprüfung auf Synonyme usw nocht nicht abgeschlossen als du schon speichern gedrückt hast, welshalb er versucht hat etwas als Schlagwort anzulegen, das aber schon existiert.
