### ISSUE TITLE
Schlagworte und Synonyme

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#474]
Wenn Schlagworte schon mal eingetragen wurden wie Dreieinigkeit, Dreifaltigkeit und Trinität und man kommt nachträglich an und sortiert sie einander zu, dann funktioniert das leider nicht so gut.
Wenn man dann einen Beitrag eingibt und das Synonym Dreifaltigkeit, wird das einfach eingetragen, obwohl Trinität auftauchen müssten.
Bei neuen Begriffen funktioniert es gut. 
Kann man da was ändern?

**Comment by staude** [comment]
Was ist „einander zusortierten“

**Comment by lehr-ruetsche** [comment]
Ich habe Trinität zum Schlagwort gemacht und die anderen beiden bei Synonymen eingegeben und bei Schlagwort gelöscht. Aber sie werden trotzdem angeboten, wenn ich in das Feld etwas eintragen will.
Wenn es richtig funktioniert, was durchaus vorkommt, dann gebe ich Dreifaltigkeit ein und automatisch verwandelt das System das Wort in Trinität um. Wenn ich Körper eingebe, wird zum Beispiel automatisch Leib daraus gemacht. Bei Dreifaltigkeit funktioniert das nicht, weil es auch schon mal ein Schlagwort war, das nachträglich zum Synonym gemacht wurde.
