### ISSUE TITLE
Not Found - Screenshot verschwindet nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#475]
Bei Frieder Harz sind ja viele Links tot. Aber manche habe ich wieder belebt. Und danach verschwindet der "Not-Found" - Screenshot einfach nicht. Ich habe jetzt schon bei vielen Einträgen händisch Bilder nachgetragen, weil es einfach ungut rüberkommt, wenn soviele Notfound-Einträge zu sehen sind.
![not found](https://user-images.githubusercontent.com/17722241/44868714-e3f95500-ac8b-11e8-8767-bf2da59baf5a.png)

**Comment by staude** [comment]
Hmm. eigentlich sollten neuen generiert werden wenn sich die url ändert
hast du mal Beispiel IDs von solchen Materialien
