### ISSUE TITLE
Schaf

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#476]
Es ist immer toll, wenn man viele Schlagworte eingegeben hat, und dann erscheint das:
![taxonomie schaf](https://user-images.githubusercontent.com/17722241/44870199-d04fed80-ac8f-11e8-84f5-a57e0fdbb1ee.png)

Heute habe ichfestgestellt, dass das zweimal passiert ist, nachdem ich das Wort "Schaf" eingegeben hatte.
Was immer dahinter steckt...

**Comment by staude** [comment]
Ja, ich kann den Fehler so bestätigen. Das ist aber auch alles. Aktuell hab ich nicht den Hauch einer Idee.
