### ISSUE TITLE
Die Auszeichnungen ändern sich bei Minderungen nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#477]
Frieder Harz hat jetzt über 100 Einträge verloren, von 183 auf 55. Dennoch hat er immer noch den güldenen Kranz:
![viele geschichten](https://user-images.githubusercontent.com/17722241/44879019-bd95e280-aca8-11e8-855c-d83a44f1e758.png)

**Comment by staude** [comment]
mit erneuten speichern des autoren ist wieder alles korrekt.
we hattest du gelöscht?  Material rausgesucht und gelöscht oder erst die zuordnung entfernt zwischen Material und Autor?

**Comment by staude** [comment]
autoren Cache verwerden bei Materiallöschung

**Comment by lehr-ruetsche** [comment]
D.h. übersetzt: auf die Autorenseite gehen? Das habe ich zum Teil auch gemacht. Wäre das grundsätzlich immer günstiger? Ich lösche an allen möglichen Stellen.
