### ISSUE TITLE
Google Maps macht Ärger

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#488]
Neuerdings wird bei VEranstaltungen das hier angezeigt:
![google maps](https://user-images.githubusercontent.com/17722241/47418325-316cdc80-d77a-11e8-9bee-3ef57b019e17.png)

**Comment by staude** [comment]
Das ist kein API Key für die Google Map hinterlegt
@johappel bitte machen oder mir zugangsdaten zu dem Googlekonto geben unter dem das eingerichtet werden soll

**Comment by staude** [comment]
Erinnerung @johappel

**Comment by lehr-ruetsche** [comment]
![google maps bei veranstaltungen](https://user-images.githubusercontent.com/17722241/48344434-55cf2100-e675-11e8-8a06-5fa6b1396459.png)

sieht immer noch so aus

**Comment by lehr-ruetsche** [comment]
Ist leider immer noch so, auch am 22.11.

**Comment by staude** [comment]
Das das nun alles in der Google Cloud Plattform zusammengefasst ist und man da auch ne Rechnungsadresse usw hinterlegen muss, werde ich das nicht auf meinen eigenen Account machen.
@johappel bitte drum kümmern.
