### ISSUE TITLE
Sofareli - Viewder

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#490]
Lässt sich bei dieser Seite das PDF im Viewer noch irgendwie darstellen?

**Comment by staude** [comment]
Welche Seite?

**Comment by staude** [comment]
Diese? https://material.rpi-virtuell.de/material/pfingsten-umgang-mit-der-inklusiven-bunten-vielfalt/?sq=https%3A%2F%2Fmaterial.rpi-virtuell.de%2Ffacettierte-suche%2F%3Ffwp_suche%3DSofareli

geht bei mir

**Comment by lehr-ruetsche** [comment]
Ja, auf dem explorer geht es bei mir auch. Ich weiß nicht, was mit firefox ist. Ich habe es ja ganz frisch heruntergeladen und keine Einstellungsänderungen vorgenommen.
