### ISSUE TITLE
Qua-Lis NRW

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#493]
Den Namen Qua-Lis habe ich falsch geschrieben, so wie jetzt und oben. Die Organisation hat mich darauf hingwiesen, dass die Schreibweise falsch ist, nur das i ist klein, also QUA-LiS. Das habe ich sofort verbessert und oberhalb des Logos wird es jetzt auch so geschrieben. Aber bei jedem einzelnen Material wird es immer noch falsch geschrieben. Ich habe einen Tag gewartet, ich habe sämtliche Caches geleert, die man nur leeren kann: die Darstellung ist immer noch nicht korrekt. Woran könnte das liegen?
https://material.rpi-virtuell.de/organisation/qua-lis-nrw/?dsgvo-confirmed=1542881875

**Comment by staude** [comment]
Danke, ist in der Tat ein permanenter Cache der die Umbenennung der Orga nicht berücksichtigt.
