### ISSUE TITLE
PDF erscheint nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#497]
Hallo Frank, kriegst Du das noch hin, dass dieses PDF im Viewer erscheint?

https://material.rpi-virtuell.de/material/der-engel-bringt-maria-eine-botschaft/

**Comment by staude** [comment]
Nein, weil mich der Material link zu dieser Seite bringt

<img width="974" alt="2018-12-12_1213" src="https://user-images.githubusercontent.com/870951/49866214-6bb43b00-fe07-11e8-9df4-5d84843c1cec.png">

**Comment by lehr-ruetsche** [comment]
ah, okay, dann lass ich nur die Zwinglis drin. Es liegt auch ein Schreiben vor, dass sie ihre SEiten überarbeiten wollen.
