### ISSUE TITLE
Galery Order

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#500]
Nochmals Galerie:

Hier tauchen ganz komische Einträge auf:
![gallery order](https://user-images.githubusercontent.com/17722241/50081513-efe33580-01ee-11e9-8ae3-dc8bc502b1dc.png)

**Comment by staude** [comment]
Das ist der Shortcode, der im Beitrag die Galerie einblendet.

**Comment by lehr-ruetsche** [comment]
Das heißt, das bleibt jetzt so? Auch ohne Bild?
