### ISSUE TITLE
Materialdetail Bildquelle

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#502]
Bildquelle als Link.

**Comment by lehr-ruetsche** [comment]
Wenn ich beim Material ein Bild eingebe, dessen Quelle ich benennen will, wird auf der Frontpage das Wort "Bildquelle" angezeigt. Wenn ich darauf klicke, komme ich aber leider nicht auf die Bildquelle, sondern lande im "nichts". 
https://material.rpi-virtuell.de/material/flucht-im-lebenslauf/
