### ISSUE TITLE
Kinder- und Jugendarbeit

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#51]
Je öfter ich eintrage, um so problematischer wird bei Bildungsstufen "Kinder- und Jugendarbeit". Die Bandbreite ist einfach zu groß. Entweder sind die Vorlagen für Kinder - oder für Jugendliche. Selten passt beides. Ich würde vorschlagen: Arbeit mit Kindern (Kindergottesdienst, Jungschar...) und Arbeit mit Jugendlichen  oder Kindergruppen/Kindergottesdienst und Jugendarbeit.
Man hat dann auch bei den Jahreszahlenangaben von 0 - 19 alles dabei, was ja auch nicht gerade genau ist.

**Comment by staude** [comment]
Altersstufenmapping muss noch angepasst werden.

**Comment by johappel** [comment]
=> Arbeit mit Kindern => 5-13 Alterstufe

**Comment by staude** [comment]
Arbeit mit Jugendichen  =>13-19 Altersstufe
