### ISSUE TITLE
Material bearbeiten gibts nicht mehr

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#513]
![seite bearbeiten](https://user-images.githubusercontent.com/17722241/50849101-4ec34700-1376-11e9-8c56-639aa42a9917.png)

Bisher gab es im Materialpool oben unter den Reitern das Feld "Material bearbeiten", das für mich eminent wichtig ist und mit dem ich nahezu täglich arbeite. Nun steht da plötzlich "Seite bearbeiten" und lande auf einer Maske, die mir nicht weiterhilft. Ich bitte sehr darum, das wieder rückgängig zu machen.

**Comment by staude** [comment]
Das ist ja auch keine Materialseite sondern die Suche
