### ISSUE TITLE
Galerie bietet Bildbearbeitung an

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#514]
Für die Artothek habe ich die Funktion "Galerie" benutzt. Wenn man in der Galerie ein einzelnes Bild anklickt, dann wird "bearbeiten" angeboten. Ich denke, dass das für die Artothek nicht passend ist. Ich glaube nicht, dass die Künstler wollen, dass man ihre Bilder bearbeiten kann.

Bei freigegebenen Fotos mag das ja angehen. Wie gehen wir mit diesem Problem um?

**Comment by staude** [comment]
Welches Problem?
Ich lade Bild in das CMS hoch und das Sytem bietet mit die möglichkeit die rudimentär zu bearbeiten.

Weder das System noch wir kennen die jeweiligen Nutzungsrechte. Das muss schon der jeweilige Anwender entscheiden.
