### ISSUE TITLE
Anmeldung im Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#518]
Mail von Manfred Spieß:

Liebe Andrea, seit einigen Tagen komme ich nicht mehr auf dem üblichen Weg in den Materialpool. Der sah bisher so aus:
https://material.rpi-virtuell.de/
Dann: rechts oben: Anmelden/Registrieren.   
 
Die Möglichkeiten zum Anmelden finde ich dort nicht mehr ...  Hat sich was geändert? 
 
Viele Grüße
 
Manfred

Stimmt, diese Möglichkeit finde ich auch nicht mehr!

**Comment by johappel** [comment]
Ja stimmt, da war ein plugin deaktiviert. Ist wieder eingeschaltet.
