### ISSUE TITLE
Verfügbarkeit

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#52]
Bei der Bundeszentrale für politische Bildung kann man kostenlos Sachen bestellen, aber auch frei Herunterladen. In der Regel empfiehlt sich eher das Bestellen (bessere Qualität).
Soll man die Verfügbarkeit ergänzen um "Kostenloser Versand und Download" ?

**Comment by johappel** [comment]
Wichig für das Filtern ist, dass das Material kostenlos ist.
