### ISSUE TITLE
Warum erscheint dieses Video nicht richtig?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#520]
Ich verstehs nicht: warum erscheint dieses Video nicht richtig:

https://material.rpi-virtuell.de/material/klimawandel-einfach-erklaert/

**Comment by staude** [comment]
ist hier absolut korrekt

<img width="1654" alt="2019-03-16_1234" src="https://user-images.githubusercontent.com/870951/54474671-039b3980-47e8-11e9-87b5-eb1d99907891.png">


bitte ticket wieder öffnen wenn bei dir trotz browsercache löschen es noch Immer nicht erscheint
