### ISSUE TITLE
Bild erscheint meistens nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#522]
![Bild fehlt](https://user-images.githubusercontent.com/17722241/54475342-609aed80-47f0-11e9-8938-75c969565916.png)

Zur neuen Themenseite zum Klimawandel habe ich ein Bild eingefügt. Ich hab das Bild schon gesehen, aber meistens erscheint es nicht, auch nicht in Chrome. Seltsam. Das war bisher kein Problem.

**Comment by staude** [comment]
War der Artikel schon veröffentlich bevor das Bild dann eingebaut wurde?
Der war von Rocket für nicht angemeldete User schon ohne Bild im cache, und der Cache wird erst nach einem Tag verworfen - wobei er eigentlich auch verworfen werden sollte wenn der Beitrag net gespeichert wird.  Muss ich mich bei den Themenseiten noch mal ansehen ob das wirklich passiert.

**Comment by lehr-ruetsche** [comment]
Also, es ist ein Grundsatzproblem, kein Bild erscheint, wenn man eine einzelne Themenseite aufruft. Bei Anne Frank erscheint aber zum Beispiel eine Bildunterschrift. Es sind also wohl schon mal an dieser Stelle Bilder aufgetaucht, aber im Moment tun sie es grundsätzlich nicht.
