### ISSUE TITLE
Elementarbereich erscheint nicht bei "Bildungskontext"

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#523]
Ich habe eben dieses Material eingegeben:

https://material.rpi-virtuell.de/material/neues-angebot-bildung-fuer-nachhaltige-entwicklung-bne/

Eigentlich ist es Material für Kitas und ich habe auch "Elementarbereich" angehakt, dazu zusätzlich noch Grundschule. Auf der Detailseite erscheint aber unter "Bildungskontext" nur Grundschule, der Elementarbereich fehlt.
Wir haben den Elementarbereich ja mal "verschoben", kann es daran liegen?

**Comment by staude** [comment]
Derzeit werden da nur die untergeordneten Elemente ausgegegeben. Schulstufen als übergeordenete Ebene wird ja auch nicht ausgegeben.
