### ISSUE TITLE
von der Organisation zum Material

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#525]
Ich steh gerade auf dem Schlauch. Wenn ich bei dieser Organisation das Material Ramadan anklicke, taucht eine Fehlermeldung auf:
https://material.rpi-virtuell.de/organisation/izd/
Bei anderen Organisationen aber nicht. Was läuft hier falsch?

**Comment by staude** [comment]
Die Url des Materialeintrags wurde geändert von https://material.rpi-virtuell.de/material/ramadan-3 auf https://material.rpi-virtuell.de/material/ramadan/ und der Cache für nicht angemeldete Besucher war noch nicht aktualisiert vom System
