### ISSUE TITLE
Wiederherstellung bei Organisationen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#526]
Ich habe eben aus Versehen Arte als Organisation in den Papierkorb geschoben und dann wiederhergestellt, danach sah es so aus (Überblicksseite):
https://material.rpi-virtuell.de/wp-admin/edit.php?s&post_status=all&post_type=organisation&action=-1&m=0&paged=8&action2=-1

Wenn ich jetzt auf Arte klicke, kommt eine Übersicht aller Organisationen, die arte enthalten wie zum Beispiel Garten der Religionen, aber Arte kommt nicht.
Das ist mir bei einer anderen Organisation auch schon passiert, die habe ich dann endgültig gelöscht. 
Aber bei Arte möchte ich das eigentlich nicht. Zusammengefasst: Nach Löschen und Wiederherstellen funktioniert das Aufrufen der Organisation nicht mehr richtig.

**Comment by staude** [comment]
arte noch mal gespeichert, alles fein
