### ISSUE TITLE
Statistik

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#527]
Die Statistik bei den Materialabrufen gibt täglich so um die 5.000 an, mal mehr, mal weniger.
Monatlich gibt sie ca. 20.000 an. Wenn ich aber 20.000 durch 31 Tage teile im März, komme ich auf 645 Abrufe am Tag und nicht auf 5.000.
Was verstehe ich hier falsch?

**Comment by staude** [comment]
Wenn du diese beiden Graphen meinst

<img width="919" alt="2019-04-05_1722" src="https://user-images.githubusercontent.com/870951/55638513-ac293180-57c7-11e9-86e5-1538bb5f3f95.png">

Abrufe 7 Tage sind die Materal Abrufe der jeweils letzen 7 Tage, so um die 5000 am Tag.
Abrufe nach Monat sind die Anzahl der Abrufe um jeweiligen Monat (über alle Jahre seit wir diese Daten erfassen). und wenn du genau schaust sind das nicht 20.000 sondern 200.000

**Comment by staude** [comment]
und wenn. man mit der maus auf einen der punkte im graphen fährt gibt die Daten des Punkts.

<img width="457" alt="2019-04-05_1727" src="https://user-images.githubusercontent.com/870951/55638739-31144b00-57c8-11e9-9168-418a17ed9b25.png">
