### ISSUE TITLE
Vom Blog in den Materialpool

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#529]
Ich habe in meinen Blog unseren Fastengottesdienst eingetragen, der vor den Osterferien statt fand. Wir bekamen gute Rückmeldungen.
Nach der Anleitung von Jörg habe ich mich angemeldet, mich redaktionell zugelassen, mir eine Nummer geholt, eine Nummer eingetragen. Alles ausgefüllt wie vorgegeben, auch 'Aktualisieren und Übertragen' angeklickt - aber im Materialpool ist nichts angekommen. Wo müsste ich den Beitrag finden? Er ist auch nicht unter zugeliefert. Das Ganze ist schon ein paar STunden her und ich habe es eben nochmals wiederholt. Irgendwas übersehe ich oder funktioniert nicht :-(

**Comment by staude** [comment]
steht denn in dem Beitrag in der Metabox das er übertragen wurde?

Ansonsten, gib mal die url des Beitrags

**Comment by lehr-ruetsche** [comment]
https://blogs.rpi-virtuell.de/unterrichtsideen/2019/04/29/einen-tag-nicht-laestern-gottesdienst-zum-thema-fasten/

**Comment by staude** [comment]
Es müssen die Feler Beschreibung und Kurzbeschreibung ausgefüllt sein, dann ändert sich auch die Anzeige in der Metabox nach erfolgreicher übertragung.

<img width="1804" alt="2019-04-30_1221" src="https://user-images.githubusercontent.com/870951/56955823-b4645a80-6b42-11e9-9a66-63fe9fb3c6a1.png">

Der Beitrag ist jetzt im Materialpool unter https://material.rpi-virtuell.de/material/einen-tag-nicht-laestern-gottesdienst-zum-thema-fasten/    Bitte noch Beschreibung und Kurzbeschreibung anpassen, da hatte ich zum testen nur die Wörter genommen.

und ja, da bräuchte es noch mal eine ordentliche Fehlermeldung, genau wie das umgebaiut werden müsste das es auch mit Gutenberg alles sauber funktioniert.
