### ISSUE TITLE
Logo erscheint nicht in allen Browsern

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#530]
Das Logo des Bistums Berlin konnte von der Mitarbeiterin des Erzbistums nicht gesehen werden. Tatsächlich sehe ich es auf Chrome auch nicht, auf Firefox aber schon. Sie kann es weder auf Firefox noch auf dem IE sehen. Wie ist das bei euch?
https://material.rpi-virtuell.de/organisation/erzbistum-berlin/

**Comment by staude** [comment]
Das ist keine Sache des Browsers sondern des Caches, un unterschiedliche ob Angemeldet oder nicht. Jeder angemeldet User hat im WP einen eigenen Cache, weil unterschiedliche User ja unterschiedlich viel sehen können. Cache gelöscht, jetzt sollten alle das Logo sehen.
Ggf sollten wir mal die Cachedauer runtersetzen.
