### ISSUE TITLE
Bilder im Viewer

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#536]
Vom CI kamen zwei PDFs für den Marterialpool, die ich eben eingepflegt habe. Bei dem Artikel von Dr. Schweitzer erscheinen im Viewer manche Seiten nicht, es sind die mit den Bildern:
https://material.rpi-virtuell.de/material/man-kann-sagen-dass-kinder-religioes-begabte-wesen-sind-ein-gespraech-mit-dem-tuebinger-theologieprofessor-friedrich-schweitzer

**Comment by staude** [comment]
Die Material URL ist nicht mehr erreichbar. Wie lautet die aktuelle?

**Comment by lehr-ruetsche** [comment]
Frau Keuter vom CI hat mir mitgeteilt, dass die Artikel gar nicht zum Veröffentlichen gedacht waren.. Ich hab ihn auf Entwurf gesetzt.
