### ISSUE TITLE
Kann man das Schlagwort "nach oben" bringen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#537]
Eben habe ich das Schlagwort Wasser eingegeben, was eine unglaubliche Verlinkungsanzahl ergab. Selbst als ich auf Vorbereitung klickte. Dann wollte ich das Schlagwort Wasser links in der Leiste anklicken, aber das musste ich erst ein bisschen suchen. Ist es technisch möglich, dass das Schlagwort, dass man oben in die Suchleiste eingibt, auch als erstes Schlagwort in der Schlagwortliste angezeigt wird (wenn es als Schlagwort bekannt ist)?

**Comment by staude** [comment]
Nein, das Plugin bietet mir keine Möglichkeit das Ergebnis noch zu manipulieren. Die Reihenfolge ist nach Häufigkeit der Verwendung sortiert und das kann ich nicht nachträglich verändern, weil es keine Möglichkeit gibt, das zu manipulieren.
