### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#544]
Müsste dieser Artikel nicht als PDF im Viewer erscheinen? Es ist ein Einzelartikel aus einer Zeitschrift (pdf)
https://material.rpi-virtuell.de/material/from-hatespeech-to-hopespeech/
Das trifft auf alle Artikel dieser Zeitschrift zu. Mach ich was falsch?
Das sieht doch schräg aus, lauter leere Kästen: https://material.rpi-virtuell.de/material/was-fuer-ein-vertrauen-2/

Irgendwie ist in dieser Geschichte der Wurm drin. Die Artikel springen auch nicht auf die angegebene Seite (zum Beispiel #page=16) sondern immer auf die Startseite der Zeitschrift. Wenn ich aber auf der Startseite bin und auf "zurück" klicke, dann komme ich auf die gewünschte Seite.
https://akd-ekbo.de/wp-content/uploads/AKD_RU_zeitspRUng_2019-2.pdf#page=26

**Comment by lehr-ruetsche** [comment]
Leider musste ich feststellen, dass dies bei früheren Zeitungen, wo es mal gestimmt hat, auch nicht mehr stimmt. Man landet immer bei der Startseite von ZeitspRUng, nicht mehr bei der richtigen Seite.

**Comment by staude** [comment]
Der PDF Viewer ging noch nie, wenn hinter dem. .pdf  in der URL noch was hinter steht.

**Comment by lehr-ruetsche** [comment]
Gut, dann ist das eine geklärt. Aber nicht, warum nicht die richtige Seite angesprungen wird, bisher hat das gut geklappt.

**Comment by staude** [comment]
Also https://material.rpi-virtuell.de/material/zeitsprung-2018-2-israel-palaestina-und-wir/ 
zeigt im Viewer die Startseite (muss ha auch) und in den Links darunter springt mein Browser sauber auf die jeweilige Seite.

**Comment by lehr-ruetsche** [comment]
Woran könnte es dann liegen, dass es bei mir nicht klappt? An der Seitenansicht?

**Comment by staude** [comment]
Wenn  https://akd-ekbo.de/wp-content/uploads/zeitspRUng_2-2018.pdf#page=4  die Startseite anzeigt statt Seite 4, an deinem Browser oder dem Plugin/Programm das in deinem Browser such für die PDF Darstellung zuständig fühlt. Ist das in jedem deiner Browser "kaputt"?

**Comment by lehr-ruetsche** [comment]
Guter Tipp: in Chrome funktionierts. Also liegts an der Ansicht, oder dem Viewer, den Firefox benutzt. Kann ich da was machen? Ich arbeite hauptsächlich in Firefox.

**Comment by staude** [comment]
Ich kann es dir nicht sagen, bei geht es in allen Browsern, auch im Firefox.

**Comment by staude** [comment]
Ich hab aber auch nen Mac. evt kann ja @beo9999 das mal ausprobieren

**Comment by beo9999** [comment]
Geht es nur darum, ob https://akd-ekbo.de/wp-content/uploads/zeitspRUng_2-2018.pdf#page=4 auf der der vierten Seite geöffnet wird?
Bei mir (Windows 10) geht es mit den meisten Browsern (Chrome, Opera, Vivaldi, Edge).

Nicht funktionieren tut es mit Firefox (69.0) Internet Explorer (11), die zeigen immer die erste Seite an.
Interessanterweise wird auf die richtige Seite gesprungen, wenn ich die Seitenzahl bei #page= manuell in der URL-Zeile des Browsers ändere.

**Comment by lehr-ruetsche** [comment]
Hallo Bernd,

 

ich arbeite ja normalerweise mit Firefox. Und da geht das Springen auf die Seitenzahl plötzlich nicht mehr.

In Chrome geht’s.

Hast Du auch Firefox, so dass Du es testen könntest?

 

Liebe Grüße

 

Andrea

 

Von: Bernd Ost [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. September 2019 11:15
An: rpi-virtuell/rw-materialpool
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/rw-materialpool] pdf (#544)

 

Geht es nur darum, ob https://akd-ekbo.de/wp-content/uploads/zeitspRUng_2-2018.pdf#page=4 auf der der vierten Seite geöffnet wird?
Bei mir (Windows 10) geht es mit den meisten Browsern (Chrome, Opera, Vivaldi, Edge).

Nicht funktionieren tut es mit Firefox (69.0) Internet Explorer (11), die zeigen immer die erste Seite an.
Interessanterweise wird auf die richtige Seite gesprungen, wenn ich die Seitenzahl bei #page= manuell in der URL-Zeile des Browsers ändere.

**Comment by beo9999** [comment]
"Eigentlich" sollte es mit Firefox funktionieren.
Wenn ich https://akd-ekbo.de/wp-content/uploads/zeitspRUng_2-2018.pdf#page=4 in die Adresszeile kopiere lande ich aber auf der ersten Seite. 
Wenn ich dann von Hand aus dem #page=4 z.B. ein #page=14 mache und die Enter-Taste drücke springt der Viewer aber auf die richtige Seite. Merkwürdig.

**Comment by lehr-ruetsche** [comment]
Ja, und wenn du auf der Seite 1 bist und dann im Browser auf „zurück“ gehst, landest Du auch auf der richtigen Stelle.

Aber nützt ja nix, die Leute sollten gleich auf der richtigen Seite landen – und früher funktionierte es ja auch.

 

Von: Bernd Ost [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. September 2019 11:23
An: rpi-virtuell/rw-materialpool
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/rw-materialpool] pdf (#544)

 

"Eigentlich" sollte es mit Firefox funktionieren.
Wenn ich https://akd-ekbo.de/wp-content/uploads/zeitspRUng_2-2018.pdf#page=4 in die Adresszeile kopiere lande ich aber auf der ersten Seite.
Wenn ich dann von Hand aus dem #page=4 z.B. ein #page=14 mache und die Enter-Taste drücke springt der Viewer aber auf die richtige Seite. Merkwürdig.
