### ISSUE TITLE
Autorin Menzke ist doppelt vorhanden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#545]
Ich wollte bei Susanne Menzke eine Verbesserung vornehmen und habe sie aus Versehen in den Papierkorb geschoben. Bei der Wiederherstellung ist sie einfach komplett verschwunden. Ich habe sie dann nochmals neu angelegt mit 6 Einträgen. In der Zwischenzeit taucht die alte Fassung aber wieder auf, wenn man unter Autoren Menzke eingibt. Tippt man dann aber auf den alten Eintrag, erscheint er nicht. Hier brauche ich Hilfe von jemand, der sie in den Eingeweiden des PCs findet und endgültig löscht. Es ist der Eintrag mit nur einem Material und jugendlicherem Bild.

**Comment by staude** [comment]
Letztes Maerial der neuen Autorin zugeordnet. 
Vermute das die Suche das nicht nicht im index berücksichtigt hat.
Lasse SearchWP gerade neu indizieren.

**Comment by staude** [comment]
Tauch immer noch in der Suche auf
