### ISSUE TITLE
YouTube auf Themenseiten

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#547]
Eben habe ich ein relativ neues YouTube-Video, das im Materialpool einwandfrei funktioniert, in die Themenseiten eingefügt. Jetzt sieht es so aus:
https://material.rpi-virtuell.de/material/antisemitismus-begegnen/
Und zwar auf verschiedenen Browsnern.

Woran könnte das liegen?
![Youtube auf den Themenseiten](https://user-images.githubusercontent.com/17722241/64591727-c4226400-d3aa-11e9-99dc-dc18e753705d.png)

**Comment by staude** [comment]
Das Video ist auf Privat gestellt, habe daher den Materialeintrag auf Entwurf gestellt.

**Comment by lehr-ruetsche** [comment]
Er wird ziemlich oft aufgerufen. Gibt es irgendwas, was ich machen kann oder worauf ich achten müsste?

**Comment by staude** [comment]
Das Video ist nicht abrufbar, weil der Eigentümer es auf Youtube auf privat gestellt hat.
https://youtu.be/pUlYdtAXX_s
Kannst natürlich die bpb anfragen ob das nich mal wieder veröffentlich wird.
