### ISSUE TITLE
Zu viel Nationalsozialismus wird gefunden, wie kommt das?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#548]
Hallo Frank, vor einiger Zeit habe ich eine Themenseite zur Kirche im Nationalsozialismus erstellt. Das war deswegen nicht so einfach, weil der Begriff 'Kirche im Nationalsozialismus' gar nie als Schlagwort angelegt wurde. Was mir zusätzlich aufgefallen ist: wenn man das Wort "Nationalsozialismus" eingibt als Tag, kommen 1.600 Vorschläge aus dem Materialpool! Nimmt man nur das Schlagwort, sind es noch etwas über einhundert. Selbst wenn man annimmt, dass das ja eine Textsuche ist und keine Schlagwortsuche, ist das irrational. Das Wort kommt nicht in 1.600 Beiträgen vor, vor allem wenn man sich die Beiträge mal anschaut, die da angezeigt werden. Was passiert da?

**Comment by staude** [comment]
Vermutlich wegen Synonym "Drittes Reich" welches dann auf Drittes und Reich sucht.
