### ISSUE TITLE
Viel zuviele Verweise

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#549]
https://material.rpi-virtuell.de/material/zeitsprung-2019-2-religionsunterricht-in-der-digitalen-welt/
Die Zeitschrift 2019/2 zeitspRUng habe ich vor einiger Zeit eingegeben. Unter "Siehe dazu auch folgendes Material" erscheint alles mögliche, was in den letzten Tagen eingeben wurde, zum Beispiel Artikel aus dem erwachsenenforum. Irgendetwas läuft da total durcheinander.

Habe es auf zwei Browsern getestet.

**Comment by staude** [comment]
Waren zwei Fehler.
In dem Material war als Verweis das Material selbst eingetragen. Hab ich entfernt.

Das hatte zur folge das die 50 neusten Materialien dort aufgelistet wurden, weil der Filter nicht abgebrochen ist.
