### ISSUE TITLE
Vier Spalten

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#553]
Firefox stellt häufig das Material in vier Spalten dar, wenn ich ein/eb Werk/Band/Verweis hinzufüge:
![grafik](https://user-images.githubusercontent.com/17722241/65413789-7cf89200-ddf2-11e9-935b-4ace64e76c67.png)
Lässt sich schlecht lesen.

**Comment by staude** [comment]
Kann ich bei https://material.rpi-virtuell.de/material/mit-actionbound-auf-den-spuren-der-reformation-in-berlin-mitte auch mit FF (mac)  nicht nachvollziehen.
@beo9999 kannst du das mit FF (win) nachvollziehen?

**Comment by beo9999** [comment]
Nein, kann ich in mit meinem Firefox in keiner Darstellungsbreite nachvollziehen.
Eine Liste mit der Überschrift "Dieses Material ist aus der Sammlung" wird bei mir unterhalb der (bei mir drei) Spalten angezeigt.
<img width="1015" alt="2019-09-23 14_42_47-Mit Actionbound auf den Spuren der Reformation in Berlin-Mitte – Material" src="https://user-images.githubusercontent.com/12952801/65426436-8a247980-de10-11e9-98c3-7d1182439e92.png">

**Comment by lehr-ruetsche** [comment]
![Firefox-Darstellung](https://user-images.githubusercontent.com/17722241/67797172-a6f04480-fa81-11e9-9e54-a1841f244bce.png)
Sieht schon krass aus, Manfred Spieß hatte ähnliche Darstellungen. Mein Firefox ist auf dem neuesten Stand. Version 70.0 64kb

**Comment by staude** [comment]
mach mal das Fenster kleiner ...
interesanter bug, tritt im safari nicht auf

**Comment by lehr-ruetsche** [comment]
Auch nicht auf Chrome, aber auf Edge, wie ich eben festgestellt habe

**Comment by lehr-ruetsche** [comment]
Aber auch nicht immer. Dieser Link wird auf Firefox ganz normal dargestellt:

https://material.rpi-virtuell.de/material/ist-das-gerecht/

Obwohl es auch ein Werk gibt.
