### ISSUE TITLE
Darstellung

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#556]
![Firefox-Darstellung 2](https://user-images.githubusercontent.com/17722241/68586980-3506fa80-0486-11ea-8d49-97418986391c.png)

Kann man wirklich gar nichts machen? Manfred Spieß hat es auch rückmeldet. Sieht schon sehr ungut aus. Immer, wenn ein Verweis oder so ins Spiel kommt.

**Comment by lehr-ruetsche** [comment]
Auch auf Edge, nicht auf Chrome.

**Comment by staude** [comment]
Nun, diesesmal kann ich es immerhin im FF auf dem Mac nachvollziehen.

**Comment by staude** [comment]
Ah, der Fehler tritt auf, wenn es bei einem Material Verweise auf andere Materialien gibt.

**Comment by lehr-ruetsche** [comment]
Ja, zum Teil auch bei Werken und Bänden (aber nicht immer) :-(
