### ISSUE TITLE
Titel bei Organisation - Screenshot

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#56]
![dekt](https://cloud.githubusercontent.com/assets/15977289/20498091/112dd1a8-b02c-11e6-9600-4a61fe743bc4.png)
Titel wurde eingetragen, veröffentlicht, reload...
Titel erscheint nicht...

**Comment by staude** [comment]
Screenshot ist keiner da. Und bei DEKT und Worthaus sehe ich in der Anscith jeweile den Titel

**Comment by johappel** [comment]
Bei mir sieht der Screen ganz anders aus:
![grafik](https://cloud.githubusercontent.com/assets/307023/20500796/3f38a720-b037-11e6-9782-a280b8814d56.png)

**Comment by staude** [comment]
@johappel Du schaust die auch das Material DEKT an, nicht die Organisation

@lehrruetsche sieht bei mir ok aus

<img width="2164" alt="2016-11-21_2212" src="https://cloud.githubusercontent.com/assets/870951/20500921/dc45154e-b037-11e6-89dd-f07ff77eff76.png">

**Comment by johappel** [comment]
Wir können ersteinmal festhalten, dass der Titel in der Datenabnk gespeichert ist, sonst könnten ihn andere auch nicht sehen. Gute Nachricht: Alle Daten sind korrekt eingetragen.

Zu klären ist, ob eine Browsereinstellung (Cache... ) oder eine parallel geöffnete Seite (Vorschau) zu diesem Darstellungsfehler führen kann.
