### ISSUE TITLE
Dr. Titel

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#57]
https://cloud.githubusercontent.com/assets/1091954/20521587/28ad349c-b0ac-11e6-81dc-b8b1938b9543.png
Eigentlich trägt http://material.rpi-virtuell.de/autor/ute-baierlein/ den Doktortitel.
Dafür haben wir kein Feld zum Eintragen bislang

**Comment by lehrruetsche** [comment]
Sagen wir so: wir haben die Titel bisher nie eingetragen bei den Autoren. Wäre die Frage, ob wir jetzt, da wir ja eh viel genauer werden, das ändern wollen. Dann wäre aber auch die Frage, ob wir beim du bleiben. In den Feedbackmails rede ich Professoren niemals mit Du an.

**Comment by retinasilk** [comment]
Macht euch bei http://chat.comenius.de/channel/materialpool kundig, wie man akademische Titel überhaupt angibt und wohin. Frau Wullf und Frau Höbing sind dem chat beigetreten.

**Comment by empeiria** [comment]
Thema: Akademische Titel: Genau, @WuenschDigital hat rückgefragt: Ohne Titel eintragen. Auch Adelstitel sind extra notiert, was wir ja nicht machen, d.h. nicht besondere dezidierte Felder eintragen, sondern weglassen. Beispiel: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn%3D118537210
