### ISSUE TITLE
Eintragen von Werken, Bänden und Verweisen funktioniert nicht mehr

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#571]
Im bisherigen Materialpool kann ich leider keine Werke, Bände oder Verweise eintragen. Die Vorlage funktioniert nicht mehr.

**Comment by staude** [comment]
kann ich nicht nachvollziehen, hab gerade einen Material zum testen einen Werk zugeordnet.
Bitte dann am Dienstag mal zeigen

**Comment by lehr-ruetsche** [comment]
https://material.rpi-virtuell.de/wp-admin/post.php?post=22675&action=edit

**Comment by lehr-ruetsche** [comment]
Auf anderen Seiten gehts, aber auf manchen nicht, siehe oben. Ich habs mehrfach aufgemacht, neu geladen usw.

**Comment by staude** [comment]
Cache löschen, das auch das JS neu geladen wird, war noch ein JS Fehler im Kontext der Kompetenzen, der dazu führte das die JS Bearbeitung vom Browser abgebrochen wurde.
