### ISSUE TITLE
dev Nicht angegeben

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#577]
![Nicht angegeben](https://user-images.githubusercontent.com/17722241/72141174-a41fa300-3392-11ea-9784-ca675bb4da0d.png)

Habe eben die Clearingsstelle Medienkompetenz eingetragen. Es wurden diverse Einträge als nicht gemacht gemeldet, obwohl sie gemacht wurden, zum Beispiel Kurzbeschreibung, Medientyp etc...

**Comment by staude** [comment]
Ja, wie gesagt, bin ich an dem JS gerade dran, das die überprüfungen und die default werte und Abhängigkeiten macht
