### ISSUE TITLE
Autoren -> Institutionen -> Landeskirchen?

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/rw-materialpool#58]
Der Eintrag von:
http://material.rpi-virtuell.de/organisation/religionspaedagogisches-zentrum-heilsbronn/
bringt mich auf die Idee, dass hier evtl. noch die Evangelisch-Lutherische Kirche in Bayern erfasst werden sollte.
Also noch Landeskirchen und Bistümer als Taxonomie einführen?

**Comment by staude** [comment]
In welcher Situation möchte ich darauf eingrenzen? 

Müsste man dann nicht auch noch konfessionsübergreifend das Bundesland erfassen? 

Das einzigste wo ich mit das vorstellen kann wo man das braucht ist wenn das Material nur für Zugehörige eines Bundeslandes, Landeskirche zugänglich ist. Dann wäre die Filterung aber andersrum.

**Comment by empeiria** [comment]
Die Bundesländer wären wegen der Lehrpläne auch relevant. Und die Landeskirchen/Bistümer wollen evtl. auch Medien/Materialien/OER, das von ihren Mitarbeitenden erstellt wurde zusammenstellen können. Außerdem ist es ganz gut, um Konkurrenz anzuregen und zu zeigen, wie viel Hessen, Rheinland oder Württemberg produziert und wo Landeskirchen noch nachziehen müssten um ihre Präsenz auf rpi-virtuell zu stärken.

**Comment by johappel** [comment]
Die Überlegung ist interessant aber überhaupt nicht trivial:

Landeskirchliche Einrichtungen der ev. Kirchen bewegen sich teilweise auf den Territorium von 3 und mehr Bundesländern und noch mehr Bistürmern. Das wird kaum von einer Materialpoolredakteurin gewusst.
Die Einzige Sinnvolle Überlelgung die ich mir zu diesem Zeitpunkt vorstellen kann, ist, dass man die Adresse (insbesondere Postleitzahl) einer Institution mitspeichert. 
Man könnte so später regionale Bezüge in relation stellen.
