### ISSUE TITLE
dev Medien einfügen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#580]
Ich wollte mit dem kleinen Tool "Dateien hinzufügen" ein Video in das Inhaltsfeld einfügen, das hat nicht geklappt (macht ja auch im bisherigen Materialpool Schwierigkeiten). 
Ich habe dann einfach den Link ins Feld direkt eingetragen und das hat funktioniert.

**Comment by staude** [comment]
Welches Video wolltest du denn aus dem Medien einfügen,  da ist doch keins.

**Comment by staude** [comment]
das "aus URL einfügen" ist nicht WP core und nicht von uns, keine Ahnung von welchem Plugin das kommt. 
Jedenfalls generiert das einen JS Fehler
TypeError: undefined is not an object (evaluating 'delete this.obj._listeners[this.id]')

**Comment by staude** [comment]
ok, ich hab mich geirrt, das kommt von WP selbst, primär als Gutenberg Block. Aber das macht auch nichts anderes, als wenn du es im Editor einsetzt. das importiert NICHT in die Medien, sondern setzt nur in den Beitrag ein.

Habe gerade noch keine Idee wrum das aber einen JS Fehler wirft, auf einer leeren frischen WP Testseite funktioniert das ganz prima

**Comment by lehr-ruetsche** [comment]
https://dev-material.rpi-virtuell.de/wp-admin/post.php?post=41894&action=edit
