### ISSUE TITLE
mal was anderes :-)

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#585]
![grafik](https://user-images.githubusercontent.com/17722241/73653414-63613400-4689-11ea-8496-5d4bedaa97df.png)

:-) auch noch nicht dagewesen: dreispaltig mit Viewer

**Comment by staude** [comment]
https://material.rpi-virtuell.de/?post_type=material&p=42334

**Comment by staude** [comment]
Erst mal ignorieren, ist das gleiche problem wie das 4 spaltige. wenn der backendumbau fertig ist, mach ich tabula rasa im theme :)
