### ISSUE TITLE
Dossier: Frieden fördern kann nicht gelöscht werden

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#589]
Heute Mittag habe ich ein Material angelegt: Dossier: Frieden fördern. (Dossiers heissen die von Haus aus, also kein bei uns angelegtes Dossier!) Es kann sein, dass ich hier die Adresse nochmals geändert habe, von pdf in html. Auf jeden Fall lässt es sich nicht aufrufen, aber auch nicht löschen:
https://shop.sternsinger.de/dossier-2020-frieden-foerdern.html

Tja, heute Morgen haben wir noch darüber geredet ;-)

**Comment by staude** [comment]
ICh versteh nicht. Das Material "Dossier: Frieden fördern" liegt im Papierkorb.
https://material.rpi-virtuell.de/wp-admin/edit.php?post_status=trash&post_type=material

Was genau ist das Problen?

**Comment by lehr-ruetsche** [comment]
Oh, die Sachen landen wieder im Papierkorb :-)

**Comment by lehr-ruetsche** [comment]
Alles, was ich heute Mittag gemacht habe, ist im Papierkorb. Das war letzte Woche schon ein Problem, aber ich dachte, das läge an dem 'verdammten Pods' und wäre jetzt geregelt. Soll ich die Sachen selbst aus dem Papierkorb holen? Heute Mittag habe ich ein Material neu eingestellt und einige nachverbessert. Alle beginnen mit Dossier: und sind von der Kinderhilfsaktion Sternsinger

**Comment by staude** [comment]
Spricht nichts dagegen, das du die wiederherstellst.

**Comment by staude** [comment]
Ist das jetzt noch akut mit dem nicht löschen können oder kann ich das Ticket schliessen?

**Comment by lehr-ruetsche** [comment]
Ich glaube, im Moment verschwindet eher zuviel als zu wenig :-) Das Dossier: Kinder auf der Flucht, das ich gestern neu angelegt habe und die ganzen Aktionen mit den Sternsingern ausgelöst hat, ist spurlos verschwunden. Naja, sag mir Bescheid, wenn Du mit den Sternsingerdossiers durch bist, dann gehe ich nochmals drüber und trage die gelöschten wieder ein.
