### ISSUE TITLE
Autoren-Fotos

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#59]
Ich bearbeite gerade das Autorenprofil von Kai Funkschmidt von der EZW Berlin. Dort wird ein Pressephoto zur Verfügung gestellt, aber dieses ist nicht verlinkt. Ich kann es aber herunterladen und könnte es wieder hochladen. Das geht aber nicht. Ich vermute, das hat seine Gründe. Aber eigentlich könnte ich das Bild in diesem Fall verwenden, wenn ich es hochladen könnte.

**Comment by empeiria** [comment]
Da ist es doch: http://www.ezw-berlin.de/img_210/funkschmidt_210.jpg
