### ISSUE TITLE
Papierkorb

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#590]
Wow, da sind unglaublich viele Artikel im Papierkorb, krass. Da hab ich echt ein Problem, denn die Sachen von heute und letzter Woche gehören da nicht hin, aber bei den älteren Sachen könnten auch Doppelungen dabei sein. Die muss ich jetzt alle durchgehen. Auf jeden Fall wirft das System seit letzter Woche Eintragungen großzügig in den Papierkorb.

**Comment by lehr-ruetsche** [comment]
Okay, ich habs mal durchgeschaut, es sind tatsächlich  nur die von heute ein Problem.

**Comment by lehr-ruetsche** [comment]
Also, vorher habe ich alle Materialien aus dem Papierkorb geholt, die dort nicht hingehörten. Die meisten von heute, der Sagenkranz Abraham von letzter Woche. Und Schwupps, kaum eine Stunde später sind sie schon wieder da. Dabei habe ich TV geschaut :-)

**Comment by staude** [comment]
Material das zur Umstellung schon existierte hat beim erneuten speichern ein Datum in der der Vergangenheit eingetragen, was dazu führte das der Dpublizierungsjob, der einmal die Stunde läuft diese dann in den Papierkorb geschoben hat.
