### ISSUE TITLE
Sie erscheinen im Frontend und liegen im Papierkorb?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#591]
Wie geht das, dass ich zum Beispiel das Dossier zur Ernähung im Frontend unter "Materialien entdecken" sehen kann und in Wirklichkeit liegt es im Papierkorb?

**Comment by staude** [comment]
finde ich nicht im frontend.

**Comment by staude** [comment]
Depublizierungsjob ergänzt de entsprechenden Facet und Rocket Caches zu löschen.
