### ISSUE TITLE
Schlagworte werden beim ersten Speichern gelöscht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#593]
Ich dachte, ich hätte was falsch gemacht aber ich habe jetzt sehr genau darauf geachtet, wenn ich Schlagworte eingegeben habe, dass ich die ausgesuchten Schlagworte nicht nur mit enter bestätige, sondern auch anklicke. Aber egal, wie ich es mache, nach dem Speichern fehlen die Schlagworte.

**Comment by lehr-ruetsche** [comment]
Okay, sie werden auch nach dem zweiten Speichern gelöscht.

**Comment by lehr-ruetsche** [comment]
Sie werden auch gelöscht, wenn man sie nach dem Veröffentlichen einträgt und aktualisiert.

**Comment by lehr-ruetsche** [comment]
Beim zweiten Eintragen nach dem Veröffentlichen und Aktualisieren hat es geklappt.

**Comment by staude** [comment]
Sorry, hab vergesseb einen Haken zu setzten in den Feldern, sollte nun korrekt funktionieren
