### ISSUE TITLE
(inherit)

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#594]
Bei den Bändern sucht man einen Eintrag und öfters steht dahinter in Klammern (inherit)
![inherit](https://user-images.githubusercontent.com/17722241/75241485-75388180-57c6-11ea-9e92-7992c4f8559a.png)

**Comment by staude** [comment]
Ja, das sind die, die nicht mehr erreichbar sind, worüber wir vorhin gespochen hatten.
