### ISSUE TITLE
Nochmals Bände

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#597]
Dossier: Frieden fördern ist im Backend richtig eingetragen, im Frontend erscheint zuviel. Der untere Teil dürfte nicht erscheinen.

**Comment by lehr-ruetsche** [comment]
Ebenso bei Dossier: Klimawandel und Bewharung der Schöpfung.

**Comment by staude** [comment]
Was genau meinst du? Der Text ist doch vollständig. Und Darunter tauchen die Verweise auf, die ich noch nicht für alle Dossiers angefasst habe, kommt nachher.
Aber bei dem genannten sind es genau die, die derzeit als Verweise drinstehen. Oder versteh ich was falsch?

**Comment by lehr-ruetsche** [comment]
Ja, aber sie erscheinen zweimal. Du musst sie nicht mehr anfassen. Sie müssten jetzt alle in Ordnung sein. Zum TEil fehlten Schlagworte, zum Teil waren falschen Zahlen drin. Nur bei diesen beiden tauchen die verweise sozusagen zweimal auf.

**Comment by staude** [comment]
Sorry, ich weiss nicht was du meinst mit doppelt. 
Bei mir sieht das so aus

<img width="256" alt="2020-02-27_1300" src="https://user-images.githubusercontent.com/870951/75443253-499dce80-5961-11ea-823e-d3e38ace6481.png">

**Comment by staude** [comment]
Ausser das das Werk falsch ist, gibts bei den Verweisen keine doppelten

**Comment by lehr-ruetsche** [comment]
![Dossier Kinderarbeit](https://user-images.githubusercontent.com/17722241/75448840-3f350200-596c-11ea-99d4-5ce2c642bf9b.png)

**Comment by lehr-ruetsche** [comment]
![Dossier Klimawandel](https://user-images.githubusercontent.com/17722241/75449261-f3cf2380-596c-11ea-9a54-1ebaa2c70df5.png)

**Comment by lehr-ruetsche** [comment]
Es tragen sich automatisch WErke ein! Ich habe alle acht Dossiers überarbeitet und sie waren in Ordnung und jetzt stehen bei der Hälfte Werke drin, die ich garantiert nie eingetragen habe. Ich habe bei den Dossiers keine Werke eingetragen. Und bei allen darauf geachtet, dass nur in Verweise etwas steht.
Naja, Du musst es doch nochmals anfassen.
