### ISSUE TITLE
Organisationen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#598]
Ich habe eben versucht, beim "Haus der kleinen Forscher" das Logo zu ändern. Als ich aktualisiert hatte, wollte ich mir die Seite anschauen und habe wie üblich oben auf die Leiste geklickt. Aber ich bin dann nicht auf dem speziellen Eintrag der kleinen Forscher gelandet, sondern auf der Gesamtseite der Organisationen. Jetzt im Moment kann ich die kleinen Forscher gar nicht mehr aufrufen.

**Comment by staude** [comment]
Da war bein speichern von Orgas tatsächlich für die Titelgenerierung ein verweis auf Pods.
Ist behoben
