### ISSUE TITLE
Abstand stimmt wieder nicht mehr

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#599]
Eben habe ich diesen Bibor-Eintrag gemacht:
![grafik](https://user-images.githubusercontent.com/17722241/75751106-fd1e0e80-5d25-11ea-9a56-3b071872c6da.png)

Und das mit den Abständen hat leider nicht funktioniert.

**Comment by staude** [comment]
Mit https://github.com/rpi-virtuell/rw-materialpool-theme/commit/a16027473592e8c11202bef9635cb6fda1d4ee41 auch in diesen Fällen gefixt
