### ISSUE TITLE
Speichern

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#60]
Was mir auch schon öfters passiert ist und anderen sicher auch noch passieren wird: Man trägt das Material ein und kann natürlich keinen Autoren eintragen. Den muss man ja extra machen. Also denkt man sich: mach ich schnell den Autoren, wechselt schupps hinüber und zack, schon sind alle bisher angelegten Materialien weg. Ich müsste es eigentlich wissen, und trotzdem passiert es mir immer noch...
Dann hat man alles gespeichert, wechselt wieder zum Material, muss alles neu anlegen, kommt zum Autor und denkt, Hurra, den gibt's ja jetzt und dann findet man ihn nicht, erinnert sich daran, dass man ihn zwar gespeichert aber vielleicht doch nicht veröffentlicht hat, wechselt wieder zum Autor und schwupps....

**Comment by staude** [comment]
Links via Contextmenü "öffnen im neuen tab" oder alternativ "im neuen Fenster" öffnen. 
Oder Strg(glaub ich jedenfalls das es unter windows strg ist)  gedrückt halten beim Klick auf eine. Link öffnet auch im neuen tab.

**Comment by staude** [comment]
Zu früh gespeichert 😜
----

Was war jetzt eigentlich die Frage oder der Fehler?

**Comment by lehrruetsche** [comment]
Weder Frage noch Fehler nur Mitteilung: nervig, dieses System :-)

**Comment by empeiria** [comment]
Man kann doch das Material speichern und schließen auch ohne den Autor. Dann den Autor anlegen und das Material beim Autor eintragen. 
Das reicht aus. 
Beim Material erscheint dann umgekehrt automatisch der Autor.
Mehrere Tabs sind tückisch, weil man die Aktualisierung des Autors dann nicht automatisch sieht.

**Comment by johappel** [comment]
Ivh denke dass der von Andrea beschrieben Workflow im Sinne von Jögs Kommentar effektiver würde wenn Sie in zwei schritten
1. Material anlegt und speichert
2. Autor anlegen und *dort* das neue Material zuordnen.... (also nicht mehr zurück zum Material geht)
