### ISSUE TITLE
Es wurden Sachen als fehlend angezeigt, die angehakt waren

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#600]
![grafik](https://user-images.githubusercontent.com/17722241/75807050-07232a00-5d85-11ea-8c1a-08808fd80891.png)

Es werden Sachen als fehlend angezeigt, die eingetragen sind (Medien, Bildungsstufe). Browser: Chrome.
Mal von der Beschreibung abgesehen, die immer fehlt. Aber ansonsten hat es ganz gut funktioniert.

**Comment by staude** [comment]
Kann ich unter CHrome nicht nachvollziehen, schau mir das noch mal auf nem Chrome unter Windows an.
@beo9999 kannst du das reproduzieren? Material: https://material.rpi-virtuell.de/material/wissenspool-christentum/?sq=https%3A%2F%2Fmaterial.rpi-virtuell.de%2Ffacettierte-suche%2F

**Comment by beo9999** [comment]
Also ich hatte nur diesen einen Eintrag angeschaut https://material.rpi-virtuell.de/wp-admin/post.php?post=42787&action=edit , und in Chrome waren bei mir die roten "unvollständig"-Anmerkungen auch nicht vorhanden.

**Comment by staude** [comment]
Danke, für Andrea war es heute dann auch nicht mehr reproduzierbar
