### ISSUE TITLE
Abstände

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#601]
https://material.rpi-virtuell.de/material/wissenspool-christentum/

Ich werde ungern angeranzt und mache mich auch nicht wirklich gerne unbeliebt. Aber diese Seite habe ich eben eingegeben. Nichts ist reinkopiert. Normalerweise waren die Abstände zwischen den Punkten früher einzeilig und ansonsten zweizeilig. Jetzt sind sie halt überall größer.

**Comment by staude** [comment]
Dann war das n2br einbauen wohl doch etwas vorschnell
