### ISSUE TITLE
Aktualisieren dauert

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#604]
Wenn ich Materialien eingebe und etwas aktualisiere, dauert es in etwa eine halbe Minute. Dann fällt mir ein, dass ich noch ein Häkchen vergessen habe, ein Schlagwort, irgendwas, jeweils wieder eine halbe Minute.

**Comment by staude** [comment]
Bei Aktualisieren passiert sogar noch mehr als beim neu anlegen. 
Alle Werke, Bände, Verknüpfungen, Themenseiten, Startseite müssen geprüft werden ob die Verknüpfung noch da ist oder weg ist und deren Inhalt muss aus dem Cache entfernt werden damit es beim nöchsten Aufruf den evt geänderten Inhalt zeigt.
