### ISSUE TITLE
Neues Schlagwort anlegen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#605]
Eben wollte ich Augmented Reality anlegen (innerhalb der Maske), das ging nicht. Dann habe ich in den Bibliotheksvorschlägen nachgeschaut, dort hieß es "erweiterte Realität". Also das Schlagwort gibt es eigentlich. Aber es war mir nicht möglich, es unter dem plus-Zeichen bei Schlagworte anzulegen. Gestern ging es noch problemlos. Würdest Du es bitte mal mit genau diesen Begriffen testen?

**Comment by staude** [comment]
Bei dem Versuch das hinzuzufügen bekomme ich diese Meldung.
<img width="318" alt="2020-03-05_1047" src="https://user-images.githubusercontent.com/870951/75969343-1a421100-5ecf-11ea-9b72-8a751ab5e451.png">
Interessanterweise kann https://xgnd.bsz-bw.de/Anfrage es händisch auflösen, bei der Abfrage vom Materialpool aber nicht.  

Hab Normwort/Schlagwort und Synonyme erst mal von Hand eingetragen.
