### ISSUE TITLE
Material wird als unvollständig angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#606]
Ich habe eben dieses Material eingetragen:

https://material.rpi-virtuell.de/material/augmented-reality-technische-spielerei-oder-bereicherung-fuer-den-unterricht-bpb/

Es wird als unvollständig angezeigt, aber ich weiß nicht, warum. Es wurde vieles in den letzten Tagen angezeigt, aber nicht alles. Ich dachte, es liegt vielleicht am Handverlesen, aber das ist auch angehakt. Was läuft schief?

**Comment by staude** [comment]
@lehr-ruetsche Was meinst du? Kann nicht erkennen was im Backend eingepflegt ist und im Frontend fehlen soll.

**Comment by staude** [comment]
doppelt #600
