### ISSUE TITLE
Doppelung

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#608]
Bildungsstufen und Medien kommen in der Eingabemaske an der Seite nochmals vor. Hat das einen bestimmten Grund?

![Doppelung](https://user-images.githubusercontent.com/17722241/76296809-0f182800-62b7-11ea-91aa-4af4a561025e.png)

**Comment by staude** [comment]
nein, sind ausgeblendet. bitte  browsercahce leeren
