### ISSUE TITLE
Überschrift?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#609]
Wenn ich mich recht erinnere, stand an dieser Stelle mal eine Überschrift:
![Überschrift fehlt](https://user-images.githubusercontent.com/17722241/76456863-0a976080-63d8-11ea-93f6-90798f3dfd93.png)

**Comment by lehr-ruetsche** [comment]
Kann sich noch jemand erinnern?

**Comment by staude** [comment]
Ja, ist aber in dem Feld gelöscht worden

![2020-03-12_1135](https://user-images.githubusercontent.com/870951/76512872-b59a2f80-6455-11ea-86af-7c425722d255.png)

Da stand sonst "Unser besonderer Tipp:"
