### ISSUE TITLE
Bildschirmhalbierung

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#61]
Wenn ich meinen Bildschirm teile, was ich bei Materialpooleinträgen immer mache, sind die Fensterchen, die sich zum Eintragen zum Beispiel bei dem Autor oder der Organisation öffnen, sehr klein. Selbst wenn man den Autor nur noch aussuchen muss, so kann man doch seinen Namen kaum lesen. Entweder kann man die Fenstergröße ändern oder ich brauche einen zweiten Bildschirm :-)

**Comment by staude** [comment]
Schriftgrösse im Browser größer stellen ?! Oder was ist genau das Problem?

**Comment by lehrruetsche** [comment]
Ich mach das nächste Mal einen Screenshot, wenn es auftaucht. Das Fensterchen, das sich öffnet, ist gefühlt 1 cm breit und 3 cm hoch im Fenster.

**Comment by staude** [comment]
Ja bitte. Ich habe im Moment keine Vorstellung was du meinst.

**Comment by lehrruetsche** [comment]
![fensterchen](https://cloud.githubusercontent.com/assets/15977289/20532240/8e836746-b0d9-11e6-9059-a0d7b48e95d8.png)

**Comment by staude** [comment]
Ah, ok. Verstehe - da müssen wir mal das PODS CSS überschreiben.
