### ISSUE TITLE
Das Bild taucht nicht auf

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#610]
![Das Bild taucht nicht auf](https://user-images.githubusercontent.com/17722241/76682125-96d49e00-65f9-11ea-9203-29fff4106bd5.png)
Ich habe es schon vor einiger Zeit eingegeben, aber nur die Quelle taucht auf, das Bild nicht. Sämtliche Caches geleert, die mir irgendwie eingefallen sind.

**Comment by lehr-ruetsche** [comment]
![Ohne Bild](https://user-images.githubusercontent.com/17722241/76683338-a35df400-6603-11ea-9521-9cf6059d15c1.png)
Hier habe ich ein Bild geändert. Obwohl im Backend alles okay ist, sieht es im Frontend so aus.

**Comment by staude** [comment]
1: muss ich mir im code ansehen 

2: da war als cover url die eigentliche seite https://www.kinderfunkkolleg-trialog.de/ eingetragen, hab ich entfernt.
