### ISSUE TITLE
Schlagworte wandeln sich nicht

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#614]
Eben habe ich das Wort Abtreibung eingegeben und bisher wandelt sich das immer in Schwangerschaftsabbruch oder etwas ähnliches. Diesmal sagte das Progamm nur: Wort findet sich nichtoder so ähnlich.

**Comment by staude** [comment]
Kann ich nicht nachvollziehen, funktioniert alles prima. 
Irgendwelche JS Fehler evt?  Wollen wir per zoom mal zusammen schauen
