### ISSUE TITLE
Materialpooleinträge werden nicht angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#621]
In Edge und Chrome fehlen die letzten 7 Einträge, in Firefox die letzten 3. Alle sind von gestern und müssten eigentlich da sein. Stand: Mittwochmorgen, 8.30 Uhr.

**Comment by staude** [comment]
ob Safari, FF, Chrome, angemeldet oder nicht. ich seh auf allen die neuste, die auch im Backend  als neuste dargestellt werden.

**Comment by lehr-ruetsche** [comment]
Auf der Startseite wird alles angezeigt, aber nicht auf "Entdecken", nach wie vor nicht.

**Comment by beo9999** [comment]
Eben getestet: "Material entdecken" https://material.rpi-virtuell.de/facettierte-suche/

Chrome (angemeldet, anonym), MS Edge (anonym), Firefox (anonym): Die letzten 6 Materialien entsprechen jeweils denen auf der Materialienliste im Backen. Aktuellstes ist der Eintrag "Kommt herein – der Himmel soll heut offen sein" (Kurt Mikula).

Ich bekomme allerdings in der Konsole Fehler angezeigt:
Mixed-content-Warnung:
http://material.rpi-virtuell.de/wp-content/plugins/wp-postratings/images/stars/rating_off.gif

Schlimmer: Wenn ich nicht eingeloggt bin wird bei mir nachvollziehbar nur das Bild des aktuell zweiten Eintrags angezeigt ("Abschlussgottesdienste in kleinen Formen in Zeiten von Corona").
Wenn ich genau hinschaue: Bei einem harten Reload werden die anderen Bilder (z.B. das blau-grüne beim Kurt-Mikula-Eintrag für einen kurzen Moment angezeigt, dann aber ausgeblendet.

<img width="1449" alt="2020-06-10 13_02_33-Facettierte Suche – Material -  InPrivate  ‎- Microsoft Edge" src="https://user-images.githubusercontent.com/12952801/84261100-7c885e80-ab1b-11ea-9c8f-65e371b4da5e.png">

<img width="1449" alt="2020-06-10 12_58_57-Facettierte Suche – Material -  InPrivate  ‎- Microsoft Edge" src="https://user-images.githubusercontent.com/12952801/84261191-a3df2b80-ab1b-11ea-9271-7455d58a69bc.png">
