### ISSUE TITLE
Bild wird auf der Startseite nicht angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#622]
Ich habe heute einen Eintrag gemacht "So groß wie ein Baum" und diesen mit einem Baumbild versehen. Dieses Bild wird auf der Startseite unter "Neu im Materialpool" nicht angezeigt. Das ist in dieser Woche schon mal passiert mit dem Beitrag: "Abschlussgottesdienst in kleinen Formen..." Dort habe ich sogar das Bild gelöscht, neu hochgeladen usw. Caches gelöscht, alles was mir eingefallen ist, das Bild ist nicht erschienen. Ich habs dann einfach ruhen lassen, aber jetzt passiert eben genau dasselbe wieder. Andere Bilder werden problemlos angezeigt. Hmhm.

**Comment by staude** [comment]
Sowohl angemeldet als auch nicht angemeldet in verschiedenen Browser bekomm ich das angezeigt. Kann ich leider nicht reproduzieren. @beo9999 was siehst du?
