### ISSUE TITLE
Wie kann ich eine CC-Lizenz wieder löschen?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#624]
Diesem Material habe ich versehentlich eine CC-Lizenz gegeben:

https://material.rpi-virtuell.de/material/behindert-sein-oder-behindert-werden/

Nun kriege ich sie nicht mehr raus.

**Comment by lehr-ruetsche** [comment]
Dass man einmal eingetragene CC-Lizenzen nicht mehr löschen kann ist nach wie vor so und sehe ich wirklich als Problem!

**Comment by staude** [comment]
Lizenzfeld hat nun ein x zum löschen der Auswahl

<img width="1323" alt="2020-10-26_22-52-00" src="https://user-images.githubusercontent.com/870951/97232763-0b053000-17de-11eb-8d3a-043579764f33.png">

Bei dem genannten Material hab ich es entfernt und das Material gespeichert.
