### ISSUE TITLE
Schlagwort-Facette wird beim Seitenweisen blättern nicht weitergegeben

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/rw-materialpool#628]
z.b. https://material.rpi-virtuell.de/facettierte-suche/?fwp_schlagworte=Lied weiterblättern auf Seite 2 verliert die Facette.

**Comment by johappel** [comment]
Facettirung der Schlagworte wurde erst einmal über fselect glöst. @lehrruetsche findet die Lösung ok.
