### ISSUE TITLE
EZW

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#63]
Es gibt das Portal der EZW = Organisation.
Diese veröffentlicht verschiedenen Publikationen: Materialdienst, Lexikon und anderes mehr.
Diese Publikationen haben wieder Artikel.
Bei der Organisation werden alle Publikationen auf der gleichen Ebene aufgezählt, obwohl zum Beispiel der Materialdienst ein Werk ist und "Reichsbürger" und "Konversionen" Bände sind.
Vermutlich überfordert diese Konstellation das System.
http://material.rpi-virtuell.de/organisation/evangelische-zentrale-fuer-weltanschauungsfragen-ezw/

**Comment by staude** [comment]
Hast du mal URLs das man sich das mal ansehen kann?

**Comment by staude** [comment]
Auf der Organistionsseite werden alle Materialien der Orga aufgelistet, das ist erst einmal unabhängig von möglichen Werk-Band verknüpfungen.  Werk-Band Verknüpfungen sind aber auch Orga unabhängig. Theoretisch können Bände in Zusammenarbeit mit unterschiedlichen Orgas entstanden sein. Daher macht es imho keinen Sinn in dieser Ansicht eine Hierachie ausgeben zu wollen, die unter umständen nicht vollständig ist.
