### ISSUE TITLE
Einträge werden nicht angezeigt

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#630]
Ich habe eben die Facette Gebet/Lied bei Kurt Mikula nachgetragen und dabei mit mehreren offenen Seiten des Materials gearbeitet.
Leider wurden die Veränderungen auch nach mehreren Reloads, leeren sämtlicher Caches und wechseln von Browsern nicht angezeigt. DAs ging früher ganz schnell. Jetzt kommt die Anzeige oder auch nicht. Es ist mühselig, wenn man dreimal die gleiche Seite aufruft, um festzustellen, dass man das Häkchen natürlich gesetzt hat. Jetzt hör ich auf. Morgen früh seh ich weiter.

**Comment by lehr-ruetsche** [comment]
Leider hat die Zeit, die seit gestern vergangen ist, auch nichts genutzt. Bei mehreren Einträgen, bei denen ich Gebet/Lied nachgetragen habe, wird dies nicht angezeigt.

**Comment by staude** [comment]
Neu hinzugefügter Medientyp "Gebet/Lied" wird in der Backendliste nicht immer angezeit, sieht so aus das der Backendcache der Materialliste nicht immer zuverlässig gelöscht wird
