### ISSUE TITLE
Komische Zeile in der Frontpage des Materialpools

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#634]
![Komische Zeile](https://user-images.githubusercontent.com/17722241/88633608-86f3bd00-d0b5-11ea-8ccd-5f0c8d830346.png)

**Comment by lehr-ruetsche** [comment]
War gestern auch schon mal zu sehen, ist dann beim Weiterarbeiten verschwunden

**Comment by staude** [comment]
ja, kann ich bestätigen. Kommt von der Customizer-Einbindung, ist daher nur sichtbar bei angemeldeten Benutzern mit entsprechenden Rechten.  Sieht so aus, das aus irgendeinem Grund das in die Seite gerenderte JS nicht mehr von script tags umschlossen ist.

**Comment by staude** [comment]
JS mionifizierung des Cachingplugins ist der Verursacher.
