### ISSUE TITLE
Gleiche Adressen?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#638]
Dieses Material von 2019: https://material.rpi-virtuell.de/material/religion-unterrichten-in-der-grundschule-erntedank/
und dieses Material und dieses Material von 2020 haben diesselbe Adresse, oder? https://material.rpi-virtuell.de/material/religion-unterrichten-in-der-grundschule-erntedank-2/

**Comment by lehr-ruetsche** [comment]
Leider wurde es nicht angezeigt.

**Comment by staude** [comment]
ja, zeigen beide auf http://www.rpz-igb.de/fileadmin/user_upload/rpz/ingbert/Gruss_aus_der_Kueche/Reader_LB_4.3_GadK.pdf

**Comment by staude** [comment]
Hmm. ich bekomme zrae kein Hinweis das die URL existiert, aber die verschwindet sofort aus dem Eingabefeld

**Comment by lehr-ruetsche** [comment]
Ja, stimmt, das ist mir gestern passiert und ich konnte es nicht recht einordnen. Beim Nachfassen waren die Adressen dann irgendwann drin.
Dann lösche ich jetzt die Eingabe von gestern.
