### ISSUE TITLE
Nochmals gleiche Adresse

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#639]
Das Problem gibt es immer noch: http://www.dihorst.de/
Das lässt sich leicht vergleichen. Ich habe es eben nochmals eingegeben und es wurde nicht angezeigt, dass das Material schon vorhanden ist. Es ist auch kein sicherheits S dazugekommen oder so...

**Comment by staude** [comment]
Doppelung von #638
