### ISSUE TITLE
Reichsbürger tauchen bei den Bänden nicht auf

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#64]
Also, ich habe zuerst "Reichsbürger" eingegeben. (Band)
Dann habe ich "Konversion/Religionswechsel" eingegeben. (Band)
Dann habe ich die Organisation eingegeben (EZW) und das Werk, nämlich den Materialdienst des EZW.

Erschienen sind bei der Organisation Werke und Bände gleichwertig, ohne Hierarchie. (siehe Issue 34)
Erschienen sind beim Materialdienst die beiden Bände "Reichsbürger" und "Konversion". Alles in Ordnung
Erschienen sind bei "Konversion" das Werk "Materialdienst", der Band "Reichsbürgerbewegung" aber bei allen Bänden nur die "Konversion". Müsste hier nicht auch noch die "Reichsbürgerbewegung" auftauchen? Sie wurde bei Band eigegeben.
Erschienen sind bei der Reichsbürgerbewegung, die ich als erstes eingetragen habe: als Werk "Konversionswechsel" - der ist eigentlich ein Band und bei den Bänden nur die "Reichsbürgerbewegung" selbst, also hier hat es nicht so gut funktioniert. Es ist offensichtlich schwierig beim ersten Material, es müsste nachgearbeitet werden. Jetzt weiß ich ja noch alles und kann das auch machen, aber in Zukunft werden ja oft größere Zeiträume dazwischen liegen. 
http://material.rpi-virtuell.de/material/reichsbuergerbewegung/

**Comment by johappel** [comment]
![image](https://cloud.githubusercontent.com/assets/307023/20561588/842cb738-b17f-11e6-9ed3-a10d4ccc1dac.png)
Du hast in Konversion/Religionswechsel  unter Materialdienst eingeordnet und Reichsbügerbewegung unter Konversion/Religionswechsel

**Comment by staude** [comment]
@lehrruetsche 
Liebe Andrea, ich habe nicht verstanden was jetzt die Frage ist. Da aber immer von beiden Seiten eine Zuordnung gemacht werden kann muss auch nicht das erste Material nachgearbeitet werden. Lass uns das morgen noch mal durchgehen.
