### ISSUE TITLE
Gelbe Hinterlegung bei religionspädagogischen Instituten funktioniert nicht mehr

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#640]
Mir ist schon vor einiger Zeit aufgefallen, dass das mit der hellgelben Hinterlegung bei religionspädagogischen Instituten nicht mehr so funktioniert. Aber heute ist es extrem, weil die letzten ca. 10 Beiträge alle gelb sein müssten, es aber nicht sind.

Die Sache mit den Werken und Bänden funktioniert noch immer nicht richtig.

**Comment by staude** [comment]
nach erneuten speichern eines Materials wird das jeweils behoben
