### ISSUE TITLE
Übersichtlichere Gestaltung bei Themenseiten möglich?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#644]
Wenn ich auf den Themenseiten im Backend arbeite und in den Feldern die Titel zuordne, kann ich die Titel in der rechten Spalte, die ich bereits zugeordnet habe, sortieren, was ich einen tollen Fortschritt finde. Allerdings kann ich sie nie alle sehen, sondern muss immer dazu scrollen, das macht das Sortieren schwieriger. Die Textfelder dagegen, die darunter stehen, brauch ich fast nie und sie nehmen sehr viel Platz ein. Könnte man daran etwas ändern? Ich kann es gerne im Bildschirmteilen zeigen, was ich meine.

**Comment by lehr-ruetsche** [comment]
![Themenseiten Titel](https://user-images.githubusercontent.com/17722241/92739590-56be6000-f37d-11ea-9ead-9e012194e959.png)

**Comment by lehr-ruetsche** [comment]
![Themenseiten Textfeld](https://user-images.githubusercontent.com/17722241/92739956-a7ce5400-f37d-11ea-83dc-91de8d425686.png)

**Comment by staude** [comment]
@lehr-ruetsche so oder noch mehr platz?

<img width="585" alt="2020-09-15_14-12-13" src="https://user-images.githubusercontent.com/870951/93208863-8c888d80-f75d-11ea-9f7c-0348d7691db4.png">

**Comment by lehr-ruetsche** [comment]
Geht es so, dass ich rechts nicht mehr scrollen muss - oder ist das technisch unsinnig?

**Comment by staude** [comment]
ich kann es noch größer machen, aber nicht dynamisch nach menge des Inhalts rechts. Du kannst da ja theoretisch tausende Elemente drin haben.

**Comment by staude** [comment]
so? 

<img width="1214" alt="2020-09-15_16-09-02" src="https://user-images.githubusercontent.com/870951/93221261-d4171580-f76d-11ea-9979-7f0bd0e83508.png">

**Comment by lehr-ruetsche** [comment]
Okay, da hast Du recht, ich denke, wenn ca. 12 reinpassen, mehr werden es eher selten sein. Geht das?

**Comment by staude** [comment]
also so wie auf dem letzten screenshot...
