### ISSUE TITLE
Breite (oder eher Tiefe) des Feldes bei Themenseiten

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#646]
Ich lege gerade eine neue Themenseite an. An den Feldern hat sich für mich nichts verändert: ich kann genau sechs Einträge sehen, dann hört das Feld auf. Das ist nicht userfreundlich, oder wie das heißt.

**Comment by lehr-ruetsche** [comment]
Kannst Du nicht die Info-Felder kleiner machen und 'Material in dieser Gruppe' größer?

**Comment by staude** [comment]
Doppelung von #644 
Tickets werden hier automatisch mit dem übertragen der Codeänderung geschlossen, damit ist es nicht automatisch auf den Materialpool ausgerollt. Hab ich gerade gemacht.
