### ISSUE TITLE
Dauerbrenner: Doppelungen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#647]
Habe letzte Woche das Dossier zum Thema Ehe der Süddeutschen eingegeben - es war schon drin, tupfengleich, und wurde nicht erkannt. Ich lass es mal noch, damit Du es Dir anschauen kannst:

https://material.rpi-virtuell.de/material/ehe/

https://material.rpi-virtuell.de/material/ehe-alles-zum-thema/

**Comment by staude** [comment]
Doppelung von #638
