### ISSUE TITLE
Organisation: Titel taucht nicht auf

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#65]
Backend: 
![organisation ekir backend](https://cloud.githubusercontent.com/assets/15977289/20534156/5f07b736-b0e0-11e6-9c2f-ce86e0b97be0.png)

Frontend:
![organisation ekir frontend](https://cloud.githubusercontent.com/assets/15977289/20534166/68b18578-b0e0-11e6-9a97-6b5bf260b5e2.png)

**Comment by staude** [comment]
Bei mir ist das ok. 
<img width="1553" alt="2016-11-22_1824" src="https://cloud.githubusercontent.com/assets/870951/20534304/146931d6-b0e1-11e6-9561-173f831549a6.png">

Kannst du das bitte noch mal mit dem Firefox gegenprüfen. Nicht das das irgendso ein obskures IE Problem ist.

**Comment by empeiria** [comment]
Bei mir wird auch http://material.rpi-virtuell.de/organisation/evangelische-kirche-im-rheinland-ekir/ sowohl in Chrome als auch in Firefox korrekt angezeigt.
Hast du schon verschiedene Browser probiert, @lehrruetsche ?
