### ISSUE TITLE
Organisation taucht nicht auf

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#66]
Ich habe zuerst das Material eingetragen: STille
Dann die Organisation: EKir
Danach habe ich beim Material die EKiR nachgetragen, also die Organisation. Aber trotz speichern und Reload und natürlich veröffentlichen, taucht die Organisation nicht auf:
http://material.rpi-virtuell.de/material/gottes-ja-in-der-stille-hoeren/?preview=true

**Comment by empeiria** [comment]
Unter der Organisation ist das Material zu sehen:
http://material.rpi-virtuell.de/organisation/evangelische-kirche-im-rheinland-ekir/
Unter dem Material allerdings nicht. Selbes Ergebnis wie @lehrruetsche
