### ISSUE TITLE
Autoren

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#67]
Eben habe ich einen Artikel zum Abendmahl des RPI Loccum eingegeben. Dieser Artikel hat drei Autoren. Bei einem solchen Artikel MUSS ich aber die Autoren angeben. Jetzt muss ich drei Autoren extra anlegen, von denen ich nicht weiß, ob sie jemals wieder auftauchen. Das ist jetzt echt aufwändig! *Mecker* Einfach Namen eingeben wäre manchmal schon schön...

**Comment by staude** [comment]
Bereits unter #1 erfasst
