### ISSUE TITLE
Bildurl

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#68]
Ich habe eben Matthias Hülsmann bei den Autoren eingegeben, der unter seinem Bild extra ein Copyrightzeichen hat. Ich habe nicht das Bild kopiert, aber die Bildurl.
Ist das jetzt rechtskonform oder nicht?

**Comment by empeiria** [comment]
Ich denke schon, dass es ok ist. Weil wir ja keine Kopie erstellen, sondern einbetten.
Die Frage ist, ob wir die Lizenz oder Quelle des Bildes anzeigen müssen?

**Comment by johappel** [comment]
Die Lizenz nicht aber die Quelle in Textform wäre ja gut machbar

**Comment by staude** [comment]
Template anpassen: Bild URL als Bildunterschrift ausgeben.
