### ISSUE TITLE
Website des Autoren

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#69]
Die wenigsten Autoren haben eine Website. Aber viele haben eine Website bei einer Organisation, so wie bei Matthias Dingens das Gütersloher Verlagshaus oder bei Michael Utsch die EZW. Bisher habe ich diese Seiten genommen. Ist das okay? Oder wirklich nur eigene Seiten?

**Comment by empeiria** [comment]
Viele sind ja auch auf ihren Institutsseiten aufgeführt - allerdings ebenfalls nicht mit eigener Seite.
Ich habe dann eher die "Über uns" Seite verlinkt - Die gleiche Frage also wie @lehrruetsche:
Ist das okay?

**Comment by johappel** [comment]
Also wenn der Autor eine eigene Visitenkarte pflegt dann ist die Url ja in der Regel identisch mit dem Namen des Autors. Beispiel: http://uwe-martini.de . Falls eine solche zufällig Seite bekannt ist, würde ich der den höchsten Stellenwert geben. Ansonsten würde ich es genau wie Andrea halten.
