### ISSUE TITLE
Verweis

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#72]
Ich gebe gerade ein sehr ungewöhnliches Material ein: Glaubenssache
http://www.sputnik.de/sendungen/tagesupdate/audio-208144.html

Zu dieser Seite gibt es eine weitere Internetseite mit einer graphic Novel und auch YouTube-Seiten. Eigentlich könnte ich hier nur Verlinkungen eingeben, es geht um eine Nebenseite sozusagen. Aber das geht nicht, ich muss mit Material verlinken. Ich bin nicht sicher, ob das bei Verweisen immer so gut ist, dass man hier nur weiteres Material eingeben kann und nicht einfach nur einen Link irgendwo hin. Ich komme mit diesem Hinweisfeld gar nicht aus rpi-virtuell heraus. Ich kann nichts außerhalb eingeben. 
In diesem Fall könnte ich das gleichlautende Material auch eingeben, aber es wäre eigentlich nicht notwendig. In meinen Augen würde ein Link genügen. Entweder ergänzen oder grundsätzlich ändern?

**Comment by johappel** [comment]
Es spricht ja nichts dagegen, Links (auf nicht im materialpool vrohandene Ressourcen) direkt in der Beschreibung einzufügen. Verweise auf andere Materialien machen ja nur Sinn, wenn es diese anderen Materialien schon gibt oder du sicher stellen möchtest, dass die Velinkung dauerhaft korrekt ist.

**Comment by empeiria** [comment]
Eigentlich geht's ja nur um die Sendung. Die könnte auch noch direkter eingegeben werden:
http://ondemand.mdr.de/mp4audiomobil/digas-f8d549f1-c922-43b6-8a44-576a9e941695-74eb7cd9f4d9_f8.mp4
Dann ist sie auch direkt bei uns im Materialpool anzuhören.
Interessanter ist jedoch die Multimetia-Story:
http://reportage.mdr.de/glaubenssache#5583
Dieser "Pageflow" ist ja ein eigenes Material und hochwertiger produziert als nur die Audio-Sendung
Die youtube-Playlist ist auch gut:
https://www.youtube.com/watch?v=ndfxPHnpKAg&list=PLJ6HqaiVBhGbpW7YRt2uOIj6Ju8dkVli6
Da ist natürlich die Frage, ob man jedes einzelne Youtube-Video ebenfalls wieder als Einzelmaterialien eintragen sollte!
