### ISSUE TITLE
Bildquelle bei den News

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#75]
Irgendjemand hat mal die Möglich konstruiert, eine Bildquelle bei den News einzutragen. Wenn man an dem Bild arbeitet, rechts unten.
Ich habs mal benutzt und es sah nicht gut aus, deswegen habe ich es gelassen. Jetzt wollte ich dem nochmal nachgehen, damit es verbessert wird, aber es erscheint gar nichts! Ich habe bei Kurt Mikula, Lied des Monats Dezember, alles eingetragen, aber es erscheint nichts. Auch das mit den Lizenzen müsste überlegt werden, ob es nicht gleich gemacht wird, wie bei den Materialien.

http://news.rpi-virtuell.de/2016/11/30/so-koennte-es-weihnachten-werden/

**Comment by johappel** [comment]
Die Möglichkeit gibt es schon lange und ist schon öfter besprochen worden. Leider hält sich kaum einer dran: Die Bildquelle wird automatsich eingetragen, wenn sie bei den Medien hinterlegt wird

![grafik](https://cloud.githubusercontent.com/assets/307023/20746694/24691dc4-b6e7-11e6-8d48-f11ebb95d386.png)

**Comment by empeiria** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1091954/20878990/e4ca82f4-bad1-11e6-8e20-6dd76e7b65a9.png)
Das klappt schon @lehrruetsche - allerdings immer nur beim obersten Artikel der jeweiligen Kategorie.
