### ISSUE TITLE
Apostroph

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#78]
Kann sein, dass wir das schon mal hatten. Aber ich habe eben ein Material eingegeben, dass Apostrophe enthielt, entsprechend lustig sah es dann aus, als ich es bei der Organisation wieder aufgerufen habe.
http://material.rpi-virtuell.de/wp-admin/post.php?post=455&action=edit

**Comment by staude** [comment]
Was genau meinst du? Auf der Ausgabeseite der Orga ist das Material korrekt

Im Backend in dem Zuordnungsdialog - ja, das ist irgendwo in den untiefen des Pods Frameworks begründet.

**Comment by staude** [comment]
ping @lehr-ruetsche @lehrruetsche
