### ISSUE TITLE
Organisationstitel fehlt mal wieder

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#79]
![organisation name fehlt](https://cloud.githubusercontent.com/assets/17722241/20796328/009d9e48-b7d6-11e6-9744-2a19e2fe3675.png)

Diesmal war es nicht firefox sondern Chrome und der Name der Organisation taucht nicht auf.

Und beim MDR war der Titel da, als ich nur gespeichert habe und auf die Vorschau bin. Dann bin ich auf veröffentlichen und dann fehlte der Name.

**Comment by johappel** [comment]
![image](https://cloud.githubusercontent.com/assets/307023/20796535/d5703356-b7d6-11e6-8cce-f9c8d490f69c.png)

so sieht es bei mir im Chrome aus

**Comment by johappel** [comment]
Ich tippe mal drauf, dass du die Seite nicht neu geladen hast?

**Comment by lehr-ruetsche** [comment]
Okay, also: ich trage ein, speichere ab, gehe auf Vorschau: der Name ist da.
Ich gehe zurück, gehe auf veröffentlichen: der Name ist weg.
Habe ich jetzt bewusst zweimal beobachtet. Organisation 2: Mediendienst Integration.
