### ISSUE TITLE
Schlagworte und Synonyme Beispiel Wert und Werte

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#83]
Eben habe ich ein interessantes Material eingegeben, es ging um islamische Werteerziehung. Ich habe das Wort Islam eingegeben, kein Problem. Dann wollte ich Werte eingeben, aber das wurde nicht gefunden.
Also habe ich im OGND nachgeschaut und dort als Normwort "Wert" gefunden und als Synonym "Werte", obwohl das eigentlich doch zwei unterschiedliche Sachen sind. Ich habe brav "Wert" bei Schlagworte als neuen Begriff eingegeben und "Werte" bei den Synonymen. Nun habe ich es beim Material selbst wieder versucht mit "Werte", aber es wurde mir nur "Wert" angeboten. Ich hatte es so verstanden, dass eingegebene Synonyme auch angeboten wurden. Ansonsten würde ich mir in diesem Fall überlegen, ob ich nicht "Werte" als eigenes Schlagwort für uns anlege, weil es doch etwas anderes ist als "Wert".

**Comment by staude** [comment]
In dem Moment wo ein Wort ein Synonym ist, wird das Normwort als Schlagwort eingetragen.
