### ISSUE TITLE
Immer noch schwierig: Das Problem der reinen Fachinformation

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#84]
Die Zeitschrift zum Thema Islam, die ich eben eingebe, enthält im Grunde reine Fachinformationen, keine Unterrichtsvorschläge o.ä., ist also eine reine Fachinformation.
Aber zuerst kommen die Bildungsstufen und ich habe sie erst mal eingegeben, für die Jugendarbeit ist ein interessanter Artikel dabei, islamische Werteerziehung sollte man auch in der KITA kennen, dann lande ich bei den Altersstufen und von 0 - 99 ist alles angekreuzt.
Was wäre da jetzt richtig gewesen? Jetzt habe ich nur Fachinformation angekreuzt und 18 - 99 Jahre. Sonst nichts. Könnte man den Medientyp auch vor die Bildungsstufe nehmen? Dann wäre es etwas logischer. Und ich habe mir auch überlegt, warum die Sprache hier auftaucht und später nochmal. Kann man nicht die Sprache englisch/deutsch auch nach unten nehmen?

**Comment by johappel** [comment]
> Fachinformation
Die Vereinbarung war, das **Fachinformation bedeutet**, dass dieses Material unabhängig von der Zielgruppe _nur_ **für die Hand des Lehrers** gedacht ist!
> Kann man nicht die Sprache englisch/deutsch auch nach unten nehmen?
Die Reihenfolge der Metaboxen kann jeder Redakteuer individuell sortieren wie er es braucht
