### ISSUE TITLE
Ratings ausblenden ausser bei Material  - war: Sternchen bei den Synonymen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#87]
Man kann tatsächlich Synonyme mit Sternchen bewerten? Abgefahren...

**Comment by johappel** [comment]
nein, nur materialien

**Comment by staude** [comment]
naja, im backend hängt sich das plugin schon in alle posttypes. aber das wird an keiner stelle ausgewertet und im frontend ist es nur im material template von mir eingebaut.

wenn das stört, wird es noch bei den posttypes von mit entfernt.
