### ISSUE TITLE
Postleitzahlen - man kann keine Postleitzahl eingeben, die mit 0 beginnt

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#89]
Habe eine Postleitzahl aus Leipzig eingegeben, die mit einer 0 beginnt. Diese 0 wird automatisch gelöscht.

**Comment by staude** [comment]
Ja, ist ein int feld. wenn ich das auf text umstelle braucht es wieder Validierungscode das da nur 5 ziffern drinstehen

**Comment by johappel** [comment]
Validierung ändern
DE-<PLZ>
