### ISSUE TITLE
Logo erscheint nicht bei der EKiR

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#90]
Bei den Organisationen habe ich die Ev. Kirche des Rheinlandes eingegeben. Das Logo erscheint einfach nicht. 
http://material.rpi-virtuell.de/wp-admin/post.php?post=366&action=edit

**Comment by staude** [comment]
das logo erscheint, aber als logo ist http://www.ekir.de/www/img/_blank.gif anggeben, das ist ein  1x1 pixel leeres gif.

**Comment by staude** [comment]
Das logo ist eine background grfik und für uns so nicht nutzbar
http://www.ekir.de/www/css/img/bg-header.jpg

**Comment by staude** [comment]
Hab es selbst im Pressebereicht auf ekir.de nicht gefunden.
Dafür aber hier fündig geworden
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/EKIR_Logo.svg/1280px-EKIR_Logo.svg.png
Binde das jetzt ein
