### ISSUE TITLE
1000 Buchstaben

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/rw-materialpool#91]
Im alten rpi hatten wir bei der Beschreibung der Inhalte 1000 Buchstaben vorgegeben. Ich glaube, im neuen rpi-virtuell.de gibt es das nicht. Wäre die Frage, ob wir das nicht wieder so einrichten wollen.

**Comment by johappel** [comment]
Sehe ich im Momment noch keine Notwendigkeit

**Comment by johappel** [comment]
Eine Beschränkung würde nur bei der Kurzbeschreibung Sinn machen.
