### ISSUE TITLE
Wie löscht man aus fehlende Bildquellen einen Titel?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#93]
Ich kriegs nicht hin. Das MDR-YouTube-Bild kann ich in der Bildbearbeitung nicht löschen und in der Liste auch nicht. Dabei hat der Beitrag jetzt ein ganz anderes Bild. Wie geht der Trick-17?

**Comment by staude** [comment]
??? URL Bitte
