### ISSUE TITLE
Lizenzen bei den Bildern

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/rw-materialpool#94]
Die CC-Angaben bei den Lizenzen der Bildquellen sind äußert sparsam.

**Comment by staude** [comment]
Das ist kein Materialpool Problem, du meinst das Bildquellen Plugin auf News, oder?

**Comment by lehr-ruetsche** [comment]
Ja, genau, da kann ich nur 2.0 angeben!

**Comment by staude** [comment]
Dann bitte das bei den allgemeinen Issues unter https://github.com/rpi-virtuell/reliwerk/issues eintragen und hier nur Materialpoorelevantes. Danke.
